;; add package repository
(source gnu)
(source melpa)

;; Cask initialized package
;; http://posaune.hatenablog.com/entry/2014/06/17/221041
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "init-loader")

;; Python
(depends-on "epc")
(depends-on "py-autopep8")
(depends-on "jedi")
;; for jedi
(depends-on "deferred")
(depends-on "python-environment")
(depends-on "auto-complete")
(depends-on "jedi-core")
;; for sagemath
(depends-on "sage-shell-mode")

;; filer
(depends-on "direx")
(depends-on "dired-ranger")
(depends-on "ranger")

;; YaTeX
(depends-on "yatex")

;; high-light current line
(depends-on "hlinum")

;; ac-math
(depends-on "ac-math")

;; slack
(depends-on "slack")

;; mark-down mode+
(depends-on "markdown-mode+")

;; flycheck-pops-tip
(depends-on "flycheck-pos-tip")

;; color theme
(depends-on "color-theme-modern")
(depends-on "abyss-theme")
(depends-on "darktooth-theme")

;; fish shell mode
(depends-on "fish-mode")

;; heml
(depends-on "helm")

;; heml-gtags
(depends-on "helm-gtags")

;; Rust
(depends-on "rust-mode")
(depends-on "racer")
(depends-on "flycheck-rust")