function CheckATagSpanChildElement(b){b=b.FindInsertNode();var a=!1;if(b&&b.childNodes)for(var c=0;c<b.childNodes.length;++c){var d=b.childNodes[c];if(d&&d.tagName&&"SPAN"==d.tagName.toUpperCase()){a=!0;break}}b.NotHighLight=a}function TSSRBiglobeTopSponsorFetchTargetURL(b){var a=b.match(/[&\?]q=(.+)$/);return a&&2==a.length?a[1]:b}function TSSRBiglobeTopSponsorFetchTargetURL1(b,a){var c=new RegExp("^(http|https)://"+b,"i");return/^(http|https):\/\//i.test(a)&&!c.test(a)?a:""}
function TSSRBiglobeFindInsertNode(){var b=this.node;if(this.baseNode&&this.baseNode.firstChild&&"SPAN"==this.baseNode.firstChild.nodeName){var a=this.baseNode.firstChild.getElementsByTagName("H3");1==a.length&&(b=a[0])}return b}function TSRBiglobeModifyCSS(b,a){var c=b.FindInsertNode();if(c&&c.style){b.spanIcon=document.createElement("SPAN");(new TMDOMObj(b.spanIcon)).style.setFloat("left");var d=a+parseInt(D_GAP_BETWEEN_ICON_TITLE);c.style.marginLeft=d+"px"}}
function TSSRBiglobeFetchTargetURL(b,a){var c="";if(/^(http|https):\/\//i.test(a)){if((new RegExp(b,"i")).test(a))return"";c=a}return c}function TSSRGetClass(b){var a="";return a=document.all?b.className:b.getAttribute("class")}
function TSSRBiglobeParseResult1(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(b,a,"H3",null);b=new CreateTSRLocatedObject(b,a,"DIV","main");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=b[a],d="";c&&"a-sr"==TSSRGetClass(c)&&(d=b[a].href);0!=d.length&&CreateTSRResultObject(c,d)}}
function TSSRBiglobeParseResult2(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(b,a,"H3",null);b=new CreateTSRLocatedObject(b,a,"DIV","searchResult");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=b[a],d="";c&&"a-sr"==TSSRGetClass(c)&&(d=b[a].href);0!=d.length&&CreateTSRResultObject(c,d)}}
function TSSRBiglobeTopSponsor1(b){var a=new CreateTSRLocatedObject(null,null,"H3",null),a=new CreateTSRLocatedObject(null,a,"A",null),a=new CreateTSRLocatedObject(null,a,"DIV",null);b=new CreateTSRLocatedObject(b,a,"DIV",null);b.appendAttribute("class","^sl-wrap");b.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=b[a];c&&"a-sl"==TSSRGetClass(c.parentNode)&&(c=CreateTSRResultObject(b[a],b[a].parentNode.href),TSRBiglobeModifyCSS(c,0))}}
function TSSRBiglobeTopSponsor2(b){var a=new CreateTSRLocatedObject(null,null,"H3",null),a=new CreateTSRLocatedObject(null,a,"A",null),a=new CreateTSRLocatedObject(b,a,"DIV",null);a.appendAttribute("class","^rl");a.multiMatches=!0;if(a=a.findElement()){a=GetAllTSRLocatedNodes(a);b=b.location.host;for(var c=0;c<a.length;c++){var d=TSSRBiglobeTopSponsorFetchTargetURL1(b,a[c].parentNode.href);0!=d.length&&(d=CreateTSRResultObject(a[c],d),TSRBiglobeModifyCSS(d,0))}}}
function TSSRBiglobeAboutSite(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"DIV",null),c=new CreateTSRLocatedObject(null,a,"LI",null);b=new CreateTSRLocatedObject(b,c,"OL",null);a.multiMatches=!0;a.appendAttribute("class","rl");c.multiMatches=!0;b.appendAttribute("class","ol-rl");b.multiMatches=!0;if(rgobjPath=b.findElement())for(b=GetAllTSRLocatedNodes(rgobjPath),a=0;a<b.length;a++)CreateTSRResultObject(b[a],b[a].href)}
function TSSRBiglobeTopSponsor3(b){var a=new CreateTSRLocatedObject(null,null,"SPAN",null),c=new CreateTSRLocatedObject(null,a,"A",null),d=new CreateTSRLocatedObject(null,c,"DIV",null),e=new CreateTSRLocatedObject(b,d,"DIV",null);a.appendAttribute("class","sp_t");c.appendAttribute("class","a-sl");d.appendAttribute("class","sl-wrap");d.multiMatches=!0;e.appendAttribute("class","^sponArea");e.multiMatches=!0;if(a=e.findElement())for(a=GetAllTSRLocatedNodes(a),b=b.location.host,c=0;c<a.length;c++)d=
TSSRBiglobeTopSponsorFetchTargetURL1(b,a[c].parentNode.href),0!=d.length&&(d=CreateTSRResultObject(a[c],d),TSRBiglobeModifyCSS(d,0))}
function TSSRBiglobeTopSponsor4(b){var a=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,a,"DIV",null),d=new CreateTSRLocatedObject(b,c,"DIV",null);a.appendAttribute("class","a-sl");a.multiMatches=!0;c.appendAttribute("class","sl");c.multiMatches=!0;d.appendAttribute("class","^sponArea");d.multiMatches=!0;if(a=d.findElement())for(a=GetAllTSRLocatedNodes(a),b=b.location.host,c=0;c<a.length;c++)d=TSSRBiglobeTopSponsorFetchTargetURL1(b,a[c].href),0!=d.length&&(d=CreateTSRResultObject(a[c],
d),TSRBiglobeModifyCSS(d,0))}
function TSSRBiglobeTopSponsor5(b){var a=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,a,"OL",null),d=new CreateTSRLocatedObject(b,c,"DIV",null);a.multiMatches=!0;c.appendAttribute("class","ol-rl ol-jw");c.multiMatches=!0;d.appendAttribute("class","^sponArea");d.multiMatches=!0;if(a=d.findElement())for(a=GetAllTSRLocatedNodes(a),b=b.location.host,c=0;c<a.length;c++)d=TSSRBiglobeTopSponsorFetchTargetURL1(b,a[c].href),0!=d.length&&(d=CreateTSRResultObject(a[c],d),
TSRBiglobeModifyCSS(d,0))}g_bIsNeedCheckSPan=!0;TSRTagFlowID();
function TSRParse(){var b=g_oEnv.Parser.iResultNumber;TSSRBiglobeParseResult1(document);TSSRBiglobeParseResult2(document);TSSRBiglobeTopSponsor1(document);TSSRBiglobeTopSponsor2(document);TSSRBiglobeTopSponsor3(document);TSSRBiglobeTopSponsor4(document);TSSRBiglobeTopSponsor5(document);TSSRBiglobeAboutSite(document);TrendMicro.TB.ReduceNewNode(b+1);for(b=1;b<g_oEnv.Parser.rgobjSearchResult.length;b++)g_oEnv.Parser.rgobjSearchResult[b]&&CheckATagSpanChildElement(g_oEnv.Parser.rgobjSearchResult[b]);
return g_oEnv.Parser.rgobjSearchResult};
