function CheckATagSpanChildElement(a){a=a.FindInsertNode();var b=!1;if(a&&a.childNodes)for(var c=0;c<a.childNodes.length;++c){var d=a.childNodes[c];if(d&&d.tagName&&"CITE"==d.tagName.toUpperCase()){b=!0;break}}a.NotHighLight=b}function filterbyHref(a){for(var b=["http://www.bing.com/search?"],c=0;c<b.length;c++)if(ptn=new RegExp(b[c],"i"),ptn.test(a))return!0;return!1}
function TSRMSNModifyCSS(a,b){var c=a.FindInsertNode();if(c&&c.style){a.spanIcon=document.createElement("SPAN");(new TMDOMObj(a.spanIcon)).style.setFloat("left");var d=b+parseInt(D_GAP_BETWEEN_ICON_TITLE);c.style.marginLeft=d+"px"}}function TSSRMSNFindInsertNode(){var a=this.node;if(this.baseNode&&this.baseNode.firstChild&&"SPAN"==this.baseNode.firstChild.nodeName){var b=this.baseNode.firstChild.getElementsByTagName("H3");1==b.length&&(a=b[0])}return a}
function TSSRMSNLiveCutPrefixURL(a){var b=a.match(/\s*\-\s+([^\s]+)$/);return b&&2==b.length?b[1]:a}
function TSSRMSBingParseNewsResult(a){var b=new CreateTSRLocatedObject(null,null,"a",null),b=new CreateTSRLocatedObject(null,b,"DIV",null),c=new CreateTSRLocatedObject(d,b,"DIV",null),d=new CreateTSRLocatedObject(a,c,"DIV","sw_main");c.multiMatches=!0;c.appendAttribute("class","NewsResultSet");b.multiMatches=!0;b.appendAttribute("class","sn_r");if(a=d.findElement())for(a=GetAllTSRLocatedNodes(a),d=0;d<a.length;d++)CreateTSRResultObject(a[d],a[d].href,null,null,null,!0)}
function TSSRMSBingParseLatestNews(a){var b=new CreateTSRLocatedObject(null,null,"a",null),b=new CreateTSRLocatedObject(null,b,"DIV",null),c=new CreateTSRLocatedObject(d,b,"DIV",null),d=new CreateTSRLocatedObject(a,c,"DIV","sw_main");c.multiMatches=!0;c.appendAttribute("class","sn_latest");b.multiMatches=!0;b.appendAttribute("class","sn_art");if(a=d.findElement())for(a=GetAllTSRLocatedNodes(a),d=0;d<a.length;d++)CreateTSRResultObject(a[d],a[d].href,null,null,null,!0)}
function TSSRMSBingParseResult_H3(a){var b=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,b,"H3",null);a=new CreateTSRLocatedObject(a,c,"DIV","results");c.multiMatches=!0;b.multiMatches=!1;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),c=0;c<b.length;c++)CreateTSRResultObject(b[c],b[c].href,null,null,null,!0)}
function TSSRMSBingParseResult_H2(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"H2",null);a=new CreateTSRLocatedObject(a,b,"DIV","results");b.multiMatches=!0;if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)CreateTSRResultObject(a[b],a[b].href,null,null,null,!0)}
function TSSRMSBingParseSidebarSponsor(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"DIV",null);a=new CreateTSRLocatedObject(a,b,"DIV","sidebar");b.appendAttribute("class","^sb_adsN");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)CreateTSRResultObject(a[b],a[b].href,null,null,null,!0)}
function TSSRMSBingTopSponsor(a){var b=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,b,"li",null),d=new CreateTSRLocatedObject(null,c,"ul",null),e=new CreateTSRLocatedObject(null,d,"DIV",null);a=new CreateTSRLocatedObject(a,e,"DIV","results_container");e.appendAttribute("class","^sb_adsW");e.multiMatches=!0;d.multiMatches=!0;c.multiMatches=!0;b.multiMatches=!1;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),c=0;c<b.length;c++)CreateTSRResultObject(b[c],b[c].href,
null,null,null,!0)}
function TSSRMSBingTopSponsor2(a){var b=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,b,"H3",null),d=new CreateTSRLocatedObject(null,c,"DIV",null),e=new CreateTSRLocatedObject(null,d,"DIV",null);a=new CreateTSRLocatedObject(a,e,"DIV","results_container");e.appendAttribute("class","sb_adsWv2");e.multiMatches=!0;d.appendAttribute("class","sb_add sb_adW");d.multiMatches=!0;c.multiMatches=!0;b.multiMatches=!1;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),c=0;c<
b.length;c++)CreateTSRResultObject(b[c],b[c].href,null,null,null,!0)}function TSSRMSBingBingNews(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"DIV",null);a=new CreateTSRLocatedObject(a,b,"DIV","results_area");b.appendAttribute("class","ans_art");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)CreateTSRResultObject(a[b],a[b].href,null,null,null,!0)}
function TSSRMSBingBingNews2(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"h2",null);a=new CreateTSRLocatedObject(a,b,"OL","b_results");b.multiMatches=!0;if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)CreateTSRResultObject(a[b],a[b].href,null,null,null,!0)}
function TSSRMSBingTopAds(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"span",null);a=new CreateTSRLocatedObject(a,b,"DIV","results_container");b.appendAttribute("class","sx_b");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)filterbyHref(a[b].href)||CreateTSRResultObject(a[b],a[b].href,null,null,null,!0)}
function TSSRMSBingBottomAds(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"DIV",null);a=new CreateTSRLocatedObject(a,b,"DIV","results_container");b.appendAttribute("class","^sb_adsW sb_adsW2");b.multiMatches=!0;if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)CreateTSRResultObject(a[b],a[b].href,null,null,null,!0)}
function TSSRMSBingResultItemDetail(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);a.appendAttribute("class","^sb_vdl");a.multiMatches=!0;if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)CreateTSRResultObject(a[b],a[b].href,null,null,null,!0)}
function TSSRMSBingDeepLinks(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);a.multiMatches=!0;b.multiMatches=!0;a.appendAttribute("class","b_deep");if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)CreateTSRResultObject(b[a],b[a].href)}
function TSSRMSBingComponents(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);a.multiMatches=!0;b.multiMatches=!0;a.appendAttribute("class","^bm_ctn");if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)CreateTSRResultObject(b[a],b[a].href)}
function TSSRMSBingHeaderRelated(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);b.multiMatches=!0;a.appendAttribute("class","headerRelated");if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)CreateTSRResultObject(b[a],b[a].href)}g_bIsNeedCheckSPan=!0;TSRTagFlowID();
function TSRParse(){var a=g_oEnv.Parser.iResultNumber;TrendMicro.TB.DOMIdExist("results")&&(TSSRMSBingParseResult_H2(document),TSSRMSBingParseResult_H3(document));TrendMicro.TB.DOMIdExist("sw_main")&&(TSSRMSBingParseNewsResult(document),TSSRMSBingParseLatestNews(document));TrendMicro.TB.DOMIdExist("sidebar")&&TSSRMSBingParseSidebarSponsor(document);TrendMicro.TB.DOMIdExist("results")&&TSSRMSBingBingNews(document);TrendMicro.TB.DOMIdExist("b_results")&&TSSRMSBingBingNews2(document);TrendMicro.TB.DOMIdExist("results_container")&&
(TSSRMSBingTopAds(document),TSSRMSBingTopSponsor2(document),TSSRMSBingTopSponsor(document));TSSRMSBingHeaderRelated(document);TrendMicro.TB.ReduceNewNode(a+1);TSSRMSBingDeepLinks(document);for(a=1;a<g_oEnv.Parser.rgobjSearchResult.length;a++)g_oEnv.Parser.rgobjSearchResult[a]&&CheckATagSpanChildElement(g_oEnv.Parser.rgobjSearchResult[a]);return g_oEnv.Parser.rgobjSearchResult};
