function filterbyHref(b){for(var a=["^https?://translate.google.cn/","https?://(.*).google.(.*)/(search|images|maps)\\?"],c=0;c<a.length;c++)if(ptn=new RegExp(a[c],"i"),ptn.test(b))return!0;return!1}function TSSRGoogleFetchTargetURL(b){var a=/&adurl=(http[^&]+)[&]?/;if((a=b.match(a))&&2==a.length)return a[1];a=/url\?q=(http[^&]+)[&]?/;if((a=b.match(a))&&2==a.length)return a[1];a=/&url=(http[^&]+)[&]?/;return(a=b.match(a))&&2==a.length?a[1]:b}
function TSSRGoogleSetMarginForIcon(b){(new TMDOMObj(b.previousSibling.childNodes[0])).style.setMargin("0 0 4px 0")}function TSSRGoogleParseResult(b){var a=new CreateTSRLocatedObject(null,null,"A",null);if(b=(new CreateTSRLocatedObject(b,a,"DIV","res")).findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=TSSRGoogleFetchTargetURL(b[a].href);CreateTSRResultObject(b[a],c,null,null,TSSRGoogleSetMarginForIcon)}}
function TSSRGoogleParseResult1(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"H3",null),c=new CreateTSRLocatedObject(null,a,"LI",null);b=new CreateTSRLocatedObject(b,c,"DIV","res");c.multiMatches=!0;c.appendAttribute("class","^g");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)c=TSSRGoogleFetchTargetURL(b[a].href),filterbyHref(c)||CreateTSRResultObject(b[a],c,null,null,TSSRGoogleSetMarginForIcon)}
function TSSRGoogleParseNewsInResult(b){var a=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,a,"DIV",null);b=new CreateTSRLocatedObject(b,c,"DIV","res");a.multiMatches=!0;c.appendAttribute("class","mnr-c");c.multiMatches=!0;if(a=b.findElement())for(a=GetAllTSRLocatedNodes(a),c=0;c<a.length;c++)b=TSSRGoogleFetchTargetURL(a[c].href),filterbyHref(b)||CreateTSRResultObject(a[c],b,null,null,TSSRGoogleSetMarginForIcon)}
function TSSRGoogleParseResult2(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"H3",null),c=new CreateTSRLocatedObject(null,a,"DIV",null);b=new CreateTSRLocatedObject(b,c,"DIV","res");c.multiMatches=!0;c.appendAttribute("class","g");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)c=TSSRGoogleFetchTargetURL(b[a].href),filterbyHref(c)||CreateTSRResultObject(b[a],c,null,null,TSSRGoogleSetMarginForIcon)}
function TSSRGoogleParseResult3(b){var a=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,a,"DIV",null);b=new CreateTSRLocatedObject(b,c,"DIV","res");c.multiMatches=!0;c.appendAttribute("class","card-section$");a.multiMatches=!0;if(a=b.findElement())for(a=GetAllTSRLocatedNodes(a),c=0;c<a.length;c++)b=TSSRGoogleFetchTargetURL(a[c].href),filterbyHref(b)||CreateTSRResultObject(a[c],b,null,null,TSSRGoogleSetMarginForIcon)}
function TSSRGoogleParseResult_Blog(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"LI",null),c=new CreateTSRLocatedObject(null,a,"LI",null);b=new CreateTSRLocatedObject(b,c,"DIV","ires");c.multiMatches=!0;c.appendAttribute("class","^g");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)c=TSSRGoogleFetchTargetURL(b[a].href),filterbyHref(c)||CreateTSRResultObject(b[a],c,null,null,TSSRGoogleSetMarginForIcon)}
function TSSRGoogleParseNewsResultResult1(b){var a=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,a,"SPAN",null),d=new CreateTSRLocatedObject(null,a,"LI",null);b=new CreateTSRLocatedObject(b,d,"LI","newsbox");d.multiMatches=!0;d.appendAttribute("class","^w0");c.multiMatches=!0;c.appendAttribute("class","^tl");a.multiMatches=!0;a.appendAttribute("class","^l");if(a=b.findElement())for(a=GetAllTSRLocatedNodes(a),c=0;c<a.length;c++)d=TSSRGoogleFetchTargetURL(a[c].href),
CreateTSRResultObject(a[c],d,null,null,TSSRGoogleSetMarginForIcon)}
function TSSRGoogleParseNewsResultResultIE7(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"TABLE",null),c=new CreateTSRLocatedObject(null,a,"LI",null);b=new CreateTSRLocatedObject(b,c,"DIV","center_col");c.multiMatches=!0;c.appendAttribute("class","g");a.multiMatches=!0;a.appendAttribute("class","ts");if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)c=TSSRGoogleFetchTargetURL(b[a].href),b[a].className&&"fl"==b[a].className||filterbyHref(c)||
CreateTSRResultObject(b[a],c,null,null,TSSRGoogleSetMarginForIcon)}
function TSSRGoogleParseTopSponsorIE7(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"TABLE",null),c=new CreateTSRLocatedObject(null,a,"LI",null);b=new CreateTSRLocatedObject(b,c,"DIV","center_col");c.multiMatches=!0;c.appendAttribute("class","taf");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)c=TSSRGoogleFetchTargetURL(b[a].href),CreateTSRResultObject(b[a],c,null,null,TSSRGoogleSetMarginForIcon)}
function TSSRGoogleParseLyrics(b){var a=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,a,"H2",null),d=new CreateTSRLocatedObject(null,c,"DIV",null);b=new CreateTSRLocatedObject(b,d,"DIV","res");d.multiMatches=!0;d.appendAttribute("class","^g$");d.appendAttribute("style",null);c.multiMatches=!0;c.appendAttribute("class","^r$");a.appendAttribute("class",null);if(a=b.findElement())for(a=GetAllTSRLocatedNodes(a),c=0;c<a.length;c++)d=TSSRGoogleFetchTargetURL(a[c].href),
CreateTSRResultObject(a[c],d,null,null,TSSRGoogleSetMarginForIcon)}function TSSRGoogleFindInsertNode(){var b=this.node;if(this.baseNode&&this.baseNode.firstChild&&"SPAN"==this.baseNode.firstChild.nodeName){var a=this.baseNode.firstChild.getElementsByTagName("H3");1==a.length&&(b=a[0])}return b}
function TSRGoogleModifyCSS(b,a){var c=b.FindInsertNode();if(c&&c.style){b.spanIcon=document.createElement("SPAN");(new TMDOMObj(b.spanIcon)).style.setFloat("left");var d=a+parseInt(D_GAP_BETWEEN_ICON_TITLE);c.style.marginLeft=d+"px"}}
function TSSRGoogleParseSidebarSponsor(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"H3",null),a=new CreateTSRLocatedObject(null,a,"LI",null);b=new CreateTSRLocatedObject(b,a,"TABLE","mbEnd");a.tagIDregexFirst=!0;a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=TSSRGoogleFetchTargetURL(b[a].href);CreateTSRResultObject(b[a],c,null,null,TSSRGoogleSetMarginForIcon)}}
function TSSRGoogleParseTopSponsor(b){var a=new CreateTSRLocatedObject(null,null,"A","^pa\\d+$"),c=new CreateTSRLocatedObject(b,a,"DIV","tads");b=new CreateTSRLocatedObject(b,a,"DIV","res");a.tagIDregexFirst=!0;(a=c.findElement())||(a=b.findElement());if(a)for(a=GetAllTSRLocatedNodes(a),c=0;c<a.length;c++)b=TSSRGoogleFetchTargetURL(a[c].href),CreateTSRResultObject(a[c],b,null,null,TSSRGoogleSetMarginForIcon)}
function TSSRGoogleParseBottomSponsor(b){var a=new CreateTSRLocatedObject(null,null,"A","^pab\\d+$");b=new CreateTSRLocatedObject(b,a,"DIV","bottomads");a.tagIDregexFirst=!0;if(a=b.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=TSSRGoogleFetchTargetURL(a[b].href);CreateTSRResultObject(a[b],c,null,null,TSSRGoogleSetMarginForIcon)}}
function TSSRGoogleParseBottomSponsorIE7(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"H3",null),c=new CreateTSRLocatedObject(null,a,"OL",null),d=new CreateTSRLocatedObject(null,c,"DIV",null);b=new CreateTSRLocatedObject(b,d,"DIV","center_col");d.multiMatches=!0;c.multiMatches=!0;a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)c=TSSRGoogleFetchTargetURL(b[a].href),filterbyHref(c)||CreateTSRResultObject(b[a],c,
null,null,TSSRGoogleSetMarginForIcon)}g_bIsNeedCheckSPan=!0;TSRTagFlowID();
function TSRParse(){var b=g_oEnv.Parser.iResultNumber;TrendMicro.TB.DOMIdExist("res")&&(TSSRGoogleParseResult1(document),TSSRGoogleParseResult2(document),TSSRGoogleParseResult3(document),TSSRGoogleParseNewsInResult(document));TrendMicro.TB.DOMIdExist("ires")&&TSSRGoogleParseResult_Blog(document);TrendMicro.TB.DOMIdExist("newsbox")&&TSSRGoogleParseNewsResultResult1(document);TrendMicro.TB.DOMIdExist("center_col")&&TSSRGoogleParseNewsResultResultIE7(document);TrendMicro.TB.DOMIdExist("res")&&TSSRGoogleParseLyrics(document);
TrendMicro.TB.DOMIdExist("mbEnd")&&TSSRGoogleParseSidebarSponsor(document);TSSRGoogleParseTopSponsor(document);TrendMicro.TB.DOMIdExist("center_col")&&TSSRGoogleParseTopSponsorIE7(document);TrendMicro.TB.DOMIdExist("bottomads")&&TSSRGoogleParseBottomSponsor(document);TrendMicro.TB.DOMIdExist("center_col")&&TSSRGoogleParseBottomSponsorIE7(document);TrendMicro.TB.ReduceNewNode(b+1);return g_oEnv.Parser.rgobjSearchResult};
