function TSSRLinkedInFetchTargetURL(a){var b=a;(a=a.match(/[&\?]url=(.+)$/))&&2==a.length&&(b=decodeURIComponent(a[1].split("&")[0]),"http"!=b.substr(0,4)&&"ftp"!=b.substr(0,3)&&(b="http://"+b));return b}function TSRLinkedInModifyCSS(a){(new TMDOMObj(a)).style.setFloat("none")}
function filterbyHref(a){for(var b="https?://www\\.linkedin\\.com/(#|(.*)trk=tod-art(.*)|lite|reconnect|anet|groupMsg|answers|static|createGroup|nhome|groupfollowing|groupRegistration|forwardProfileMsg|search|secure|updates|profile|groups|groupItem|groupAnswers|pymk|home|share(.*)trk=NUS_UNIU_SHARE-pic|mfeed|msgToConns|mbox|groupInvitation|inbox|blink|company|share\\?displayShare|today|signal|recRequests|pub|organizer|requestList|inviteFromProfile|csearch|subscriptionv2) https?://www\\.linkedin\\.com/(.*)url=(https?://(www\\.)?linkedin\\.com|https?%3A%2F%2F(www%2E)?linkedin(%2Ecom)?|https?%3A%2F%2F(www%2E)?twitter%2Ecom) javascript http://www.linkedin.com/companies http://www.linkedin.com/company http://www.linkedin.com/@ https://www.linkedin.com/@ http://www.linkedin.com/jsearch http://signal/ http://www.linkedin.com/nus-trk?trkact=viewJobPosting http://www.linkedin.com/jobs? http://[A-Za-z][A-Za-z].linkedin.com/pub http://www.linkedin.com/connections http://www.linkedin.com/manageGroupMembers http://www.linkedin.com/manageGroup http://www.linkedin.com/groupNews ^http://www.linkedin.com/\\?trk=hb-0-h-logo# ^https?://www\\.linkedin\\.com/((skills)|(people))/".split(" "),c=
0;c<b.length;c++)if(ptn=new RegExp(b[c],"i"),ptn.test(a))return!0;return!1}
function TBParseHome(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"P",null),c=new CreateTSRLocatedObject(null,b,"DIV",null);a=new CreateTSRLocatedObject(a,c,"DIV","content");c.appendAttribute("class","content");c.multiMatches=!0;b.multiMatches=!0;if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)c=TSSRLinkedInFetchTargetURL(a[b].href),filterbyHref(c)||CreateTSRResultObject(a[b],c,null,null,TSRLinkedInModifyCSS)}
function TBParseProfile_OverView(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"D1","overview");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=TSSRLinkedInFetchTargetURL(b[a].href);filterbyHref(c)||CreateTSRResultObject(b[a],c,null,null,TSRLinkedInModifyCSS)}}
function TBParseProfile_Additional(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV","profile-additional");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=TSSRLinkedInFetchTargetURL(b[a].href);filterbyHref(c)||CreateTSRResultObject(b[a],c,null,null,TSRLinkedInModifyCSS)}}
function TBParseProfileActivity(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"DIV",null);a=new CreateTSRLocatedObject(a,b,"li",null);a.multiMatches=!0;a.appendAttribute("class","feed-item");b.multiMatches=!0;b.appendAttribute("class","feed-content");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=TSSRLinkedInFetchTargetURL(a[b].href);filterbyHref(c)||CreateTSRResultObject(a[b],c,null,null,TSRLinkedInModifyCSS)}}
function TBParseAnswers(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);a.appendAttribute("class","answersbox");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=TSSRLinkedInFetchTargetURL(b[a].href);filterbyHref(c)||CreateTSRResultObject(b[a],c,null,null,TSRLinkedInModifyCSS)}}
function TBParseInboxBody(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);a.appendAttribute("class","inbox-item-body");a.multiMatches=!0;b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=TSSRLinkedInFetchTargetURL(b[a].href);filterbyHref(c)||CreateTSRResultObject(b[a],c,null,null,TSRLinkedInModifyCSS)}}
function TBParseJobs_ViewJob(a){var b=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,b,"td",null),d=new CreateTSRLocatedObject(null,c,"DIV",null);a=new CreateTSRLocatedObject(a,d,"DIV","lui-panel-body");d.appendAttribute("class","details");c.multiMatches=!0;b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),c=0;c<b.length;c++)d=TSSRLinkedInFetchTargetURL(b[c].href),filterbyHref(d)||CreateTSRResultObject(b[c],d,null,null,TSRLinkedInModifyCSS)}
function TBParseCompany_Mentioned_In_News(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"DIV",null);a=new CreateTSRLocatedObject(a,b,"DIV","extra");b.appendAttribute("class","news content inner-mod");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=TSSRLinkedInFetchTargetURL(a[b].href);filterbyHref(c)||CreateTSRResultObject(a[b],c,null,null,TSRLinkedInModifyCSS)}}
function TBParseCompany_Basic_Info(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"DIV",null);a=new CreateTSRLocatedObject(a,b,"DIV","extra");b.appendAttribute("class","basic-info");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=TSSRLinkedInFetchTargetURL(a[b].href);filterbyHref(c)||CreateTSRResultObject(a[b],c,null,null,TSRLinkedInModifyCSS)}}
function TBParseCompany_Main_Page(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"li",null),c=new CreateTSRLocatedObject(null,b,"ul",null);a=new CreateTSRLocatedObject(a,c,"DIV",null);a.appendAttribute("class","nus-feed");c.multiMatches=!0;b.multiMatches=!0;if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)c=TSSRLinkedInFetchTargetURL(a[b].href),filterbyHref(c)||CreateTSRResultObject(a[b],c,null,null,TSRLinkedInModifyCSS)}
function TBParseCompany_Activity(a){var b=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,b,"li",null);a=new CreateTSRLocatedObject(a,c,"ul","yui-gen5");c.multiMatches=!0;b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),c=0;c<b.length;c++)a=TSSRLinkedInFetchTargetURL(b[c].href),filterbyHref(a)||CreateTSRResultObject(b[c],a,null,null,TSRLinkedInModifyCSS)}
function TBParseNews_Signal(a){var b=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,b,"li",null);a=new CreateTSRLocatedObject(a,c,"ol","result-set");c.multiMatches=!0;b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),c=0;c<b.length;c++)a=TSSRLinkedInFetchTargetURL(b[c].href),filterbyHref(a)||CreateTSRResultObject(b[c],a,null,null,TSRLinkedInModifyCSS)}
function TBParseGroup_Content(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);a.multiMatches=!0;a.appendAttribute("class","user-contributed");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=TSSRLinkedInFetchTargetURL(a[b].href);filterbyHref(c)||CreateTSRResultObject(a[b],c,null,null,TSRLinkedInModifyCSS)}}
function TBParseGroup_Comments(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"P",null);a.multiMatches=!0;a.appendAttribute("class","commenter");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=TSSRLinkedInFetchTargetURL(a[b].href);filterbyHref(c)||CreateTSRResultObject(a[b],c,null,null,TSRLinkedInModifyCSS)}}
function TBParseSignal_Who_Shared_This_Headline(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV","whoShared-result-ajax");a.multiMatches=!0;if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=TSSRLinkedInFetchTargetURL(a[b].href);filterbyHref(c)||CreateTSRResultObject(a[b],c,null,null,TSRLinkedInModifyCSS)}}
function TBParseSignal_Shared_Headline(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);a.multiMatches=!0;a.appendAttribute("class","share-headline");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=TSSRLinkedInFetchTargetURL(a[b].href);filterbyHref(c)||CreateTSRResultObject(a[b],c,null,null,TSRLinkedInModifyCSS)}}
function TBParseGroups_Latest_Discussion(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);a.multiMatches=!0;a.appendAttribute("class","popular-content");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=TSSRLinkedInFetchTargetURL(a[b].href);filterbyHref(c)||CreateTSRResultObject(a[b],c,null,null,TSRLinkedInModifyCSS)}}
function TBParseGroup_About_This_Group(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"li",null),c=new CreateTSRLocatedObject(null,b,"DIV",null);a=new CreateTSRLocatedObject(a,c,"DIV",null);a.appendAttribute("class","sidebar");a.multiMatches=!0;c.appendAttribute("class","content");c.multiMatches=!0;b.multiMatches=!0;if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)c=TSSRLinkedInFetchTargetURL(a[b].href),filterbyHref(c)||CreateTSRResultObject(a[b],
c,null,null,TSRLinkedInModifyCSS)}
function TBParseCompany_Sidebar_Ads(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"H5",null),c=new CreateTSRLocatedObject(null,b,"DIV",null);a=new CreateTSRLocatedObject(a,c,"DIV","extra-search-ads");a.multiMatches=!0;c.appendAttribute("class","section ads");c.multiMatches=!0;b.multiMatches=!0;if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)c=TSSRLinkedInFetchTargetURL(a[b].href),filterbyHref(c)||CreateTSRResultObject(a[b],c,null,
null,TSRLinkedInModifyCSS)}g_bIsNeedCheckSPan=!0;TSRTagFlowID();
function TSRParse(){var a=g_oEnv.Parser.iResultNumber;TBParseHome(document);TrendMicro.TB.DOMIdExist("overview")&&TBParseProfile_OverView(document);TrendMicro.TB.DOMIdExist("profile-additional")&&TBParseProfile_Additional(document);TBParseProfileActivity(document);TBParseAnswers(document);TBParseInboxBody(document);TrendMicro.TB.DOMIdExist("lui-panel-body")&&TBParseJobs_ViewJob(document);TrendMicro.TB.DOMIdExist("extra")&&(TBParseCompany_Mentioned_In_News(document),TBParseCompany_Basic_Info(document),
TBParseCompany_Main_Page(document));TrendMicro.TB.DOMIdExist("yui-gen5")&&TBParseCompany_Activity(document);TrendMicro.TB.DOMIdExist("result-set")&&TBParseNews_Signal(document);TBParseGroup_Content(document);TBParseGroup_Comments(document);TBParseGroup_About_This_Group(document);TrendMicro.TB.DOMIdExist("whoShared-result-ajax")&&TBParseSignal_Who_Shared_This_Headline(document);TBParseSignal_Shared_Headline(document);TBParseGroups_Latest_Discussion(document);TrendMicro.TB.DOMIdExist("extra-search-ads")&&
TBParseCompany_Sidebar_Ads(document);TrendMicro.TB.ReduceNewNode(a+1);return g_oEnv.Parser.rgobjSearchResult};
