var PSBackground={PageList:{LocalPage_Background:{port:null,tabID:null}},SendMessageToLocalPage:function(a){try{PSBackground.PageList.LocalPage_Background.port.postMessage(a)}catch(d){}},SendMessageToContentPage:function(a,d){try{PSBackground.PageList[a].port.postMessage(d)}catch(c){}},UpdateUBM:function(){"undefined"!=typeof PSBGWrapper.PrivacyScannerUpdateUBM&&PSBGWrapper.PrivacyScannerUpdateUBM()},OpenHelpPage:function(a){switch(a.dataIn.help_type){case "privacy_scanner_help":"undefined"!=typeof PSBGWrapper.ShowPSHelpPage&&
PSBGWrapper.ShowPSHelpPage();break;case "privacy_scanner_faq_help":"undefined"!=typeof PSBGWrapper.ShowPSFAQHelpPage&&PSBGWrapper.ShowPSFAQHelpPage(a.dataIn.help_website,a.dataIn.help_id)}},PSSettingSyncUp:function(a){if("undefined"!=typeof PSBGWrapper.PrivacyScannerSetting){var d=a.dataIn.setting_type,c=a.dataIn.setting_items;"get"==d?(d=PSBGWrapper.PrivacyScannerSetting(c,d),c=TMExt_$.parseJSON(TMExt_$.toJSON(a)),c.type="privacy_scanner_setting_result",c.dataOut={setting_items:d},d=TMExt_$.toJSON(c),
"local"==a.source?PSBackground.SendMessageToLocalPage(d):PSBackground.SendMessageToContentPage(a.dataIn.destination,d)):PSBGWrapper.PrivacyScannerSetting(c,d)}},PSCollectData:function(a){"undefined"!=typeof PSBGWrapper.PrivacyScannerCollectData&&PSBGWrapper.PrivacyScannerCollectData(a)},DoAJAX:function(a){var d=function(a){a.type="ajax_request_result";a=TMExt_$.toJSON(a);PSBackground.SendMessageToLocalPage(a)},c=a.dataIn.params,b=0,e=function(){TMExt_$.ajax({type:c.type,url:c.url,dataType:c.dataType,
data:c.data||"",timeout:15E3,success:function(b){a.dataOut={ret_status:!0,ret_value:b};d(a)},error:function(c,g,h){3>=++b?(console.log("try"+b+"/3 times"),setTimeout(e,100)):(a.dataOut={ret_status:!1,ret_value:null},d(a))}})};e()},RequestForBrowsers:function(a){"undefined"!=typeof PSBGWrapper.PrivacyScannerRequestForBrowsers&&PSBGWrapper.PrivacyScannerRequestForBrowsers(a)},init:function(){chrome.extension.onConnect.addListener(function(a){console.log(a.name);"LocalPage_Background"==a.name?null==
PSBackground.PageList[a.name].tabID?(PSBackground.PageList[a.name].tabID=a.sender.tab.id,PSBackground.PageList[a.name].port=a,a.onDisconnect.addListener(function(a){PSBackground.PageList[a.name].tabID=null}),a.onMessage.addListener(function(a){var c=a.data;console.log("strMsg="+c+"\n");var b=TMExt_$.parseJSON(c);if("update_ubm"==b.type)PSBackground.UpdateUBM();else if("open_help_page"==b.type)PSBackground.OpenHelpPage(b);else if("write_file_log"==b.type)"undefined"!=typeof PSBGWrapper.PrivacyScannerLog&&
PSBGWrapper.PrivacyScannerLog(b.dataIn.data);else if("privacy_scanner_setting"==b.type)PSBackground.PSSettingSyncUp(b);else if("data_collection"==b.type)PSBackground.PSCollectData(c);else if(b.isBrowser)PSBackground.RequestForBrowsers(c);else if("ajax_request"==b.type)PSBackground.DoAJAX(b);else if("login"==b.type)chrome.tabs.create({url:b.target_url,active:b.active},function(a){});else if(""!=b.target_url){PSBackground.PageList[b.destination]||(PSBackground.PageList[b.destination]={});!0==b.needForceNewTab&&
(PSBackground.PageList[b.destination].connected=!1);a=!1;PSBackground.PageList[b.destination].connected||(a=!0,chrome.tabs.create({url:b.target_url,active:b.active},function(a){PSBackground.PageList[b.destination].tabID=a.id}));var e=0,f=function(){e++;console.log("Try "+e+" times");if(PSBackground.PageList[b.destination].connected)PSBackground.SendMessageToContentPage(b.destination,c);else if(15>e)setTimeout(f,2E3);else{console.log(b.destination+"is not connected, return error:80000000");var a=TMExt_$.parseJSON(TMExt_$.toJSON(b));
a.type="error";a.dataOut={ret_status:!1,ret_value:"80000000"};a=TMExt_$.toJSON(a);PSBackground.SendMessageToLocalPage(a)}};a?setTimeout(f,2E3):f()}})):(chrome.tabs.remove(a.sender.tab.id,function(){}),chrome.tabs.update(PSBackground.PageList[a.name].tabID,{active:!0})):PSBackground.PageList[a.name]&&(PSBackground.PageList[a.name].connected=!0,PSBackground.PageList[a.name].port=a,a.onDisconnect.addListener(function(a){PSBackground.PageList[a.name].connected=!1}),a.onMessage.addListener(function(a){a=
a.data;console.log("strMsg="+a+"\n");var c=TMExt_$.parseJSON(a);"privacy_scanner_setting"==c.type?PSBackground.PSSettingSyncUp(c):"data_collection"==c.type?PSBackground.PSCollectData(a):PSBackground.SendMessageToLocalPage(a)}))})}};window.addEventListener("load",PSBackground.init,!1);
