(function(){var f=function(a,b,c){this.id=a;this.htmlContent=b;this.scanResultTemplate=c};f.prototype.getCurrentSetting_20=function(a,b){for(var c=0;c<b;c++)if("true"===a.find(".uiMenuInner li:eq("+c+") a").attr("aria-checked"))return c;return 3};f.prototype.generateUIResources_20=function(a,b){var c={};c.Title=a.find('div[class="mbm fwb"]').text();c.Desc=a.find('div[class="mbm fcg"]').text();if(void 0==c.Desc||null==c.Desc||""==c.Desc)c.Desc=c.Title;for(var w=a.find('ul[class="uiMenuInner"]'),w=
w.find(void 0==b||null==b?"li":"li:lt("+b+")"),d={},e=0;e<w.length;e++){var f=TMExt_$(TMExt_$(w[e]).find("a span")[0].childNodes[0]).text();d[e]=f}c.PossibleValue=d;return c};f.prototype.generateUIResources_31=function(){for(var a=this.htmlContent,b={},c=null,d=0;3>d;d++)1==a.jsmods.markup[d][2]?1==d?b[0]=a.jsmods.markup[d][1].__html.toString():2==d&&(b[1]=a.jsmods.markup[d][1].__html.toString()):7==a.jsmods.markup[d][2]&&(c=TMExt_$(a.jsmods.markup[d][1].__html));a={};a.Title=c.find('div[class="mbm fwb"]').text();
a.Desc=c.find('label[class="mvm"]').text();if(void 0==a.Desc||null==a.Desc||""==a.Desc)a.Desc=a.Title;a.PossibleValue=b;return a};var d=function(a,b,c){f.call(this,a,b,c)};d.prototype=new f;d.prototype.getNumberOfSettingItems=function(){for(var a=TMExt_$(this.htmlContent.jsmods.markup[0][1].__html).find('ul[class="uiMenuInner"]>li'),b=0,c=0;c<a.length;c++){if(a.eq(c).hasClass("uiMenuSeparator"))return b;b++}return null};d.prototype.getNumberOfSettingItems_83=function(){for(var a=this.htmlContent.find('ul[class="uiMenuInner"]>li'),
b=0,c=0;c<a.length;c++){if(a.eq(c).hasClass("uiMenuSeparator"))return b;b++}return null};var k=function(a,b,c){f.call(this,a,b,c)};k.prototype=new f;k.prototype.getNumberOfSettingItems=function(){var a=this.htmlContent.jsmods.instances,b=0;TMExt_$.each(a[a.length-1][2][0],function(a,d){if(d.ctor&&d.ctor.__m&&"PrivacySelectorOptionNew"==d.ctor.__m)return b++,!0;if(d.ctor&&d.ctor.__m&&"PrivacySelectorCustomOption"==d.ctor.__m)return b++,!1});return b};k.prototype.getResult=function(){try{var a=this.scanResultTemplate,
b=TMExt_$(this.htmlContent.jsmods.markup[0][1].__html);if(this.getNumberOfSettingItems()>a.ExpectedNumberOfPossibleValue)return null;var c=this.generateUIResources(b);TMExt_$.extend(a,c);var d=this.getSettings(this.htmlContent);TMExt_$.extend(a,d);return a}catch(e){return PSDebug.error(e),null}};k.prototype.generateUIResources=function(a){var b={};b.Title=a.find('div[class="mbm fwb"]').text();b.Desc=a.find('div[class="mbm fcg"]').text();if(void 0==b.Desc||null==b.Desc||""==b.Desc)b.Desc=b.Title;return b};
k.prototype.getSettings=function(a){var b={Current:null,PossibleValue:{}};a=a.jsmods.instances;var c=0;TMExt_$.each(a[a.length-1][2][0],function(a,d){if(d.ctor&&d.ctor.__m&&"PrivacySelectorOptionNew"==d.ctor.__m)return d.selected&&(b.Current=c),b.PossibleValue[c]=d.label,c++,!0;if(d.ctor&&d.ctor.__m&&"PrivacySelectorCustomOption"==d.ctor.__m)return b.PossibleValue[c]=d.label,c++,!1});null===b.Current&&(b.Current=this.DefaultSetting);return b};var e=function(a,b,c){f.call(this,a,b,c)};e.prototype=
new d;e.prototype.getResult=function(){try{var a=this.scanResultTemplate,b=TMExt_$(this.htmlContent.jsmods.markup[0][1].__html),c=this.getNumberOfSettingItems();if(c!=a.ExpectedNumberOfPossibleValue)return null;var d=this.generateUIResources_20(b,c);TMExt_$.extend(a,d);a.Current=this.getCurrentSetting_20(b,c);return a}catch(e){return PSDebug.error(e),null}};var g=function(a,b,c){f.call(this,a,b,c)};g.prototype=new k;g.prototype.DefaultSetting=3;var m=function(a,b,c){f.call(this,a,b,c)};m.prototype=
new d;m.prototype.getCurrentSetting=function(a,b){for(var c=0;c<b;c++)if("true"===a.find(".uiMenuInner li:eq("+c+") a").attr("aria-checked"))return c;return null};m.prototype.getResult=function(){try{var a=this.scanResultTemplate,b=TMExt_$(this.htmlContent.jsmods.markup[0][1].__html),c=this.getNumberOfSettingItems(b);if(c!=a.ExpectedNumberOfPossibleValue)return null;var d=this.generateUIResources_20(b,c);TMExt_$.extend(a,d);a.Current=this.getCurrentSetting(b,c);return a}catch(e){return PSDebug.error(e),
null}};var n=function(a,b,c){f.call(this,a,b,c)};n.prototype=new d;n.prototype.generateUIResources=function(a){var b={};b.Title=a.find('div[class="mbm fwb"]').text();b.Desc=a.find('label[class="mvm"]').text();if(void 0==b.Desc||null==b.Desc||""==b.Desc)b.Desc=b.Title;b.PossibleValue={0:null,1:null};return b};n.prototype.getCurrentSetting=function(a){return 0<a.find('input[name="search_filter_public"][checked]').length?1:0};n.prototype.getResult=function(){try{var a=this.scanResultTemplate,b=TMExt_$(this.htmlContent.jsmods.markup[0][1].__html),
c=this.generateUIResources(b);TMExt_$.extend(a,c);a.Current=this.getCurrentSetting(b);return a}catch(d){return PSDebug.error(d),null}};var l=function(a,b,c){f.call(this,a,b,c)};l.prototype=new d;l.prototype.getCurrentSetting=function(){for(var a=this.htmlContent,b=null,c=0;3>c;c++)if(7==a.jsmods.markup[c][2]){b=TMExt_$(a.jsmods.markup[c][1].__html);break}return"1"===b.find('input[name="tag_approval_enabled"]').attr("value")?0:1};l.prototype.getResult=function(){try{var a=this.scanResultTemplate,b=
this.generateUIResources_31();TMExt_$.extend(a,b);a.Current=this.getCurrentSetting();return a}catch(c){return PSDebug.error(c),null}};var h=function(a,b,c){f.call(this,a,b,c)};h.prototype=new d;h.prototype.getResult=function(){try{var a=this.scanResultTemplate,b=TMExt_$(this.htmlContent.jsmods.markup[0][1].__html),c=this.getNumberOfSettingItems(b);if(c!=a.ExpectedNumberOfPossibleValue)return null;var d=this.generateUIResources_20(b,c);TMExt_$.extend(a,d);a.Current=this.getCurrentSetting_20(b,c);return a}catch(e){return PSDebug.error(e),
null}};var x=function(a,b,c){f.call(this,a,b,c)};x.prototype=new d;x.prototype.getResult=function(){try{var a=this.scanResultTemplate,b=TMExt_$(this.htmlContent.jsmods.markup[0][1].__html),c=this.getNumberOfSettingItems(b);if(c!=a.ExpectedNumberOfPossibleValue)return null;var d=this.generateUIResources_20(b,c);TMExt_$.extend(a,d);a.Current=this.getCurrentSetting_20(b,c);return a}catch(e){return PSDebug.error(e),null}};var q=function(a,b,c){f.call(this,a,b,c)};q.prototype=new k;q.prototype.DefaultSetting=
5;var p=function(a,b,c){f.call(this,a,b,c)};p.prototype=new d;p.prototype.getCurrentSetting=function(){for(var a=this.htmlContent,b=null,c=0;3>c;c++)if(7==a.jsmods.markup[c][2]){b=TMExt_$(a.jsmods.markup[c][1].__html);break}return"1"===b.find('input[name="tag_review_enabled"]').attr("value")?0:1};p.prototype.getResult=function(){try{var a=this.scanResultTemplate,b=this.generateUIResources_31();TMExt_$.extend(a,b);a.Current=this.getCurrentSetting();return a}catch(c){return PSDebug.error(c),null}};
var r=function(a,b,c){f.call(this,a,b,c)};r.prototype=new d;r.prototype._getResult=function(a){var b=a.jsmods.markup;a=TMExt_$(b[0][1].__html);var c=b[1][1].__html,b=b[2][1].__html,d={};d.Title=a.find('div[class="mbm fwb"]').text();d.Desc=a.find('div[class="mbm fcg"]').contents().eq(0).text();d.PossibleValue={0:c,1:b};-1!=a.find('form a[role="button"] span').text().indexOf(c)?d.Current=0:d.Current=1;return d};r.prototype.getResult=function(){try{var a=this.scanResultTemplate,b=this._getResult(this.htmlContent);
TMExt_$.extend(a,b);return a}catch(c){return PSDebug.error(c),null}};var s=function(a,b,c){f.call(this,a,b,c)};s.prototype=new d;s.prototype.generateUIResources=function(){var a={};a.Title=TMExt_$(window.app_settings_title_array[1]).text();a.Desc=TMExt_$(window.app_settings_desc_array[1]).text();if(void 0==a.Desc||null==a.Desc||""==a.Desc)a.Desc=a.Title;a.PossibleValue={0:null,1:null};return a};s.prototype.getCurrentSetting=function(a){return 0<a.find("input[type=checkbox][checked]").length?1:0};
s.prototype.getResult=function(){try{var a=this.scanResultTemplate,b=TMExt_$(this.htmlContent.jsmods.markup[0][1].__html),c=this.generateUIResources(b);TMExt_$.extend(a,c);a.Current=this.getCurrentSetting(b);return a}catch(d){return PSDebug.error(d),null}};var t=function(a,b,c){f.call(this,a,b,c)};t.prototype=new d;t.prototype.generateUIResources=function(){var a={};a.Title=TMExt_$(window.app_settings_title_array[1]).text();a.Desc=TMExt_$(window.app_settings_desc_array[1]).text();if(void 0==a.Desc||
null==a.Desc||""==a.Desc)a.Desc=a.Title;a.PossibleValue={0:null,1:null};return a};t.prototype.getCurrentSetting=function(a){try{return 0>a[0].action.indexOf("opt_out=0")?1:0}catch(b){return PSDebug.error(b),0}};t.prototype.getResult=function(){try{var a=this.scanResultTemplate,b=TMExt_$(this.htmlContent.jsmods.markup[0][1].__html),c=this.generateUIResources();TMExt_$.extend(a,c);a.Current=this.getCurrentSetting(b);return a}catch(d){return PSDebug.error(d),null}};var u=function(a,b,c){f.call(this,
a,b,c)};u.prototype=new d;u.prototype.generateUIResources=function(a,b){var c={};c.Title=TMExt_$(window.app_settings_title_array[2]).text();c.Desc=TMExt_$(window.app_settings_desc_array[2]).text();if(void 0==c.Desc||null==c.Desc||""==c.Desc)c.Desc=c.Title;for(var d=a.find('ul[class="uiMenuInner"]'),d=d.find(void 0==b||null==b?"li":"li:lt("+b+")"),e={},f=0;f<d.length;f++){var k=TMExt_$(TMExt_$(d[f]).find("a span")[0].childNodes[0]).text();e[f]=k}c.PossibleValue=e;return c};u.prototype.getCurrentSetting=
function(a,b){for(var c=0;c<b;c++)if("true"===a.find(".uiMenuInner li:eq("+c+") a").attr("aria-checked"))return c;return 4};u.prototype.getResult=function(){try{var a=this.scanResultTemplate,b=this.htmlContent,c=this.getNumberOfSettingItems_83(b);if(c!=a.ExpectedNumberOfPossibleValue)return null;var d=this.generateUIResources(b,c);TMExt_$.extend(a,d);a.Current=this.getCurrentSetting(b,c);return a}catch(e){return PSDebug.error(e),null}};var y=function(a,b,c){f.call(this,a,b,c)};y.prototype=new k;y.prototype.DefaultSetting=
4;y.prototype.generateUIResources=function(a){var b={};b.Title=a.find('div[class="mvm mlm _cuf"]').text();b.Desc=a.find('div[class="mbm fcg"]').text();if(void 0==b.Desc||null==b.Desc||""==b.Desc)b.Desc=b.Title;return b};var v=function(a,b,c){f.call(this,a,b,c)};v.prototype=new d;v.prototype.generateUIResources=function(a){var b={},c={0:"Public",1:"Friends of Friends",2:"Friends",3:"Only Me",4:"Custom"};if("undefined"===typeof GetPSL10NString){if(b.Title=TMExt_$(window.application_3rd_title).text(),
b.Desc=a.find('div[class="_4n9s"]').text(),void 0==b.Desc||null==b.Desc||""==b.Desc)b.Desc=b.Title}else{b.Title=GetPSL10NString("fb_app_titleArea_title_wording_title");b.Desc=GetPSL10NString("fb_app_titleArea_title_wording_detail_tooltip");if(void 0==b.Desc||null==b.Desc||""==b.Desc)b.Desc=b.Title;c={0:GetPSL10NString("fb_app_level_public_wording"),1:GetPSL10NString("fb_app_level_FriendsOfFriends_wording"),2:GetPSL10NString("fb_app_level_friends_wording"),3:GetPSL10NString("fb_app_level_onlyme_wording")}}window.FacebookL10nWording&&
(c=window.FacebookL10nWording);b.PossibleValue=c;return b};v.prototype.getCurrentSetting=function(a){try{switch(Math.max.apply(null,a)){case 50:return 1;case 40:return 2;case 10:return 3}return 0}catch(b){return PSDebug.error(b),0}};v.prototype.getResult=function(){try{var a=this.scanResultTemplate,b=TMExt_$(this.htmlContent.domops[0][3].__html).hide();TMExt_$("._w9r").remove();TMExt_$("body").append(b);a.html=this.htmlContent.domops[0][3].__html;var c=this.htmlContent.resource_map,d=[],e;for(e in c){var f=
c[e];if(0<=f.type.indexOf("css")){d.push(f.src);var k=document.createElement("link");k.setAttribute("rel","stylesheet");k.setAttribute("type","text/css");k.setAttribute("href",f.src);document.getElementsByTagName("head")[0].appendChild(k)}}a.cssNeed=d;a.appIDs=[];a.appsDetail={};c=[];this.htmlContent.jsmods&&(c=this.htmlContent.jsmods.require);var q=b.find("._3fig"),d=[];for(e=0;e<c.length&&e!=q.length;e++){var g=TMExt_$(q[e]),n=g.find("._4n9w").text(),h;if(window.FacebookL10nWording)for(f=0;f<a.possibleFixValue.length;f++)if(0<=
n.indexOf(window.FacebookL10nWording[f])){h=f;break}if(!(0>a.Risk.indexOf(h))){var p=c[e][3][1];a.appsDetail[p]={};var l=a.appsDetail[p];l.imgPath=g.find("img._8r").attr("src");l.appName=g.find("._4n9u").text();l.appLevelWording=g.find("._4n9w").text();d.push(h);l.appLevelNum=h;a.appIDs.push(p)}}a.Current=Math.min.apply(null,d);isNaN(a.Current);var m=this.generateUIResources(b);TMExt_$.extend(a,m);PSDebug.log("facebook applications scan result :===================> ",a);return a}catch(r){return PSDebug.error(r),
null}};window.getResponseHandler=function(a,b,c){var d=function(a){try{return 0<TMExt_$(a.jsmods.markup[0][1].__html).find('ul[class="uiMenuInner"]').length?!0:!1}catch(b){return!0}};switch(String(a)){case "20":return d(b)?new e(a,b,c):new g(a,b,c);case "22":case "23":return d(b)?new m(a,b,c):new g(a,b,c);case "24":return new n(a,b,c);case "31":return new l(a,b,c);case "33":return d(b)?new h(a,b,c):new q(a,b,c);case "34":return d(b)?new x(a,b,c):new q(a,b,c);case "35":return new p(a,b,c);case "36":return new r(a,
b,c);case "81":return new s(a,b,c);case "82":return new t(a,b,c);case "83":return d(b)?new u(a,b,c):new y(a,b,c);case "84":return new v(a,b,c)}}})();
(function(){var f=function(){this.PROTOCOL_DOMAIN=PUtil.checkPage.IsFacebook()?window.location.protocol+"//"+window.location.host:"https://www.facebook.com";this.ScanResultsTemplate=FacebookScanResultsTemplate};f.prototype.logHeaderSendData="[Facebook Scan -> send data]";f.prototype.logHeaderHandleResponseData="[Facebook Scan -> handle response data]";f.prototype.getSendData_SettingPage=function(){var d={type:"GET",data:null,dataType:"html",url:null};d.url=this.PROTOCOL_DOMAIN;d.url+="/settings?tab=privacy";
(new SendDataLogger(this.logHeaderSendData+" : getSendData_SettingPage",d)).getLog();return d};f.prototype.handleResponse_SettingPage=function(d){(new ResponseHandlerLogger(this.logHeaderHandleResponseData+", ID : handleResponse_SettingPage",d)).getLog();try{var f={},e=this.getUserIDFromHtml(d);f.user_id=e;var g=this.getFb_dtsgfromHtml(d);f.fb_dtsg=g;return f}catch(m){return PSDebug.error(m),null}};f.prototype.getUserIDFromHtml=function(d){function f(){try{var e="",k=d.indexOf('"USER_ID');if(-1!=
k){var g=d.indexOf(":",k);-1!=g&&(e=d.substring(g+1,d.indexOf(",",g)),e=e.replace(/[\\, \"]/g,""))}return"0"==e||""==e?null:e}catch(h){return null}}function e(){try{var d=l.find("#pageNav li a.navLink img").attr("id").split("_");return null!=d&&d[3]?d[3]:null}catch(e){return null}}function g(){try{var d=l.find("#pageNav .tinyman a").attr("href");return d?d.substring(d.indexOf("id=")+3,d.indexOf("&")):null}catch(e){return null}}function m(){try{var e="",e=substringBetween('CurrentUserInitialData",[],{"USER_ID":"',
'"',d);return null==e||"0"==e?null:e}catch(f){return null}}function n(){try{var d=l.find("li.navItem:first a img").eq(0).attr("id");if(d){var e=d.split("_");return e[e.length-1]}return null}catch(f){return null}}var l=TMExt_$(d);try{var h=f();return h||(h=e())||(h=g())||(h=m())?h:(h=n())?h:null}catch(x){return null}};f.prototype.getFb_dtsgfromHtml=function(d){function f(){try{var e=d.match(/"token"\s*:\s*"[\w\d]+"/i)[0];return e?e.split('"')[3]:null}catch(k){return null}}function e(){try{var e="",
e=substringBetween('fb_dtsg\\" value=\\"',"\\",d);return null==e||"0"==e?null:e}catch(f){return null}}try{var g=f();return g?g:(g=e())?g:null}catch(m){return null}};f.prototype.getSendData=function(d,f){var e={type:"GET",data:null,dataType:"html",url:null};e.url=this.PROTOCOL_DOMAIN;switch(String(d)){case "20":e.url+="/ajax/settings/granular_privacy/composer.php";break;case "22":e.url+="/ajax/settings/granular_privacy/find_email.php";break;case "23":e.url+="/ajax/settings/granular_privacy/find_phone.php";
break;case "24":e.url+="/ajax/settings/granular_privacy/search.php";break;case "31":e.url+="/ajax/settings/timeline/review.php";break;case "33":e.url+="/ajax/settings/timeline/tagging.php";break;case "34":e.url+="/ajax/settings/timeline/others.php";break;case "35":e.url+="/ajax/settings/tagging/review.php";break;case "36":e.url+="/ajax/settings/tagging/suggestions.php";break;case "81":e.url+="/settings/applications/platform_friends_share";break;case "82":e.url+="/settings/applications/edit_personalization";
break;case "83":e.url+="/settings?tab=applications";break;case "84":e.url+="/settings/applications/fetch_apps?tab=all&container_id=u_0_9"}83!=d&&(e.url+="?__user="+f+"&__a=1");(new SendDataLogger(this.logHeaderSendData+" : "+d,e)).getLog();return e};f.prototype.handleResponse=function(d,f){(new ResponseHandlerLogger(this.logHeaderHandleResponseData+", ID : "+d,f)).getLog();var e;e=83==d||82==d?this.getHTMLContent_2(f):this.getHTMLContent(f);var g=this.getScanResultSampleByID(d);return(new getResponseHandler(d,
e,g)).getResult()};f.prototype.getAllvalidID=function(){for(var d=[],f=0;f<this.ScanResultsTemplate.length;f++)d.push(this.ScanResultsTemplate[f].ID);return d};f.prototype.isValidID=function(d){for(var f=this.getAllvalidID(),e=0;e<f.length;e++)if(d==f[e])return!0;return!1};f.prototype.getScanResultSampleByID=function(d){for(var f=0;f<this.ScanResultsTemplate.length;f++)if(this.ScanResultsTemplate[f].ID==d)return PUtil.cloneObj(this.ScanResultsTemplate[f])};f.prototype.getHTMLContent=function(d){return TMExt_$.parseJSON(d.substring(d.indexOf("{")))};
f.prototype.getHTMLContent_2=function(d){return TMExt_$(d.substring(d.indexOf("<",1)))};window.FacebookScannerHelper=f})();
(function(){var f=[{Website:"FACEBOOK",ID:20,Risk:[1],ExpectedNumberOfPossibleValue:4,possibleFixValue:[0,1,2],Suggestion:0,Category:"People_can_see_your_personal_info"},{Website:"FACEBOOK",ID:22,Risk:[0,1],ExpectedNumberOfPossibleValue:3,possibleFixValue:[0,1,2],Suggestion:2,Category:"Strangers_can_easily_track_you"},{Website:"FACEBOOK",ID:23,Risk:[0,1],ExpectedNumberOfPossibleValue:3,possibleFixValue:[0,1,2],Suggestion:2,Category:"Strangers_can_easily_track_you"},{Website:"FACEBOOK",ID:24,Risk:[1],
possibleFixValue:[0,1],Suggestion:0,Category:"Strangers_can_easily_track_you"},{Website:"FACEBOOK",ID:31,Risk:[1],possibleFixValue:[0,1],Suggestion:0,Category:"You_can_be_tagged_without_your_permission"},{Website:"FACEBOOK",ID:33,Risk:[0],ExpectedNumberOfPossibleValue:4,possibleFixValue:[0,1,2],Suggestion:1,Category:"People_can_see_your_personal_info"},{Website:"FACEBOOK",ID:34,Risk:[0],ExpectedNumberOfPossibleValue:4,possibleFixValue:[0,1,2],Suggestion:1,Category:"People_can_see_your_personal_info"},
{Website:"FACEBOOK",ID:35,Risk:[1],possibleFixValue:[0,1],Suggestion:0,Category:"People_can_see_your_personal_info"},{Website:"FACEBOOK",ID:36,Risk:[0],possibleFixValue:[0,1],Suggestion:1,Category:"You_can_be_tagged_without_your_permission"},{Website:"FACEBOOK",ID:81,Risk:[1],possibleFixValue:[0],Suggestion:0,Category:"People_outside_of_Facebook_can_see_your_info"},{Website:"FACEBOOK",ID:82,Risk:[1],possibleFixValue:[0,1],Suggestion:0,Category:"People_outside_of_Facebook_can_see_your_info"},{Website:"FACEBOOK",
ID:83,Risk:[0],ExpectedNumberOfPossibleValue:4,possibleFixValue:[0,1,2],Suggestion:1,Category:"People_can_see_your_personal_info"},{Website:"FACEBOOK",ID:84,Risk:[0],possibleFixValue:[0,1,2],Suggestion:1,html:"<div></div>",Category:"Application_can_access_your_personal_info"}],d=function(){this.ScanResultsTemplate=f};d.prototype=new FacebookScannerHelper;window.FacebookScannerHelper_Under18=d})();
