(function(){var h=function(){this.PROTOCOL_DOMAIN=PUtil.checkPage.IsFacebook()?window.location.protocol+"//"+window.location.host:"https://www.facebook.com";this.responseHeaderScanSingle=FPScanSingleResponse;this.responseHeaderScan=FPScanResponse;this.UserInfo={hasUserInfo:!1,userID:null,isUnder18:null}};h.prototype.getUserInfo=function(d,f,l,b){var c=this;SendWebRequest({type:"GET",data:null,dataType:"html",url:c.PROTOCOL_DOMAIN+"/settings?tab=privacy"},function(b){SendWebRequest({type:"GET",data:null,
dataType:"html",url:c.PROTOCOL_DOMAIN+"/settings?tab=applications"},function(e){var g=TMExt_$(e);e=g.find('span[class="_3aiv"]');var m=g.find('div[class="_4na2"]'),g=g.find('span[class="_57ne"]');window.app_settings_title_array=e;window.app_settings_desc_array=m;window.application_3rd_title=g;c.UserInfo.hasUserInfo=!0;return(e=(new FacebookScannerHelper).handleResponse_SettingPage(b))&&e.user_id?(c.UserInfo.userID=e.user_id,e=c.UserInfo,m=0<=b.indexOf("214189648617074")?!0:!1,e.isUnder18=m,c.UserInfo.isUnder18?
f():d()):l()})},b)};h.prototype.scanSingle=function(d,f){function l(b){b=(new APIResponseHelper(c.responseHeaderScanSingle,ReturnCodeEnum.NETWORK_ERROR.code,ReturnCodeEnum.NETWORK_ERROR.description)).getResponse();PSDebug.error(b);return f(b)}function b(){function b(e){var a=k.handleResponse(d,e);if(84==d)if(c.bSecondTime)PSDebug.log("Second time for applications");else{setTimeout(function(){c.bSecondTime=!0;c.sendWebRequestOKCallback(e)},5E3);return}83==d&&a&&a.PossibleValue&&a.PossibleValue["3"]&&
"undefined"==typeof window.FacebookL10nWording&&(window.FacebookL10nWording=a.PossibleValue);a&&""==TMExt_$.trim(a.Title)&&(a=null);if(!a)return a=(new APIResponseHelper(c.responseHeaderScanSingle,ReturnCodeEnum.WEBRESPONSE_PARSE_ERROR.code,ReturnCodeEnum.WEBRESPONSE_PARSE_ERROR.description,"Web content parse error! ID: "+d+", webData: "+e)).getResponse(),PSDebug.error(a),f(a);a=(new APIResponseHelper(c.responseHeaderScanSingle,ReturnCodeEnum.OK.code,ReturnCodeEnum.OK.description,{ID:a.ID,Risk:a.Risk,
Title:a.Title,Desc:a.Desc,PossibleValue:a.PossibleValue,possibleFixValue:a.possibleFixValue,Current:a.Current,Suggestion:a.Suggestion,Category:a.Category,Website:a.Website,html:a.html,appIDs:a.appIDs,appsDetail:a.appsDetail,cssNeed:a.cssNeed})).getResponse();PSDebug.log(a);return f(a)}if(!k.isValidID(d)){var g=(new APIResponseHelper(c.responseHeaderScanSingle,ReturnCodeEnum.INVALID_ID.code,ReturnCodeEnum.INVALID_ID.description,"wrong ID! : "+d+", availableIDS: "+k.getAllvalidID())).getResponse();
PSDebug.error(g);return f(g)}c.sendWebRequestOKCallback=b;SendWebRequest(k.getSendData(d,c.UserInfo.userID),b,l)}var c=this,k=null;if(c.UserInfo.hasUserInfo)return k=c.UserInfo.isUnder18?new FacebookScannerHelper_Under18:new FacebookScannerHelper,b();c.getUserInfo(function(){k=new FacebookScannerHelper;return b()},function(){k=new FacebookScannerHelper_Under18;return b()},function(){var b=(new APIResponseHelper(c.responseHeaderScanSingle,ReturnCodeEnum.NOT_LOGGED_IN.code,ReturnCodeEnum.NOT_LOGGED_IN.description)).getResponse();
PSDebug.error(b);return f(b)},l)};h.prototype.scan=function(d){function f(a){if(!g){if(a[b.responseHeaderScanSingle].ReturnCode==ReturnCodeEnum.OK.code)switch(a=a[b.responseHeaderScanSingle].Response,parseInt(a.ID)){case 20:case 22:case 23:case 24:c.PrivacySetting.Items.push(a);break;case 31:case 33:case 34:case 35:case 36:c.TimeLineAndTagging.Items.push(a);break;case 81:case 82:case 83:case 84:c.AppsAndWebsites.Items.push(a)}else if(a[b.responseHeaderScanSingle].ReturnCode==ReturnCodeEnum.WEBRESPONSE_PARSE_ERROR.code)h=
!0;else return a=(new APIResponseHelper(b.responseHeaderScan,a[b.responseHeaderScanSingle].ReturnCode,a[b.responseHeaderScanSingle].Description,a[b.responseHeaderScanSingle].Response)).getResponse(),PSDebug.error(a),g=!0,d(a);e++;if(e==k)return a=h?(new APIResponseHelper(b.responseHeaderScan,ReturnCodeEnum.WEBRESPONSE_PARSE_ERROR_COULD_USE_PARTLY.code,ReturnCodeEnum.WEBRESPONSE_PARSE_ERROR_COULD_USE_PARTLY.description,c)).getResponse():(new APIResponseHelper(b.responseHeaderScan,ReturnCodeEnum.OK.code,
ReturnCodeEnum.OK.description,c)).getResponse(),PSDebug.log(a),d(a)}}function l(){for(var a=0;a<k;a++)b.scanSingle(FacebookScanResultsTemplate[a].ID,f);PSDebug.log("do scan finish")}var b=this,c={TimeLineAndTagging:{ID:3,Items:[]},PrivacySetting:{ID:2,Items:[]},AppsAndWebsites:{ID:8,Items:[]}},k=FacebookScanResultsTemplate.length,e=0,g=!1,h=!1;b.getUserInfo(function(){return l()},function(){return l()},function(){var a=(new APIResponseHelper(b.responseHeaderScan,ReturnCodeEnum.NOT_LOGGED_IN.code,
ReturnCodeEnum.NOT_LOGGED_IN.description)).getResponse();PSDebug.error(a);return d(a)},function(a){a=(new APIResponseHelper(b.responseHeaderScan,ReturnCodeEnum.NETWORK_ERROR.code,ReturnCodeEnum.NETWORK_ERROR.description)).getResponse();PSDebug.error(a);return d(a)})};h.prototype.Website="FACEBOOK";window.FacebookPScanner=h;window.PSScan={scanSingle:function(d,f){(new h).scanSingle(d,function(d){return f(d.FPScanSingleResponse.Response)})},scan:function(d){(new h).scan(function(f){return d(f.FPScanResponse.Response)})}}})();
