function filterbyHref(a){for(var b="^https?://\\w+.myspace.com ^javascript ^# ^/ ^https?://myspace.com ^https?://myspace.videosurf.com ^mailto ^https?://twitter.com ^https?://eventful\\.com/".split(" "),c=0;c<b.length;c++)if(ptn=new RegExp(b[c],"i"),ptn.test(a))return!0;return!1}
function TBParseHome(a){var b=new CreateTSRLocatedObject(null,null,"A",null);if(a=(new CreateTSRLocatedObject(a,b,"SECTION","row1")).findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=a[b].href;filterbyHref(c)||CreateTSRResultObject(a[b],c)}}
function TBParsePhoto(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"SECTION","container");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=b[a].href;filterbyHref(c)||CreateTSRResultObject(b[a],c)}}
function TBParseBulletins(a){var b=new CreateTSRLocatedObject(null,null,"A",null);if(a=(new CreateTSRLocatedObject(a,b,"SECTION","row0")).findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=a[b].href;filterbyHref(c)||CreateTSRResultObject(a[b],c)}}
function TBParseProfile(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"SECTION","col1_0");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=b[a].href;filterbyHref(c)||CreateTSRResultObject(b[a],c)}}
function TBParseOther(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"SECTION","row2");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=b[a].href;filterbyHref(c)||CreateTSRResultObject(b[a],c)}}
function adjustStyleOfFindTickets(a){var b=a&&a.id;b&&/link_findticket_.*/.test(b)&&(b=a.previousSibling,a.style.marginLeft="18px",b.style.position="relative",(new TMDOMObj(b)).style.setFloat("left"),b.style.top="3px",b.style.height=b.style.width="0px",b.firstChild.style.position="absolute")}
function TBParseEvent(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV","page");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=b[a].href;filterbyHref(c)||CreateTSRResultObject(b[a],c)}}
function TBParseThread(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV","groups_app");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=b[a].href;filterbyHref(c)||CreateTSRResultObject(b[a],c)}}
function TBParseLatestPost(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);a.appendAttribute("class","horizontalContent");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=a[b].href;filterbyHref(c)||CreateTSRResultObject(a[b],c)}}
function TBParseComment(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);a.appendAttribute("class","commentBody");b.multiMatches=!0;a.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=b[a].href;filterbyHref(c)||CreateTSRResultObject(b[a],c)}}
function AdjustNodeStyle(a){if(a){var b=a.previousSibling||null;b&&"TSRSpan"==b.className&&(b.style.width=g_oImgDefine.ImgSize.WarningIcon.width+"px",b.style.height=g_oImgDefine.ImgSize.WarningIcon.height+"px");adjustStyleOfFindTickets(a)}}g_bIsNeedCheckSPan=!0;TSRTagFlowID();
function TSRParse(){var a=g_oEnv.Parser.iResultNumber;TBParseHome(document);TBParseBulletins(document);TBParseProfile(document);TBParseOther(document);TBParseEvent(document);TBParseThread(document);TBParseLatestPost(document);TBParseComment(document);TBParsePhoto(document);TrendMicro.TB.ReduceNewNode(a+1);for(a=1;a<g_oEnv.Parser.rgobjSearchResult.length;a++)g_oEnv.Parser.rgobjSearchResult[a]&&AdjustNodeStyle(g_oEnv.Parser.rgobjSearchResult[a]);return g_oEnv.Parser.rgobjSearchResult};
