function GetRealURL(a){var b=a.match(/^https?:\/\/(.*)\.facebook\.com\/l\.php\?u=(.*)&h=/i);return b?decodeURIComponent(b[2]):a}function filterbyHref(a){for(var b="^#$ ^/ ^mailto ^https?\\:\\/\\/.*\\.fbcdn\\.net ^https?\\:\\/\\/.*\\.facebook\\.com ^https?\\:\\/\\/facebook\\.interviewstreet\\.com".split(" "),c=0;c<b.length;c++)if(ptn=new RegExp(b[c],"i"),ptn.test(a))return!0;return!1}function filterByNode(a){return a&&"undefined"!=typeof a.innerHTML&&""==a.innerHTML?!0:!1}
function TBParseMessagesContent(a){var b=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,b,"DIV",null),d=new CreateTSRLocatedObject(null,c,"DIV",null),e=new CreateTSRLocatedObject(null,d,"DIV",null);a=new CreateTSRLocatedObject(a,e,"DIV","gb_content_and_toolbar");c.appendAttribute("class","GBThreadMessageRow_Body");e.appendAttribute("class","message_pane");d.appendAttribute("class","GBThreadMessageRow clearfix");d.multiMatches=!0;c.multiMatches=!0;b.multiMatches=!0;
if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),c=0;c<b.length;c++)d=GetRealURL(b[c].href),filterbyHref(d)||filterByNode(b[c])||CreateTSRResultObject(b[c],d)}function TBParseEvent(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV","event_info_pagelet");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=GetRealURL(b[a].href);filterbyHref(c)||filterByNode(b[a])||CreateTSRResultObject(b[a],c)}}
function TBParseWall(a){var b=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,b,"DIV",null),d=new CreateTSRLocatedObject(null,c,"LI",null);a=new CreateTSRLocatedObject(a,d,"UL","profile_minifeed");d.multiMatches=!0;c.appendAttribute("class","^storyInnerContent");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),c=0;c<b.length;c++)d=GetRealURL(b[c].href),filterbyHref(d)||filterByNode(b[c])||CreateTSRResultObject(b[c],d)}
function TBParseNewsFeed(a){var b=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,b,"DIV",null),d=new CreateTSRLocatedObject(null,c,"LI",null);a=new CreateTSRLocatedObject(a,d,"DIV","home_stream");d.multiMatches=!0;c.appendAttribute("class","^storyInnerContent");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),c=0;c<b.length;c++)d=GetRealURL(b[c].href),filterbyHref(d)||filterByNode(b[c])||CreateTSRResultObject(b[c],d)}
function TBParseNotes(a){if(!a.getElementById("pagelet_roosters")){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV","contentArea");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=GetRealURL(b[a].href);filterbyHref(c)||filterByNode(b[a])||CreateTSRResultObject(b[a],c)}}}
function TBParsePhoto(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV","photos_snowlift");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=GetRealURL(b[a].href);filterbyHref(c)||filterByNode(b[a])||CreateTSRResultObject(b[a],c)}}
function TBParsePhotoFromHome(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV","content");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=GetRealURL(b[a].href);filterbyHref(c)||filterByNode(b[a])||CreateTSRResultObject(b[a],c)}}
function TBParsePhotoShowBox(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV","fbxPhotoContentContainer");b.multiMatches=!0;if(b=a.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=GetRealURL(b[a].href);filterbyHref(c)||filterByNode(b[a])||CreateTSRResultObject(b[a],c)}}function TBAdjustAdinfoStyle(a){a.style.display="inline"}
function GetAdUrl(a){var b=a.match(/^https?:\/\/(.*)\.facebook\.com\/a\.php\?u=(.*)&__tn__/);return b&&2<b.length?decodeURIComponent(b[2]):a}
function TBParseAds(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"DIV",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);a.multiMatches=!0;a.appendAttribute("class","^ego_column");b.multiMatches=!0;b.appendAttribute("class","^ego_unit");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=a[b].getElementsByTagName("strong");if(0<c.length){var d=GetAdUrl(a[b].href);CreateTSRResultObject(c[0],d)}}}
function AdjustNodeStyle(a){a&&(a=a.previousSibling||null)&&"TSRSpan"==a.className&&(a=a.childNodes[0])&&"TSRWebRatingIcon"==a.className&&(a.style.margin="0px",a.style.padding="0px",a.style.border="0px")}
function TBParseSiderUIStream(a){var b=new CreateTSRLocatedObject(null,null,"A",null),b=new CreateTSRLocatedObject(null,b,"H6",null),c=new CreateTSRLocatedObject(null,b,"DIV",null);a=new CreateTSRLocatedObject(a,c,"DIV",null);a.appendAttribute("class","^ego_column");c.multiMatches=!0;c.appendAttribute("class","^fbAdUnit");b.multiMatches=!0;b.appendAttribute("class","uiStreamMessage");if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)c=GetRealURL(a[b].href),filterbyHref(c)||filterByNode(a[b])||
CreateTSRResultObject(a[b],c)}function TBParseAnswerText(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"DIV",null);a.appendAttribute("class","answerText");a.multiMatches=!0;if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=GetRealURL(a[b].href);filterbyHref(c)||filterByNode(a[b])||CreateTSRResultObject(a[b],c)}}
function TBParseCommentBody(a){var b=new CreateTSRLocatedObject(null,null,"A",null);a=new CreateTSRLocatedObject(a,b,"SPAN",null);a.appendAttribute("class","commentBody");a.multiMatches=!0;if(a=a.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++){var c=GetRealURL(a[b].href);filterbyHref(c)||filterByNode(a[b])||CreateTSRResultObject(a[b],c)}}TSRTagFlowID();g_bIsNeedCheckSPan=!0;
function TSRParse(){var a=g_oEnv.Parser.iResultNumber;TrendMicro.TB.DOMIdExist("gb_content_and_toolbar")&&TBParseMessagesContent(document);TrendMicro.TB.DOMIdExist("profile_minifeed")&&TBParseWall(document);TrendMicro.TB.DOMIdExist("home_stream")&&TBParseNewsFeed(document);TrendMicro.TB.DOMIdExist("event_info_pagelet")&&TBParseEvent(document);TBParseNotes(document);TrendMicro.TB.DOMIdExist("photos_snowlift")&&TBParsePhoto(document);TrendMicro.TB.DOMIdExist("content")&&TBParsePhotoFromHome(document);
TrendMicro.TB.DOMIdExist("fbxPhotoContentContainer")&&TBParsePhotoShowBox(document);TBParseSiderUIStream(document);TBParseAnswerText(document);TBParseCommentBody(document);TBParseAds(document);TrendMicro.TB.ReduceNewNode(a+1);return g_oEnv.Parser.rgobjSearchResult};
