function TSSRYahooFetchTargetURL(b){var a=b.match(/\/EXP=\d+\/[*\-]{2}(.+)$/);return a&&2==a.length?a[1]:b}
function TSSRYahooParseResult(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(b,a,"H3",null),a=new CreateTSRLocatedObject(b,a,"DIV",null);b=new CreateTSRLocatedObject(b,a,"DIV","WS2m");a.appendAttribute("class","^hd");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=TSSRYahooFetchTargetURL(b[a].href);CreateTSRResultObject(b[a],c)}}
function TSSRYahooParseResultFirefox7(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"LI",null),c=new CreateTSRLocatedObject(null,a,"OL",null);b=new CreateTSRLocatedObject(b,c,"DIV","web");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)CreateTSRResultObject(b[a],b[a].href)}
function TSSRYahooParseSidebarSponsor(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"DIV",null);new CreateTSRLocatedObject(b,a,"DIV","so3");b=new CreateTSRLocatedObject(b,a,"DIV","sIn");a.appendAttribute("class","^bd");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)CreateTSRResultObject(b[a],b[a].href)}
function TSSRYahooParseSidebarSponsorFirefox7(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"LI",null),c=new CreateTSRLocatedObject(null,a,"UL",null);b=new CreateTSRLocatedObject(b,c,"DIV","posE");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)CreateTSRResultObject(b[a],b[a].href)}
function TSRYahooModifyCSS(b){var a=b.FindInsertNode();a&&a.style&&(b.spanIcon=document.createElement("SPAN"),(new TMDOMObj(b.spanIcon)).style.setFloat("left"))}
function TSSRYahooParseTopSponsor(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"DIV",null);new CreateTSRLocatedObject(b,a,"DIV","so1");b=new CreateTSRLocatedObject(b,a,"DIV","So1");a.appendAttribute("class","^bd");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){var c=CreateTSRResultObject(b[a],b[a].href);TSRYahooModifyCSS(c)}}
function TSSRYahooParseBottonSponsor(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"DIV",null);new CreateTSRLocatedObject(b,a,"DIV","so2");b=new CreateTSRLocatedObject(b,a,"DIV","So2");a.appendAttribute("class","^bd");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)CreateTSRResultObject(b[a],b[a].href)}
function TSSRYahooParseNewsResult(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"ul",null),a=new CreateTSRLocatedObject(null,a,"td",null);b=new CreateTSRLocatedObject(b,a,"li",null);b.multiMatches=!0;b.appendAttribute("data-bns","Yahoo");a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++){for(var c=TSSRYahooFetchTargetURL(b[a].href),e=!1,d=0;d<YahooEnPtn.length;d++)if(ptn=new RegExp(YahooEnPtn[d],"i"),ptn.test(c)){e=
!0;break}e||(CreateTSRResultObject(b[a],c,TSSRYahooFindInsertNode).baseNode=b[a].parentNode.parentNode.parentNode)}}
function TSSRYahooParseNewsSearchResult(b){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"H2",null),c=new CreateTSRLocatedObject(b,a,"DIV","NSm");a.multiMatches=!0;if(a=c.findElement())for(a=GetAllTSRLocatedNodes(a),c=0;c<a.length;c++)CreateTSRResultObject(a[c],a[c].href);a=new CreateTSRLocatedObject(null,null,"A",null);b=new CreateTSRLocatedObject(b,a,"DIV","NSt2");a.multiMatches=!0;if(a=b.findElement())for(a=GetAllTSRLocatedNodes(a),c=0;c<a.length;c++)CreateTSRResultObject(a[c],
a[c].href)}g_bIsNeedCheckSPan=!0;TSRTagFlowID();
function TSRParse(){if(/realtime\.search\.yahoo\./.test(document.location))return[];var b=g_oEnv.Parser.iResultNumber;TSSRYahooParseResult(document);TrendMicro.TB.DOMIdExist("web")&&TSSRYahooParseResultFirefox7(document);TSSRYahooParseSidebarSponsor(document);TrendMicro.TB.DOMIdExist("posE")&&TSSRYahooParseSidebarSponsorFirefox7(document);TSSRYahooParseTopSponsor(document);TSSRYahooParseBottonSponsor(document);TSSRYahooParseNewsResult(document);TSSRYahooParseNewsSearchResult(document);TrendMicro.TB.ReduceNewNode(b+
1);return g_oEnv.Parser.rgobjSearchResult};
