function filterbyHref(b){for(var a=["http://(e|trust|guanwang|open|cache|newscache)\\.baidu\\.com","http://(www|news)\\.baidu\\.com/(.*)((wd=)|(word=))","http://tag\\.news\\.baidu\\.com/t","http://cache\\.baiducontent\\.com"],c=0;c<a.length;c++)if(ptn=new RegExp(a[c],"i"),ptn.test(b))return!0;return!1}
function TSSRBaiduParseResult(b){if(TrendMicro.TB.DOMIdExist("container")){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"H3",null),a=new CreateTSRLocatedObject(null,a,"DIV",null);b=new CreateTSRLocatedObject(b,a,"DIV","content_left");a.multiMatches=!0;a.appendAttribute("class","result");if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)filterbyHref(b[a].href)||CreateTSRResultObject(b[a],b[a].href)}}
function TSSRBaiduParseResultTopFirst(b){if(TrendMicro.TB.DOMIdExist("container")){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"H2",null),a=new CreateTSRLocatedObject(null,a,"DIV",null);b=new CreateTSRLocatedObject(b,a,"DIV","content_left");a.multiMatches=!0;a.appendAttribute("class","layout");if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)filterbyHref(b[a].href)||CreateTSRResultObject(b[a],b[a].href)}}
function TSSRBaiduParseResult_News(b){if(TrendMicro.TB.DOMIdExist("container")){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"FONT",null),c=new CreateTSRLocatedObject(null,a,"TABLE",null);b=new CreateTSRLocatedObject(b,c,"DIV","container");c.multiMatches=!0;a.multiMatches=!0;a.appendAttribute("size","-1");if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)filterbyHref(b[a].href)||1!=(b[a].innerText||b[a].textContent||"").length&&CreateTSRResultObject(b[a],
b[a].href)}}
function TSSRBaiduParseResult_FromBing(b){if(TrendMicro.TB.DOMIdExist("container")){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"DIV",null),c=new CreateTSRLocatedObject(null,a,"TABLE",null);b=new CreateTSRLocatedObject(b,c,"DIV","container");c.multiMatches=!0;a.multiMatches=!0;a.appendAttribute("class","bingres");if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)filterbyHref(b[a].href)||CreateTSRResultObject(b[a],b[a].href)}}
function TSSRBaiduParseSidebarSponsor(b){if(TrendMicro.TB.DOMIdExist("container")){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"TD",null);b=new CreateTSRLocatedObject(b,a,"DIV","container");a.appendAttribute("align","left");if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)filterbyHref(b[a].href)||CreateTSRResultObject(b[a],b[a].href)}}
function TSSRBaiduParseTopSponsor(b){if(TrendMicro.TB.DOMIdExist("content_left")){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"H3",null),a=new CreateTSRLocatedObject(null,a,"DIV",null);b=new CreateTSRLocatedObject(b,a,"DIV","content_left");a.multiMatches=!0;a.appendAttribute("data-click",".*");if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)filterbyHref(b[a].href)||CreateTSRResultObject(b[a],b[a].href)}}
function TSSRBaiduParseBottomSponsor(b){if(TrendMicro.TB.DOMIdExist("content_left")){var a=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,a,"TABLE",null);b=new CreateTSRLocatedObject(b,c,"DIV","content_left");c.multiMatches=!0;a.multiMatches=!0;a.appendAttribute("data-is-main-url","true");if(a=b.findElement())for(a=GetAllTSRLocatedNodes(a),c=0;c<a.length;c++)filterbyHref(a[c].href)||CreateTSRResultObject(a[c],a[c].href)}}
function TSSRBaiduParseNews(b){if(TrendMicro.TB.DOMIdExist("container")){var a=new CreateTSRLocatedObject(null,null,"A",null),a=new CreateTSRLocatedObject(null,a,"LI",null),c=new CreateTSRLocatedObject(null,a,"UL",null);b=new CreateTSRLocatedObject(b,c,"DIV","container");c.multiMatches=!0;a.multiMatches=!0;if(b=b.findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)filterbyHref(b[a].href)||CreateTSRResultObject(b[a],b[a].href)}}
function TSSRBaiduParseNews_SideSponsor(b){if(TrendMicro.TB.DOMIdExist("ecad")){var a=new CreateTSRLocatedObject(null,null,"A",null);if(b=(new CreateTSRLocatedObject(b,a,"DIV","ecad")).findElement())for(b=GetAllTSRLocatedNodes(b),a=0;a<b.length;a++)filterbyHref(b[a].href)||CreateTSRResultObject(b[a],b[a].href)}}
function TSSRBaiduParseTable(b){if(TrendMicro.TB.DOMIdExist("container")){var a=new CreateTSRLocatedObject(null,null,"A",null),c=new CreateTSRLocatedObject(null,a,"H3",null),c=new CreateTSRLocatedObject(null,c,"TABLE",null);b=new CreateTSRLocatedObject(b,c,"DIV","content_left");c.multiMatches=!0;a.appendAttribute("data-click",".*");if(a=b.findElement())for(a=GetAllTSRLocatedNodes(a),b=0;b<a.length;b++)filterbyHref(a[b].href)||CreateTSRResultObject(a[b],a[b].href)}}g_bIsNeedCheckSPan=!0;TSRTagFlowID();
function TSRParse(){var b=g_oEnv.Parser.iResultNumber;try{TSSRBaiduParseResult(document),TSSRBaiduParseResultTopFirst(document),TSSRBaiduParseResult_News(document),TSSRBaiduParseResult_FromBing(document),TSSRBaiduParseSidebarSponsor(document),TSSRBaiduParseTopSponsor(document),TSSRBaiduParseBottomSponsor(document),TSSRBaiduParseNews(document),TSSRBaiduParseNews_SideSponsor(document),TSSRBaiduParseTable(document)}catch(a){}TrendMicro.TB.ReduceNewNode(b+1);return g_oEnv.Parser.rgobjSearchResult};
