(function(){function l(){e.init();f.UMSCreateTooltip();TMExt_$("a").each(function(){TMExt_$(this)[0].UMSMouseEnterEventHandler&&!0===TMExt_$(this)[0].UMSMouseEnterEventHandler||(TMExt_$(this)[0].UMSMouseEnterEventHandler=!0,TMExt_$(this).mouseenter(function(a){try{var b=TMExt_$(this);if(!d.isRated(b)){var c=null;try{c=decodeURI(b[0].href||"")}catch(h){try{c=encodeURI(b[0].href||"")}catch(k){try{c=b[0].href}catch(l){c=null}}}c?(TMExt_debug("mouseenter href="+c),c=f.TSTrim(c),d.isValidUrl(c)?(d.setCurrentTarget(b),
d.setDocument(document),d.setCurrentNode(c),d.gMouseLeaveFlag=1,d.gOnRatingTimer=setTimeout(function(){TMExt_debug("timeout start rating");d.gOnRatingTimer=0;d.gCurrentEvent=b[0];e.call(c)},f.g_iUMSToolTipTimeout&&0<f.g_iUMSToolTipTimeout?f.g_iUMSToolTipTimeout:2E3),TMExt_$(this)[0].UMSMouseLeaveEventHandler&&!0===TMExt_$(this)[0].UMSMouseLeaveEventHandler||(TMExt_$(this)[0].UMSMouseLeaveEventHandler=!0,TMExt_$(this).mouseleave(function(a){d.gOnRatingTimer?(TMExt_debug("clear rating time out"),clearTimeout(d.gOnRatingTimer),
d.gOnRatingTimer=0):(f.UMSSetToolTipHideTimer(),d.gMouseLeaveFlag=0,d.setCurrentNode(null))}))):(TMExt_debug("just return: href is invalid:"+c),d.setCurrentNode(null))):TMExt_debug("just return: href is null")}}catch(g){g.number&&g.description?(a="catch err:[\n"+("Facility Code: "+(g.number>>16&8191)+"\n"),a+="Number: "+(g.number&65535)+"\n",a+="Description: "+g.description+"\n",TMExt_debug(a)):TMExt_debug(g)}}))})}function h(){try{l(),0==d.gMouseLeaveFlag&&f.UMSSetToolTipHideTimer()}catch(a){if(a.number&&
a.description){var b;b="catch err:[\n"+("Facility Code: "+(a.number>>16&8191)+"\n");b+="Number: "+(a.number&65535)+"\n";b+="Description: "+a.description+"\n";TMExt_debug(b)}else TMExt_debug(a)}}var f=window,d={gOnRatingTimer:null,gMouseLeaveFlag:1,gCurrentEvent:null,gCurrentTarget:null,gCurrentNode:null,gUrlMap:[],gDoc:null,gToolTip:null,gLinkNum:-1,gLastLink:null,gIntervalThread:null,gTooltipTimeout:0,gDocGuid:null,getCurrentTarget:function(){return this.gCurrentTarget},setCurrentTarget:function(a){this.gCurrentTarget=
a},isEditable:function(){var a=TMExt_$("body").attr("contenteditable"),a="on"===document.designMode||""===a||"true"===a,b=0<TMExt_$("body#punymce").length,c=0<TMExt_$("body#tinymce").length;return a||b&&!0===b||c&&!0===c},getCurrentNode:function(){return this.gCurrentNode},setCurrentNode:function(a){this.gCurrentNode=a},getUrlMapLenth:function(){return this.gUrlMap.length},getUrlMapValueByKey:function(a){return this.gUrlMap[a]},getUrlMapValueByIndex:function(a){return this.gUrlMap[a]},setUrlMapValue:function(a,
b){this.gUrlMap[a]=b},pushUrlMapValue:function(a){this.gUrlMap.push(a)},getDocument:function(){return this.gDoc},setDocument:function(a){this.gDoc=a},getToolTip:function(){return this.gToolTip},setToolTip:function(a){this.gToolTip=a},canHookLink:function(a,b){if(a===this.gLinkNum&&b===this.gLastLink)return!1;this.gLinkNum=a;this.gLastLink=b;return!0},callbackFromDoc:function(a,b){this.isEditable()||f.UMSInsertResultICON(this,a,b)},isValidUrl:function(a){a=encodeURI(a);return a.match(/^(https?|ftps?):\/\/([\w%\-]+\.)+[\w%\-]+(\/[\w\- .\/?%&=]*)?/i)?
!0:(TMExt_debug(a+" is invalid url"),!1)},isUrlRated:function(a){for(var b=0;b<this.getUrlMapLenth();++b)if(a==this.getUrlMapValueByIndex(b))return!0;TMExt_debug(a+" has not be rated.");this.pushUrlMapValue(a);return!1},getLocalUrlRule:function(){for(var a="^https?://(.*)",b=document.location.hostname.split("."),c=5>b.length?2===b.length?2:b.length-1:3;0<c;--c)a+="\\."+b[b.length-c];return a},isRated:function(a){var b=!1;if("TSRSpan"===a.prev().attr("class")||"TSRSpan"===a.parent().prev().attr("class"))b=
!0;if(!0!==b){a=a.children();for(var c=0;c<a.length;++c)if("TSRSpan"===TMExt_$(a[c]).attr("class")){b=!0;break}}!0===b&&TMExt_debug("It is a Rated link");return b}};f.g_manual_rating=d;var e={UMS_SEND_DATA_EVENT:"UMSSendDataEvent",UMS_EVENT_ID:"UMSSendDataEventElement",UMS_TAG_NAME:"UMSDataElement",UMS_IEObject:null,D_TOOLBAR_CALLBACK_ACTIVEX_PROG_ID:"ProToolbarIMRatingActiveX.ToolbarCB",init:function(){e.createElement()},createElement:function(){if(TrendMicro.TB.IsIE()){if(!e.UMS_IEObject){var a=
TrendMicro.TB.GetIEObject(!0);a||(a=TrendMicro.TB.GetIEObject(!1));a&&(e.UMS_IEObject=a||null)}}else{if(document.getElementById(e.UMS_EVENT_ID))return document.getElementById(e.UMS_EVENT_ID);a=document.createElement(e.UMS_TAG_NAME);a.setAttribute("id",e.UMS_EVENT_ID);document.documentElement.appendChild(a);return a}},call:function(a){var b=e.createElement();b?(b.setAttribute("data",a),b.setAttribute("docguid",d.gDocGuid),a=document.createEvent("Event"),a.initEvent(e.UMS_SEND_DATA_EVENT,!0,!1),b.dispatchEvent(a)):
(TMExt_debug("start ToolbarInvoke url="+a),e.UMS_IEObject.ToolbarInvoke({Action:5,URL:a,HTMLDocument:document}))}};f.Communicator=e;f.tmb_onRatingSingleURL=function(a,b,c,e){TMExt_debug("tmb_onRatingSingleURL url="+b+"ret=[ "+c+" ]");d.callbackFromDoc(c,b)};var k=function(){d.isEditable()||(TMExt_debug("manual rating document.ready TMExt_UMS_Start"),h(),setInterval(h,2E3))};f.UMSOnDocumentReady=k;try{TMExt_$(document).ready(function(){k()})}catch(m){"undefined"!=typeof console&&"undefined"!=typeof console.log&&
console.log("TMExt_$(document) in TISProUrlManualScannerLib.js Error"+m)}})();
