var g_oImgDefine={Nolink:{Tail:{TopRight:"red_bottom_left.png",TopLeft:"red_bottom_right.png",BottomRight:"red_top_left.png",BottomLeft:"red_top_right.png"},Content:{Icon:"icon_nolink.png",TextColor:"#333",SiteUrlColor:"#999",LevelString:g_oRatingLevelToolTipString.LevelString.Nolink,HelpString:g_oRatingLevelToolTipString.HelpString.Nolink},WebIcon:"webicon_nolink.png",Highlight:"#BDBDBD"},Safe:{Tail:{TopRight:"red_bottom_left.png",TopLeft:"red_bottom_right.png",BottomRight:"red_top_left.png",BottomLeft:"red_top_right.png"},
Content:{Icon:"icon_green.png",TextColor:"#333",SiteUrlColor:"#999",LevelString:g_oRatingLevelToolTipString.LevelString.Safe,HelpString:g_oRatingLevelToolTipString.HelpString.Safe},WebIcon:"webicon_green.png",Highlight:"#b8eab8"},Neutral:{Tail:{TopRight:"red_bottom_left.png",TopLeft:"red_bottom_right.png",BottomRight:"red_top_left.png",BottomLeft:"red_top_right.png"},Content:{Icon:"icon_green.png",TextColor:"#333",SiteUrlColor:"#999",LevelString:g_oRatingLevelToolTipString.LevelString.Neutral,HelpString:g_oRatingLevelToolTipString.HelpString.Neutral},
WebIcon:"webicon_green.png",Highlight:"#b8eab8"},Dangerous:{Tail:{TopRight:"red_bottom_left.png",TopLeft:"red_bottom_right.png",BottomRight:"red_top_left.png",BottomLeft:"red_top_right.png"},Content:{Icon:"icon_red.png",TextColor:"#333",SiteUrlColor:"#ed1c24",LevelString:g_oRatingLevelToolTipString.LevelString.Dangerous,HelpString:g_oRatingLevelToolTipString.HelpString.Dangerous},WebIcon:"webicon_red.png",Highlight:"#FA8F8F"},Suspicious:{Tail:{TopRight:"red_bottom_left.png",TopLeft:"red_bottom_right.png",
BottomRight:"red_top_left.png",BottomLeft:"red_top_right.png"},Content:{Icon:"icon_yellow.png",TextColor:"#333",SiteUrlColor:"#999",LevelString:g_oRatingLevelToolTipString.LevelString.Suspicious,HelpString:g_oRatingLevelToolTipString.HelpString.Suspicious},WebIcon:"webicon_yellow.png",Highlight:"#FCC465"},Untested:{Tail:{TopRight:"red_bottom_left.png",TopLeft:"red_bottom_right.png",BottomRight:"red_top_left.png",BottomLeft:"red_top_right.png"},Content:{Icon:"icon_gray.png",TextColor:"#333",SiteUrlColor:"#999",
LevelString:g_oRatingLevelToolTipString.LevelString.Untested,HelpString:g_oRatingLevelToolTipString.HelpString.Untested},WebIcon:"webicon_gray.png",Highlight:"#BDBDBD"},Trusted:{Tail:{TopRight:"red_bottom_left.png",TopLeft:"red_bottom_right.png",BottomRight:"red_top_left.png",BottomLeft:"red_top_right.png"},Content:{Icon:"icon_green.png",TextColor:"#333",SiteUrlColor:"#999",LevelString:g_oRatingLevelToolTipString.LevelString.Trusted,HelpString:g_oRatingLevelToolTipString.HelpString.Trusted},WebIcon:"webicon_green.png",
Highlight:"#b8eab8"},Blocked:{Tail:{TopRight:"red_bottom_left.png",TopLeft:"red_bottom_right.png",BottomRight:"red_top_left.png",BottomLeft:"red_top_right.png"},Content:{Icon:"icon_red.png",TextColor:"#333",SiteUrlColor:"#999",LevelString:g_oRatingLevelToolTipString.LevelString.Blocked,HelpString:g_oRatingLevelToolTipString.HelpString.Blocked},WebIcon:"webicon_red.png",Highlight:"#FA8F8F"},PCBlocked:{Tail:{TopRight:"red_bottom_left.png",TopLeft:"red_bottom_right.png",BottomRight:"red_top_left.png",
BottomLeft:"red_top_right.png"},Content:{Icon:"icon_red.png",TextColor:"#333",SiteUrlColor:"#999",LevelString:g_oRatingLevelToolTipString.LevelString.PCBlocked,HelpString:g_oRatingLevelToolTipString.HelpString.PCBlocked},WebIcon:"webicon_red.png",Highlight:"#FA8F8F"},ImgSize:{WebIcon:{width:16,height:16},Icon:{width:46,height:46},Tail:{width:30,height:60},PopupBodySize:{width:300,height:250},WarningIcon:{width:16,height:16}},LinkIcon:"arrow_blue.gif",CloseIcon:"close_pop.png",DotLine:"dotline.gif",
ShareIcon:"trendlogo.png",LogoIcon:"PC_Icon_Guide_16.png"},D_TSRSpanIDPrefix="TSRSpan_",D_TSRToolTipID="TSRToolTipLayer",D_TSRToolTipTailID="TSRToolTipTail",D_TSRToolTipBodyID="TSRToolTipBody",D_TSRToolTipTitleID="TSRToolTipTitle",D_TSRToolTipCloseSpanID="TSRToolTipCloseSpan",D_TSRToolTipLogoSpanID="TSRToolTipLogoSpan",D_TSRToolTipCloseID="TSRToolTipClose",D_TSRToolTipIconID="TSRToolTipIcon",D_TSRToolTipRLStringID="TSRToolTipRLString",D_TSRToolTipRLDetailedID="TSRToolTipRLDetailed",D_TSRToolTipRLDetailedShareID=
"TSRToolTipRLDetailedShare",D_TSRToolTipCheckUrlID="TSRCheckUrl",D_TSRToolTipSiteNameID="TSRToolTipSiteName",D_TSRToolTipSiteUrlID="TSRToolTipSiteUrl",D_TSRToolTipPhishingID="TSRToolTipPhishing",D_TSRToolTipTrustPageID="TSRToolTipTrustPage",D_TSRToolTipTrustPageLinkID="TSRToolTipTrustPageLink",D_TSRToolTipReviewPageID="TSRToolTipReviewPage",D_TSRToolTipReviewPageLinkID="TSRToolTipReviewPageLink",D_TSRToolTipShowClass="TSRshow",D_TSRToolTipHideClass="TSRhide",D_TSRHIGHLIGHT_COLOR_OFF="transparent",
D_HTTP_PREFIX="http://",D_PIXEL_UNIT="px",D_SITE_MSG_TRUNCATE_LIMIT=35,D_SITE_MSG_TRUNCATE_SUFFIC="...",D_GAP_BETWEEN_ICON_TITLE="2px",D_TOOLBAR_CALLBACK_ACTIVEX_PROG_ID="ProToolbarIMRatingActiveX.ToolbarCB",g_oRatingLevel={0:g_oImgDefine.Nolink,1:g_oImgDefine.Safe,2:g_oImgDefine.Neutral,3:g_oImgDefine.Dangerous,4:g_oImgDefine.Suspicious,5:g_oImgDefine.Untested,6:g_oImgDefine.Trusted,7:g_oImgDefine.Blocked,8:g_oImgDefine.PCBlocked};
