(function(){function h(){if(!sessionID){var a,b,c;a="";for(c=0;32>c;c++){if(8==c||12==c||16==c||20==c)a+="-";b=Math.floor(16*Math.random()).toString(16).toUpperCase();a+=b}sessionID=a}return sessionID}window.function_table={count:0};window.DoPSLocalReceiveMessage=function(a){PSDebug.log("[receive message] background page -> local page : ");PSDebug.log(a);PSDebug.log(JSON.stringify(a,void 0,4));if("privacy_scanner_setting_result"==a.type){a=a.dataOut.setting_items;for(var b in a){var c=a[b],d=c.key;
window.PrivacyScannerGlobalSettings[d]=c.value}}else if(function_table.hasOwnProperty(a.function_id)){if(a.isBrowser)function_table[a.function_id].success(a);else if("error"==a.type)switch(a.dataOut.ret_value){case "80000000":a.dataIn.params?get_scannerHelper(a.dataIn.Website).alertMessageOverTabContent_forceCloseTab():get_scannerHelper(a.dataIn.Website).alertMessageInTabContent_forceCloseTab();break;case "80000001":get_scannerHelper(a.dataIn.Website).alertMessageInTabContent_timeoutError()}else!0==
a.dataOut.ret_status?function_table[a.function_id].success&&function_table[a.function_id].success(a.dataOut.ret_value):function_table[a.function_id].error&&function_table[a.function_id].error(a.dataOut.ret_value);delete function_table[a.function_id]}else for(d in PSDebug.error("can not find function with ID: "+a.function_id),PSDebug.error("Current function table: "),function_table)PSDebug.error("key: "+d+"\n"),PSDebug.error("value -> success: "),PSDebug.error(String(function_table[d].success)),PSDebug.error("value -> error: "),
PSDebug.error(String(function_table[d].error))};window.DoPSLocalReceiveMessage=DoPSLocalReceiveMessage;window.sessionID=null;window.SendRequestToBackground_Website=function(a,b,c,d,g,e,k,l,m){var f=h()+"_"+function_table.count;d={isBrowser:!1,source:"local",destination:d,type:c,active:l||!1,needForceNewTab:m||!1,target_url:k,function_id:f,dataIn:{Website:e,params:g},dataOut:{ret_status:null,ret_value:null}};function_table[f]={};function_table[f].success=a;function_table[f].error=b;function_table.count++;
PSDebug.log("[send message] local page -> background page : ");PSDebug.log(d);"login"==c?PSLocalSendMessage(d):PSLocalSendMessage(d,TIMEOUT_SEND_REQUEST_TO_BACKGROUND)};window.SendRequestToBackground_Browser=function(a){var b=h()+"_"+function_table.count,c={isBrowser:!0,source:"Not Used",destination:"Not Used",function_id:b,dataIn:{action:a.action,postaction:a.postaction||"",restarturl:function(){var b=window.location.href.split("?"),c=b[0],b=b[1].split("&"),e=[];TMExt_$.each(b,function(a,b){b.split("=")[0]!=
URL_PARAM_RESTART_BROWSER&&e.push(b)});if(-1==TMExt_$.inArray(a.browser,AllBrowsers))return window.location.href;e.push(URL_PARAM_RESTART_BROWSER+"="+a.browser);b=e.join("&");return c+"?"+b}(),browser:a.browser,param:a.params},dataOut:{ret_status:null,ret_value:null}};function_table[b]={};function_table[b].success=a.success;function_table[b].error=a.error;function_table.count++;PSDebug.log("[send message] local page -> background page : ");PSDebug.log(c);PSDebug.log(JSON.stringify(c,void 0,4));PSLocalSendMessage(c,
TIMEOUT_SEND_REQUEST_TO_BACKGROUND)};window.SendRequestToBackground_openFaqPage=function(a,b){var c={type:"open_help_page",source:"local",dataIn:{help_type:"privacy_scanner_faq_help",help_website:a}};void 0!=b&&(c.dataIn.help_id=b);PSDebug.log("[send message] local page -> background page : ");PSDebug.log(c);PSLocalSendMessage(c)};window.SendRequestToBackground_openHelpLink=function(){var a={type:"open_help_page",source:"local",dataIn:{help_type:"privacy_scanner_help",help_website:"ALL"}};PSDebug.log("[send message] local page -> background page : ");
PSDebug.log(a);PSLocalSendMessage(a)};window.DCA_UTIL={_SendRequestToBackground_DCA:function(a,b){var c={type:"data_collection",source:"local",dataIn:{type:a,data:[b]}};PSDebug.info("[DCA]: type ->"+c.dataIn.type+" data: ->"+JSON.stringify(c.dataIn.data));PSDebug.info(c);PSLocalSendMessage(c)},lstBrowserUsageInfo:function(a,b,c){DCA_UTIL._SendRequestToBackground_DCA("lstBrowserUsageInfo",{nBrowserID:parseInt(a),sBrowserVersion:b,nBrowserClickTimes:parseInt(c)})},_lstLocalPageUsageInfo:function(a,
b,c,d,g,e){(a||0==a)&&DCA_UTIL._SendRequestToBackground_DCA("lstLocalPageUsageInfo",{nWebsiteID:parseInt(a),nScanTimes:parseInt(b),nPromotionTimes:parseInt(c),nFixAllTimes:parseInt(d),nShareTimes:parseInt(g),nSwitchUserClickTimes:parseInt(e)})},lstLocalPageUsageInfo:{nScanTimes:function(a,b){DCA_UTIL._lstLocalPageUsageInfo(a,b,0,0,0,0)},nPromotionTimes:function(a,b){DCA_UTIL._lstLocalPageUsageInfo(a,0,b,0,0,0)},nFixAllTimes:function(a,b){DCA_UTIL._lstLocalPageUsageInfo(a,0,0,b,0,0)},nShareTimes:function(a,
b){DCA_UTIL._lstLocalPageUsageInfo(a,0,0,0,b,0)},nSwitchUserClickTimes:function(a,b){DCA_UTIL._lstLocalPageUsageInfo(a,0,0,0,0,b)}},lstErrorPageUsageInfo:function(a,b,c){(a||0==a)&&DCA_UTIL._SendRequestToBackground_DCA("lstErrorPageUsageInfo",{nWebsiteID:parseInt(a),nErrorID:parseInt(b),nErrorShowTimes:parseInt(c)})},lstHelpUsageInfo:function(a,b,c){(a||0==a)&&DCA_UTIL._SendRequestToBackground_DCA("lstHelpUsageInfo",{nWebsiteID:parseInt(a),nHelpID:parseInt(b),nHelpClickTimes:parseInt(c)})},lstPSUsageInfo:function(a,
b){DCA_UTIL._SendRequestToBackground_DCA("lstPSUsageInfo",{nSourceTypeID:parseInt(a),nOpenTimes:parseInt(b)})}};window.SendRequestToBackground_Website=SendRequestToBackground_Website;window.SendWebRequest=function(a,b,c){var d;d=a.url;d=TMExt_$("<a>").prop("href",d).prop("hostname");d=-1!=d.indexOf("facebook")?FACEBOOK:-1!=d.indexOf("twitter")?TWITTER:-1!=d.indexOf("google")?GOOGLEPLUS:-1!=d.indexOf("linkedin")?LINKEDIN:"";SendRequestToBackground_Website(b,c,"ajax_request","",a,d)}})();
