(function(){window.GetListStyleFacebookData=function(a){for(var b=[],c=0;c<a.PrivacySetting.Items.length;c++)b.push(a.PrivacySetting.Items[c]);for(c=0;c<a.TimeLineAndTagging.Items.length;c++)b.push(a.TimeLineAndTagging.Items[c]);for(c=0;c<a.AppsAndWebsites.Items.length;c++)b.push(a.AppsAndWebsites.Items[c]);return b};window.SetVerticalCenter=function(a,b){if(a&&a.is(":visible")){var c=a.outerHeight();if(0!=c){var d=a.parent().height(),c=Math.ceil((d-c)/2);0<c&&(b?a.css("margin-top",c+b):a.css("margin-top",
c))}}};window.SetTextHorizontalCenter=function(a){if(a&&a.is(":visible")){var b=a.width();if(0!=b){var c=a.parent().width(),b=Math.ceil((c-b)/2);0<b&&a.css("margin-left",b)}}};window.SetHorizontalCenter=function(a){if(a&&a.is(":visible")){var b=a.outerWidth();if(0!=b){var c=a.parent().width(),b=Math.ceil((c-b)/2);0<b&&a.css("margin-left",b)}}};window.SetAbsoluteCenter=function(a){if(a&&a.is(":visible")){var b=a.outerHeight();if(0!=b){var c=a.parent().outerHeight(),b=Math.ceil((c-b)/2);0<b&&a.css("top",
b)}}};window.SetVerticalCenterPadding=function(a){if(a&&a.is(":visible")){var b=a.height();if(0!=b){var c=a.parent().height(),b=Math.ceil((c-b)/2);0<b&&a.css("padding-top",b)}}};window.ReUpdateUI_Layout=function(){TMExt_$(".privacy_item_content");for(var a=TMExt_$(".changesMade_area"),b=0;b<a.length;b++)SetVerticalCenter(a.eq(b).find(".changesMade_area_hitArea")),SetVerticalCenter(a.eq(b).find(".changesMade_area_saveChanges"));a=TMExt_$(".privacy_item_content_current_arrow");for(b=0;b<a.length;b++)SetVerticalCenter(a.eq(b));
a=TMExt_$(".div_head_image");for(b=0;b<a.length;b++)SetVerticalCenter(a.eq(b));a=TMExt_$(".overlay_quickFix_contentWrapper");for(b=0;b<a.length;b++)SetVerticalCenter(a.eq(b));a=TMExt_$(".fixAll_item_content_current");for(b=0;b<a.length;b++)SetVerticalCenter(a.eq(b));a=TMExt_$(".fixAll_item_content_toIcon");for(b=0;b<a.length;b++)SetVerticalCenter(a.eq(b));a=TMExt_$(".fixAll_item_content_suggestion");for(b=0;b<a.length;b++)SetVerticalCenter(a.eq(b));a=TMExt_$(".alertInTabContentArea_title_content");
for(b=0;b<a.length;b++)SetTextHorizontalCenter(a.eq(b));a=TMExt_$(".alertInTabContentArea_button");for(b=0;b<a.length;b++)SetHorizontalCenter(a.eq(b));a=TMExt_$(".privacy_item_content_ul");for(b=0;b<a.length;b++){var c=a.eq(b),d=c.prev().width();c.css({"min-width":d+24})}a=TMExt_$(".div_head_wrapper");c=TMExt_$(".user_area_name");for(b=0;b<a.length;b++){var d=a.eq(b),f=c.eq(b);d.is(":visible")&&d.css({width:f.outerWidth()+2})}ToolTipHelper.RefreshToolTip()};window.ToolTipHelper=function(){var a=null,
b=TMExt_$(".tooltip"),c=function(){var c=b.find(".tooltipArrow"),f=b.find(".tooltipContent"),e=a.offset();b.css({top:e.top+a.height(),left:e.left+(a.outerWidth()-f.outerWidth())/2});c.css({left:(f.outerWidth()-c.width())/2})};return{ShowTooltip:function(d,e){a=e;b.show();b.find(".tooltipContent").text(d);c(d)},HideTooltip:function(){b.hide()},RefreshToolTip:function(){a&&c()}}}();window.GetHowManyConcerns=function(a){for(var b=0,c=0;c<a.length;c++)-1!=a[c].Risk.indexOf(a[c].Current)&&b++;return b};
window.isSettingRisky=function(a,b){return-1!=TMExt_$.inArray(parseInt(a),b)?!0:!1};window.Initialize_UI=function(){for(var a=OptionSetting.getShowSiteOrBrowserList(),b=OptionSetting.getPromoteSiteOrBrowserList(),c=0;c<a.length;c++){var d=get_scannerHelper(a[c]);d.tabDom.show();d.contentDom.show();-1!==TMExt_$.inArray(a[c],b)&&d.alertMessageInTabContent_installProduct();-1!==TMExt_$.inArray(a[c],AllBrowsers)&&(TMExt_$(".BrowserArea").show(),TMExt_$(".SNSArea").addClass("notOnlySNS"))}window.ProductFeatureConfiguration&&
!1==window.ProductFeatureConfiguration.LocalPage.DisplayFootWebSiteArea||TMExt_$('a[name="footer_trend_dot_com"]').show();PUtil.checkBrowser.IsIE()||TMExt_$(".header_content_area_getHelp").click(function(){SendRequestToBackground_openHelpLink()})};window.TwitterIsNeedToShowPromotePS=function(){return PrivacyScannerGlobalSettings[SettingConstants.is_first_fixtwitter]};window.TwitterSetShowPromotePS=function(a){e(SettingConstants.is_first_fixtwitter,a)};window.LinkedinIsNeedToShowPromotePS=function(){return PrivacyScannerGlobalSettings[SettingConstants.is_first_fixlinkedin]};
window.LinkedinSetShowPromotePS=function(a){e(SettingConstants.is_first_fixlinkedin,a)};window.IsNeedToShowSaveChangesHint=function(){return PrivacyScannerGlobalSettings[SettingConstants.is_first_savechange]};window.SetShowSaveChangesHint=function(a){e(SettingConstants.is_first_savechange,a)};var e=function(a,b){PrivacyScannerGlobalSettings[a]=b;PSLocalSendMessage({type:"privacy_scanner_setting",source:"local",dataIn:{setting_type:"set",setting_items:[{key:a,value:b}]},dataOut:{setting_items:null}})}})();
