(function(){new MTwitterPScanner;var g=MTwitterScanResultsTemplate,f=function(){this.PROTOCOL_DOMAIN=window.location.protocol+"//"+window.location.host};f.prototype.logHeaderSendData="[MTwitter Fix -> send data]";f.prototype.logHeaderHandleResponseData="[MTwitter Fix -> handle response data]";f.prototype.getSendData_SettingPage=function(){var d={type:"GET",data:null,dataType:"html",url:null};d.url=this.PROTOCOL_DOMAIN;d.url+="/settings/account";(new SendDataLogger(this.logHeaderSendData+" : getSendData_SettingPage",
d)).getLog();return d};f.prototype.handleAuth_SettingPage=function(d){return d.find('[name="authenticity_token"]').val()};f.prototype.handleResponse_Single_SettingPage=function(d,b){(new ResponseHandlerLogger(this.logHeaderHandleResponseData+", ID : handleResponse_SettingPage",b)).getLog();var e={fixResult:[],fixResult_incomplete:!1},c=0;try{switch(String(d)){case "10":var a=this.getFixResultSampleByID("10"),c=0;a.Current="_1bfHukDN _1aj72xLB _3f2NsD-H"==b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c].className?
1:0;a.Title=b.find(document.getElementsByClassName("Fe7ul3Lt _2DggF3sL _2v8hsvrz")).prevObject[c].textContent;a.Title=TMExt_$.trim(a.Title);a.Desc="";a.Current!=g[c].Suggestion&&(b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c].click(),a.Current="_1bfHukDN _1aj72xLB _3f2NsD-H"==b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c].className?1:0);a.Status="ok";e.fixResult.push(a);break;case "11":a=this.getFixResultSampleByID("11");c=1;a.Current="_1bfHukDN _1aj72xLB _3f2NsD-H"==
b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c].className?1:0;a.Title=b.find(document.getElementsByClassName("Fe7ul3Lt _2DggF3sL _2v8hsvrz")).prevObject[c].textContent;a.Title=TMExt_$.trim(a.Title);a.Desc=b.find(document.getElementsByClassName("Fe7ul3Lt _1BL0F5oT _2DggF3sL _34Ymm628")).prevObject[0].textContent;a.Current!=g[c].Suggestion&&(b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c].click(),a.Current="_1bfHukDN _1aj72xLB _3f2NsD-H"==b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c].className?
1:0);a.Status="ok";e.fixResult.push(a);break;case "12":a=this.getFixResultSampleByID("12");c=2;a.Current="_1bfHukDN _1aj72xLB _3f2NsD-H"==b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c+1].className?1:0;a.Title=b.find(document.getElementsByClassName("Fe7ul3Lt _2DggF3sL _2v8hsvrz")).prevObject[c+2].textContent;a.Title=TMExt_$.trim(a.Title);a.Desc="";a.Current!=g[c].Suggestion&&(b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c+1].click(),a.Current="_1bfHukDN _1aj72xLB _3f2NsD-H"==
b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c+1].className?1:0);a.Status="ok";e.fixResult.push(a);break;case "13":a=this.getFixResultSampleByID("13");c=3;a.Current="_1bfHukDN _1aj72xLB _3f2NsD-H"==b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c+1].className?1:0;a.Title=b.find(document.getElementsByClassName("Fe7ul3Lt _2DggF3sL _2v8hsvrz")).prevObject[c+2].textContent;a.Title=TMExt_$.trim(a.Title);a.Desc="";a.Current!=g[c].Suggestion&&(b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c+
1].click(),a.Current="_1bfHukDN _1aj72xLB _3f2NsD-H"==b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c+1].className?1:0);a.Status="ok";e.fixResult.push(a);break;case "14":a=this.getFixResultSampleByID("14");c=4;a.Current="_1bfHukDN _1aj72xLB _3f2NsD-H"==b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c+3].className?1:0;a.Title=b.find(document.getElementsByClassName("Fe7ul3Lt _2DggF3sL _2v8hsvrz")).prevObject[c+4].textContent;a.Title=TMExt_$.trim(a.Title);a.Desc="";
a.Current!=g[c].Suggestion&&(b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c+3].click(),a.Current="_1bfHukDN _1aj72xLB _3f2NsD-H"==b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c+3].className?1:0);a.Status="ok";e.fixResult.push(a);break;case "15":a=this.getFixResultSampleByID("15"),c=5,a.Current="_1bfHukDN _1aj72xLB _3f2NsD-H"==b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c+1].className?1:0,a.Title=b.find(document.getElementsByClassName("Fe7ul3Lt _2DggF3sL _2v8hsvrz")).prevObject[c+
2].textContent,a.Title=TMExt_$.trim(a.Title),a.Desc=b.find(document.getElementsByClassName("Fe7ul3Lt _1BL0F5oT _2DggF3sL _34Ymm628")).prevObject[3].textContent,a.Current!=g[c].Suggestion&&(b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c+1].click(),a.Current="_1bfHukDN _1aj72xLB _3f2NsD-H"==b.find(document.getElementsByClassName("_1bfHukDN")).prevObject[c+1].className?1:0),a.Status="ok",e.fixResult.push(a)}return e}catch(f){PSDebug.error(f),e.fixResult_incomplete=!0}return e};f.prototype.handleResponse_SettingPage=
function(d){(new ResponseHandlerLogger(this.logHeaderHandleResponseData+", ID : handleResponse_SettingPage",d)).getLog();for(var b in g)this.handleResponse_Single_SettingPage(b.ID,d);return{fixResult:[],fixResult_incomplete:!1}};f.prototype.getAllvalidID=function(){for(var d=[],b=0;b<g.length;b++)d.push(g[b].ID);return d};f.prototype.isValidID=function(d){for(var b=this.getAllvalidID(),e=0;e<b.length;e++)if(d==b[e])return!0;return!1};f.prototype.getFixResultSampleByID=function(d){for(var b=0;b<g.length;b++)if(g[b].ID==
d)return PUtil.cloneObj(g[b])};f.prototype.getSendData=function(d,b,e){d={type:"POST",data:{authenticity_token:d,"settings[discoverable_by_email]":b["12"],"settings[discoverable_by_mobile_phone]":b["13"],"settings[geo_enabled]":b["14"],"settings[display_sensitive_media]":b["15"],"settings[protected]":b["11"],"settings[password]":e,commit:"Save"},dataType:"html",url:"https://mobile.twitter.com/settings/account"};(new SendDataLogger(this.logHeaderSendData+" : getSendData_SettingPage",d)).getLog();return d};
f.prototype.handleResponse=function(d,b){return{}};window.MTwitterFixHelper=f})();
