(function(h){var e={isTiInstalled:void 0,curCount:0,maxCount:10,callback_function:null,init_function:null,do_isTiInstalled:function(){return this.isTiInstalled},do_connect:function(a,c){var b=this;chrome.runtime.sendNativeMessage("com.trendmicro.tmtoolbar",{browser_id:"chrome",api:"GetProductInformation",dataIn:""},function(g){b.isTiInstalled="undefined"===typeof chrome.runtime.lastError;var d={ProductName:_T("product_name"),ProductVersion:null,ProductName_Ti:null};b.isTiInstalled&&(d.ProductVersion=
g.dataOut.ProductVersion,d.ProductName_Ti=decodeURI(g.dataOut.EncodedProductName),b.callback_function=a,b.init_function=c,b.port=chrome.runtime.connectNative("com.trendmicro.tmtoolbar"),b.port.onMessage.addListener(function(b){a(b)}),b.port.onDisconnect.addListener(function(){e.curCount++<e.maxCount&&setTimeout(function(){tbc_log("onDisconnect, and reconnect");e.do_connect(e.callback_function,e.init_function)},500)}));c(b.isTiInstalled,d)})},do_dispatch:function(a,c){if(this.port){var b=!0,d={browser_id:"chrome",
api:a||"",dataIn:c||""};try{this.port.postMessage(d)}catch(k){b=!1,tbc_error("Error when postMessage, dataIn="+TMExt_$.toJSON(d)+"error="+k)}b&&(e.curCount=0)}},template_anchor:document.createElement("a"),do_getHostPortFromURL:function(a){e.template_anchor.href=a;return{hostname:e.template_anchor.hostname,port:e.template_anchor.port||443}}},d={isTiInstalled:function(){return e.do_isTiInstalled()},connect:function(a,c){e.do_connect(a,c)},call_function:function(a,c){WaitAndCall(CONST_WAIT_BACKGROUND_TIME_OUT,
"Wait and call_function: "+a,function(){d.isTiInstalled()?e.do_dispatch(a,c):tbc_error("Titanium is not installed when calling:"+a+" dataIn:"+TMExt_$.toJSON(c))})},functionTable:{GetSetting:function(){if(d.isTiInstalled())GlobalExtensionProxy.call_function("GetSetting");else for(var a in Settings){var c=localStorage[a];"undefined"!==typeof c&&(Settings[a]="true"==c?1:0)}},GetLearnMoreURL:function(){Infos.LearnMoreURL=_T("help_page_base_url")+"100005/"},GetSerialNumber:function(){d.isTiInstalled()?
GlobalExtensionProxy.call_function("GetSerialNumber"):Infos.SerialNumber="GetSerialNumber"},SetEnableRatingStatus:function(a){GlobalExtensionProxy.call_function("SetSetting",{key:"EnableRating",value:a})},SetEnableManualRatingStatus:function(a){GlobalExtensionProxy.call_function("SetSetting",{key:"EnableManualRating",value:a})},SetEnableFBScannerStatus:function(a){GlobalExtensionProxy.call_function("SetSetting",{key:"EnableFBScanner",value:a})},SetFirstSNSScannerStatus:function(a,c){if(d.isTiInstalled())GlobalExtensionProxy.call_function("SetSetting",
{key:a,value:c});else{var b={FACEBOOK:"IsFirstFBScanner",TWITTER:"IsFirstTwitterScanner",GOOGLEPLUS:"IsFirstGooglePlusScanner",LINKEDIN:"IsFirstLinkedInScanner",IsFirstSaveChanges:"IsFirstSaveChanges",IsFirstFixTwitter:"IsFirstFixTwitter",IsFirstFixLinkedIn:"IsFirstFixLinkedIn"};a in b?localStorage[b[a]]=c:tbc_error("SetSetting error, cannot find: key="+a+" value="+c)}d.functionTable.GetSetting()},SendPSCollectionData:function(a){d.isTiInstalled()&&GlobalExtensionProxy.call_function("SendPSCollectionData",
a)},Feedback2SiteSafety:function(a,c,b,d,e){GlobalExtensionProxy.call_function("Feedback2SiteSafety",{url:a,site_owner:c,email:b,description:d,score:e})},updatePrivacyScannerUBM:function(){d.isTiInstalled()&&GlobalExtensionProxy.call_function("updatePrivacyScannerUBM")},WritePrivacyScannerLog:function(a){d.isTiInstalled()&&GlobalExtensionProxy.call_function("WritePrivacyScannerLog",a)},OpenSetting:function(){GlobalExtensionProxy.call_function("OpenSetting")},OpenHelp:function(){d.isTiInstalled()&&
GlobalExtensionProxy.call_function("OpenHelp")},OpenPSHelp:function(){var a=_T("help_page_base_url")+"100005/";window.open(a)},OpenHelpByID:function(a){a=_T("help_page_base_url")+a+"/";window.open(a)},RatingURL:function(a,c,b,d,e){for(var f in b)b[f]&&(b[f]=encodeURI(b[f]));GlobalExtensionProxy.call_function("RatingURL",{DocID:a,FlowID:c,UrlList:b,UrlArrLen:d,Category:e,IsEncoded:!0})},RatingSingleURL:function(a,c,b){c=encodeURI(c);GlobalExtensionProxy.call_function("RatingSingleURL",{DocID:a,Url:c,
Category:b,IsEncoded:!0})},DispatchBrowserPrivacyScanner:function(a){GlobalExtensionProxy.call_function("DispatchBrowserPrivacyScanner",{BPS_MSG:a})},SetTempImageSafeSearchStatus:function(a){GlobalExtensionProxy.call_function("SetSetting",{key:"EnableImageSafeSearch",value:a})},SendPSUsageInfoData:function(a){GlobalExtensionProxy.call_function("SendPSUsageInfoData",{SourceType:a})},CheckSSLCertificate:function(a,c){var b=e.do_getHostPortFromURL(c),d=b.hostname,b=b.port;GlobalExtensionProxy.call_function("CheckSSLCertificateSync",
{tabid:a,url:c,encoded_url:encodeURIComponent(c),hostname:d,port:b,use_system_proxy:!0,browser_proxy:""})},sendMail2TmpluginToolbar:function(a){GlobalExtensionProxy.call_function("sendMail2TmpluginToolbar",{params:a})}}};h.GlobalExtensionProxy=d})(window);
