function _tb_tryInitializeCRPattern(){if(!_tb_tryInitializeCRPattern.called){_tb_tryInitializeCRPattern.called=!0;for(var a in ContentRatingURLPatternType)ContentRatingURLPatternType[a].Rex=function(){this.rex_||(this.rex_=new RegExp(this.Pattern,"i"));return this.rex_}}}
function tb_loadCRPattern(a){tbc_log("tb_loadCRPattern,url="+a.href);_tb_tryInitializeCRPattern();for(var c in ContentRatingURLPatternType){var b=ContentRatingURLPatternType[c];if((tmb_EnableRating(Settings)||tmb_EnableImageFilter(Settings)&&b.Engine.ImageFilter)&&b.Rex().test(a.href))return b.Engine.Categary==TCategary.E_CATEGARY_SNS&&!Settings.SNSEnable||b.Engine.Categary==TCategary.E_CATEGARY_SEARCHRESULT&&!Settings.SREnable||b.Engine.Categary==TCategary.E_CATEGARY_WEBMAIL&&!Settings.WMEnable?
null:b}tbc_log("no pattern");return null}var fakePlugin={RatingURL:function(){tbc_log("Fake Rating URL is called")},EnableRating:function(a){tbc_log("Fake enable rating , value="+a)},OpenSetting:function(){tbc_log("Fake Open setting is called")},OpenHelp:function(){tbc_log("Fake Open help is called")}};function getPluginTB(){return GlobalExtensionProxy.functionTable}function tmb_IconEnable(a){return a.Enable&&a.WTPEnable&&!a.LicenseExpired}
function tmb_Enable(a){return a.Enable&&!a.LicenseExpired}function tmb_EnableRating(a){return a.EnableRating&&a.WTPEnable&&a.Enable&&!a.LicenseExpired}function tmb_EnableManualRating(a){return a.EnableManualRating&&a.WTPEnable&&a.Enable&&!a.LicenseExpired}function tmb_EnableFBScanner(a){return a.EnableFBScanner&&a.WTPEnable&&a.Enable&&!a.LicenseExpired}function tmb_EnableImageFilter(a){return a.EnableImageSafeSearch&&a.WTPEnable&&a.Enable&&!a.LicenseExpired}
function tmb_EnableCheckSSLCert(a){return a.EnableCheckSSLCert&&a.WTPEnable&&a.Enable&&!a.LicenseExpired}function tmb_EnableSNSFeedback(a){return a.EnableSNSFeedback&&a.WTPEnable&&a.Enable&&!a.LicenseExpired}
function OnSettingChangeCallback(a){Settings.WTPEnable=a.WTPEnable;Settings.Enable=a.Enable;Settings.EnableRating=a.EnableRating;Settings.EnableManualRating=a.EnableManualRating;Settings.EnableFBScanner=a.EnableFBScanner;Settings.EnableFBScannerFeatureSKU=a.EnableFBScannerFeatureSKU;Settings.IsFirstFBScanner=a.IsFirstFBScanner;Settings.IsFirstTwitterScanner=a.IsFirstTwitterScanner;Settings.IsFirstGooglePlusScanner=a.IsFirstGooglePlusScanner;Settings.IsFirstLinkedInScanner=a.IsFirstLinkedInScanner;
Settings.IsFirstSaveChanges=a.IsFirstSaveChanges;Settings.IsFirstFixTwitter=a.IsFirstFixTwitter;Settings.IsFirstFixLinkedIn=a.IsFirstFixLinkedIn;Settings.IsConsoleLogEnabled=a.IsConsoleLogEnabled;Settings.IsFileLogEnabled=a.IsFileLogEnabled;Settings.SNSEnable=a.SNSEnable;Settings.WMEnable=a.WMEnable;Settings.SREnable=a.SREnable;Settings.LicenseExpired=a.LicenseExpired;Settings.NotActivated=a.NotActivated;Settings.RatingTimeout=a.RatingTimeout;Settings.EnableImageSafeSearch=a.EnableImageSafeSearch;
Settings.EnableCheckSSLCert=a.EnableCheckSSLCert;Settings.EnableSNSFeedback=a.EnableSNSFeedback;Settings.BrowserStatus=a.BrowserStatus;iconName=tmb_IconEnable(a)?TB_PATHS.IMAGE_LOGO:TB_PATHS.IMAGE_LOGO_DISABLE;chrome.browserAction.setIcon({path:TB_PATHS.IMAGE_PATH+iconName});popupName=tmb_Enable(a)?getCurrentPopup(Infos.ProductVersion):"";chrome.browserAction.setPopup({popup:popupName});chrome.tabs.query({},function(c){for(var b in c)chrome.tabs.sendMessage(c[b].id,{action:TB_ACTIONS.FORCE_REFRESH_PAGE,
ForceRefresh:a.ForceRefresh})})}function OnRatingURLCallback(a,c,b,d,e,f){if(tmb_EnableRating(Settings)||tmb_EnableImageFilter(Settings)){tbc_log("rating result is:,docID="+a+",url="+e+",flowID="+c+",resultID="+b+",ratingLevel="+d);var g=portsToDocument[a];if(g)try{g.postMessage({action:TB_ACTIONS.INSERTRATINGRESULT,params:{docID:a,flowID:c,resultID:b,ratingLevel:d,url:decodeURI(e),bPhishing:f}})}catch(h){tbc_error(h)}else tbc_log("can not find the port,windowguid="+a)}}
function OnRatingSingleURLCallback(a,c,b,d){if(tmb_EnableManualRating(Settings)){tbc_log("OnRatingSingleCallback: docID="+a+",url="+c+",retLevel="+b+",bPhishing="+d);var e=portsToDocument[a];if(e)try{e.postMessage({action:TB_ACTIONS.INSERTSINGLERESULT,params:{docID:a,url:decodeURI(c),ratingLevel:b,bPhishing:d}})}catch(f){tbc_error(f)}else tbc_log("can not find the port,windowguid="+a)}}var g_block_page_show_times=1;
function OnCheckSSLCertificateCallback(a){tbc_log(a);a.block&&chrome.tabs.get(a.tabid,function(c){if(c.url==a.url)try{var b=3>=++g_block_page_show_times?0:1,d=chrome.extension.getURL("TMToolbar\\CheckSSLCert\\block_page\\index.html?url="+a.encoded_url+"&show_more="+b+"&locale="+getCurrentLocale()+"&product_name_ti="+Infos.ProductName_Ti);chrome.tabs.update(a.tabid,{url:d})}catch(e){tbc_error("show blocking page failed, e:"),tbc_error(e)}})}
function ratingSingleURL(a,c,b){tbc_log("start ManualRatingURL params.guid="+a.windowguid+" params.url="+a.url);getPluginTB().RatingSingleURL(a.windowguid,a.url,TCategary.E_CATEGORY_MANUAL_RATING.toString())}function ratingURLS2(a){tbc_log("params.urls.length="+a.urls.length);a.urls.length&&getPluginTB().RatingURL(a.windowguid.toString(),a.flowid.toString(),a.urls,a.urls.length.toString(),a.category.toString())}
function feedback2SiteSafety(a){getPluginTB().Feedback2SiteSafety(a.url.toString(),a.site_owner.toString(),a.email.toString(),a.description.toString(),a.score)}function setTempImageSafeSearchStatus(){getPluginTB().SetTempImageSafeSearchStatus(!1)}function sendMail2TmpluginToolbar(a){getPluginTB().sendMail2TmpluginToolbar(a)};
