var m_RatingDocs=[],GetChromeVersion=function(){var a="null";try{var b=navigator.userAgent.toLowerCase(),c=b.indexOf("chrome"),d=b.substring(c),c=d.indexOf(" safari"),d=d.substring(7,c),b=[],b=d.split("."),a=b[0]+"."+b[1]+"."+b[2]+"."+b[3]}catch(e){tbc_error(e)}return a};function tryToInjectElement(a,b){var c=null,d=a.getElementsByTagName("head");0<d.length&&(c=d[0]);c||(c=a.documentElement);return c?!!c.appendChild(b):null}
function injectScript(a,b){var c=a.createElement("script");c.setAttribute("type","text/javascript");c.setAttribute("src",getURL(b));return tryToInjectElement(a,c)}function injectScripts(a,b){for(var c in b)injectScript(a,b[c])}function injectCss(a,b){var c=document.createElement("LINK");c.setAttribute("type","text/css");c.setAttribute("src",getURL(b));c.setAttribute("rel","stylesheet");return tryToInjectElement(a,c)}function injectCsses(a,b){for(var c in b)injectCss(a,b[c])}
var CreatePageRatingHandler=function(a){if(null==a)return new DefaultCRHandler(null);var b=null;switch(a.Engine.Categary){case TCategary.E_CATEGARY_SNS:b=new PageRatingHandler(a);break;case TCategary.E_CATEGARY_SEARCHRESULT:b=new PageRatingHandler(a);break;case TCategary.E_CATEGARY_WEBMAIL:b=new PageRatingHandler(a);break;default:tbc_log("No possible")}return b},CreateManualRatingHandler=function(){return new ManualRatingHandler(null)},TFunctionWrapper=tb_createClass({initialize:function(a){this.doc=
a},isReady:function(){return!0},prepare:function(){return!1},call:function(){},trycall:function(){if(this.isReady()||this.prepare.apply(this,arguments))return this.call.apply(this,arguments)}}),TFunctionPrepareParse=tb_createClass({isReady:function(){return!0},prepare:function(a){return ret},call:function(a,b,c){tbc_log("enter TFunctionPrepareParse::prepare");this.isReady()&&TSRPrepareParse(function(d){tbc_log("enter TFunctionPrepareParse::callback");var e=d.getElementById(TAG_ID4TOOLBAR_GUID);tbc_log("windowguid="+
b);e&&tbc_log("tagGUID="+e.innerHTML);c(a,d)},!1)}},TFunctionWrapper),TFunctionInnerParse=tb_createClass({isReady:function(){return!1},prepare:function(a,b){tbc_log("enter TFunctionInnerParse2::prepare,guid="+b);var c=new TFunctionPrepareParse(this.doc);c.trycall.apply(c,arguments);return!0},call:function(a){return!0}},TFunctionWrapper),TFunctionParse=tb_createClass({isReady:function(){return"undefined"!==typeof TSRParse},prepare:function(a){tbc_log("enter TFunctionParse::prepare");this.doc.D_TSRToolTipTitleString=
D_TSRToolTipTitleString;this.doc.g_oRatingLevelToolTipString=g_oRatingLevelToolTipString;var b=[TB_PATHS.JS_CRENGINE_RES_DEFINE,TB_PATHS.JS_CRENGINE_LIB];a.Engine.ParserRule&&b.push(TB_PATHS.CRPATTERN+URLSEP+a.Engine.ParserRule);a.Engine.SupportShareToFriend&&1==a.Engine.SupportShareToFriend&&b.push(TB_PATHS.JS_ALERT_LIB);a.Engine.EnableFeedbackSnsUnsafeUrl&&1==a.Engine.EnableFeedbackSnsUnsafeUrl&&(b.push(TB_PATHS.JS_SENDMAIL_LIB),b.push(TB_PATHS.JS_SNS_FEEDBACK_LIB));injectScripts(this.doc,b);console.info("prepare is ok");
a=[getLocaleResource("_locales",TB_PATHS.CSS_SR)];injectCsses(this.doc,a);return!0},call:function(a){tbc_log("enter TFunctionParse::call,ready="+this.isReady());if(this.isReady()){var b=null;try{var c=window;TSRInitToolTip(getURL(TB_PATHS.IMAGE_TOOLTIP),m_oSRSetting.bMouseOver.value,m_oSRSetting.bHighlight.value,m_oSRSetting.lTooltipTimeout.value,c.ContentPageCacheSettings.EnableImageSafeSearch,c.ContentPageCacheSettings.RatingTimeout);tbc_log("before call TSRParse");b=TSRParse();tbc_log("searchResults.length="+
b.length)}catch(d){tbc_log(d)}b&&0!=b.length&&(tbc_log("the length of search result is "+b.length),RatingURLs(this.doc,b,a))}}},TFunctionWrapper),DefaultCRHandler=tb_createClass({initialize:function(a){this.crpattern=a},startRating:function(){tbc_log("==> tb_createClass")},parseIFrames:function(){tbc_log("==> tb_createClass")},getScripts:function(){if(!this.crpattern)return[];var a=[];this.crpattern.Engine.ParserRule&&a.push(TB_PATHS.CRPATTERN+URLSEP+this.crpattern.Engine.ParserRule);this.crpattern.Engine.SupportShareToFriend&&
1==this.crpattern.Engine.SupportShareToFriend&&a.push(TB_PATHS.JS_ALERT_LIB);this.crpattern.Engine.EnableFeedbackSnsUnsafeUrl&&1==this.crpattern.Engine.EnableFeedbackSnsUnsafeUrl&&(a.push(TB_PATHS.JS_SENDMAIL_LIB),a.push(TB_PATHS.JS_SNS_FEEDBACK_LIB));return a},getCsses:function(){return this.crpattern?[getLocaleResource("_locales",TB_PATHS.CSS_SR)]:[]}}),ManualRatingHandler=tb_createClass({startRating:function(){},parseIFrames:function(a,b){tbc_log("enter parseIFrames of ManualRatingHandler");b(document)},
getScripts:function(){return[]},getCsses:function(){return[getLocaleResource("_locales",TB_PATHS.CSS_SR)]}},DefaultCRHandler),PageRatingHandler=tb_createClass({innerParse:null,startRating:function(){},parseIFrames:function(a,b){this.innerParse=(new TFunctionInnerParse(document)).trycall(this.crpattern,a,b)}},DefaultCRHandler);
function RatingURLs(a,b,c){a=[];for(var d=1;d<b.length;d++){var e=b[d];e&&(e.sended?tbc_log("objResult has been sent"):(e.sended=!0,a[d]=e.link))}d=document.getElementById(TAG_ID4TOOLBAR_GUID).innerText;try{portToBackground.postMessage({action:TB_ACTIONS.RATINGURLS,params:{windowguid:d,flowid:b.FlowID,urls:a,category:c.Engine.Categary}})}catch(f){tbc_error(f)}};
