var Settings={WTPEnable:1,Enable:1,EnableRating:0,EnableManualRating:0,IsFirstFBScanner:0,IsFirstTwitterScanner:0,IsFirstGooglePlusScanner:1,IsFirstLinkedInScanner:0,IsFirstSaveChanges:1,IsFirstFixTwitter:1,IsFirstFixLinkedIn:1,IsConsoleLogEnabled:1,IsFileLogEnabled:1,EnableFBScanner:1,EnableFBScannerFeatureSKU:1,SNSEnable:1,WMEnable:1,SREnable:1,EnableCheckSSLCert:1,EnableSNSFeedback:1,LicenseExpired:0,NotActivated:0,debug:0,RatingTimeout:CONST_RATING_TIME_OUT,BrowserStatus:""},Infos={ProductName:null,
ProductVersion:null,LearnMoreURL:null,SerialNumber:null},ActionParameterCache=null;tbb_addRequestHandler(TB_ACTIONS.PRELOAD,function(b,a,c){(b=tb_loadCRPattern(b.url))&&c(b)});
function DoInjectResourceAction(b,a){var c=a.params,d=a.callback;if(c.scripts)for(var e in c.scripts)tbc_log("resource path="+c.scripts[e]),chrome.tabs.executeScript(b,{file:c.scripts[e],allFrames:"undefined"!==typeof c.all_frames?c.all_frames:!0});if(c.csses)for(e in c.csses)tbc_log("resource path="+c.csses[e]),chrome.tabs.insertCSS(b,{file:c.csses[e],allFrames:"undefined"!==typeof c.all_frames?c.all_frames:!0});chrome.tabs.executeScript(b,{code:"bResourceInjected=true;",allFrames:"undefined"!==
typeof c.all_frames?c.all_frames:!0},function(){try{tbc_log("callback after script has been inserted"),d()}catch(a){tbc_error("Catch error:"),tbc_error(a)}})}chrome.tabs.onReplaced.addListener(function(b,a){tbc_log("Tab "+a+" has been replaced by tab "+b+".");tbc_log(ActionParameterCache);ActionParameterCache&&(DoInjectResourceAction(b,ActionParameterCache),ActionParameterCache=null)});
tbb_addRequestHandler(TB_ACTIONS.INJECTRESOURCES,function(b,a,c){ActionParameterCache={params:b,callback:c};a.tab&&-1!=a.tab.index&&-1!=a.tab.id&&0!=a.tab.url.indexOf("chrome://")&&DoInjectResourceAction(a.tab.id,ActionParameterCache)});tbb_addRequestHandler(TB_ACTIONS.RATINGSINGLEURL,function(b,a,c){ratingSingleURL(b,a,c)});
tbb_addRequestHandler(TB_ACTIONS.IFRAMELOADED,function(b,a,c){tbc_log("handler of IFRAMELOADED in background");chrome.tabs.sendRequest(a.tab.id,{action:TB_ACTIONS.IFRAMELOADED+"_TopWindow",params:b},c)});var portsToDocument={};
chrome.extension.onConnect.addListener(function(b){tbc_log("port.name="+b.name);portsToDocument[b.name]=b;b.onMessage.addListener(function(a){var b=a.action;TB_ACTIONS.RATINGURLS==b?(tbc_log("handle TB_ACTIONS.RATINGURLS"),ratingURLS2(a.params)):TB_ACTIONS.RATINGSINGLEURL==b&&(tbc_log("handle TB_ACTIONS.RATINGSINGLEURL"),ratingSingleURL(a.params))})});function toJson(b){var a="{";for(p in b)a=a+p+":"+b[p]+",";a=a.substr(0,a.length-1);return a+"}"}
function CallbackFunction(b){var a=b.dataOut;switch(b.type){case "PageRatingCallback":OnRatingURLCallback(a.DocID,a.FlowID,a.ResultID,a.RetLevel,a.Url,a.Phishing);break;case "ManualRatingCallback":OnRatingSingleURLCallback(a.DocID,a.Url,a.RetLevel,a.Phishing);break;case "SettingChangedCallback":OnSettingChangeCallback(a);break;case "GetLearnMoreURL":Infos.LearnMoreURL=a.LearnMoreURL;break;case "GetSerialNumber":Infos.SerialNumber=a.SerialNumber;break;case "BrowserPrivacyCallback":PSBackground.SendMessageToLocalPage(a.BPS_MSG);
break;case "CheckSSLCertificateCallback":OnCheckSSLCertificateCallback(a);break;case "NOT_SUPPORT_INTERFACE":console.warn("Don't support such interface:"+TMExt_$.toJSON(a.SourceDataIn))}}var WaitAndCall=function(b,a,c){setTimeout(function(){tbc_log(a);void 0===GlobalExtensionProxy.isTiInstalled()?setTimeout(arguments.callee,b):c()},0)};
function initPlugin(){(function(){var b=CONST_WAIT_BACKGROUND_TIME_OUT;tbb_addRequestHandler(TB_ACTIONS.CAN_RATING,function(a,c,d){WaitAndCall(b,"CAN_RATING GlobalExtensionProxy.isTiInstalled()="+GlobalExtensionProxy.isTiInstalled(),function(){if(tmb_EnableRating(Settings)||tmb_EnableImageFilter(Settings)||Settings.debug)tbc_log("callback settings="+toJson(Settings)),d(Settings)})});tbb_addRequestHandler(TB_ACTIONS.CAN_MANUAL_RATING,function(a,c,d){WaitAndCall(b,"CAN_MANUAL_RATING GlobalExtensionProxy.isTiInstalled()="+
GlobalExtensionProxy.isTiInstalled(),function(){if(tmb_EnableManualRating(Settings)||Settings.debug)tbc_log("callback settings="+toJson(Settings)),d(Settings)})});tbb_addRequestHandler(TB_ACTIONS.CAN_FB_SCANNER,function(a,c,d){WaitAndCall(b,"CAN_FB_SCANNER GlobalExtensionProxy.isTiInstalled()="+GlobalExtensionProxy.isTiInstalled(),function(){if(tmb_EnableFBScanner(Settings)||Settings.debug)tbc_log("callback settings="+toJson(Settings)),d(Settings)})});tbb_addRequestHandler(TB_ACTIONS.GET_FIRST_SCANNER_STATUS,
function(a,c,d){WaitAndCall(b,"GET_FIRST_SCANNER_STATUS GlobalExtensionProxy.isTiInstalled()="+GlobalExtensionProxy.isTiInstalled(),function(){d(Settings)})});tbb_addRequestHandler(TB_ACTIONS.SET_FIRST_SCANNER_STATUS,function(a,c,d){WaitAndCall(b,"SET_FIRST_SCANNER_STATUS GlobalExtensionProxy.isTiInstalled()="+GlobalExtensionProxy.isTiInstalled(),function(){tbc_log("set first SNS Scanner");getPluginTB().SetFirstSNSScannerStatus(a.Website,a.value);d()})});tbb_addRequestHandler(TB_ACTIONS.OPEN_HELP,
function(a,c,d){WaitAndCall(b,"OPEN_HELP GlobalExtensionProxy.isTiInstalled()="+GlobalExtensionProxy.isTiInstalled(),function(){tbc_log("open help");getPluginTB().OpenHelp();d()})});tbb_addRequestHandler(TB_ACTIONS.OPEN_FBPS_HELP,function(a,c,d){WaitAndCall(b,"OPEN_FBPS_HELP GlobalExtensionProxy.isTiInstalled()="+GlobalExtensionProxy.isTiInstalled(),function(){tbc_log("open help");getPluginTB().OpenFBPSHelp();d()})});tbb_addRequestHandler(TB_ACTIONS.UBM_FBSCANNER,function(a,c,d){WaitAndCall(b,"UBM_FBSCANNER GlobalExtensionProxy.isTiInstalled()="+
GlobalExtensionProxy.isTiInstalled(),function(){tbc_log("UBM for PrivacyScanner");getPluginTB().updatePrivacyScannerUBM();d()})});tbb_addRequestHandler(TB_ACTIONS.GET_INFORMATION,function(a,c,d){WaitAndCall(b,"GET_INFORMATION GlobalExtensionProxy.isTiInstalled()="+GlobalExtensionProxy.isTiInstalled(),function(){tbc_log("get information, product name, learn more url");Infos.isTiInstalled=GlobalExtensionProxy.isTiInstalled();Infos.BrowserStatus=Settings.BrowserStatus;d(Infos)})});tbb_addRequestHandler(TB_ACTIONS.FEEDBACK_2_SITESAFETY,
function(a,c,d){WaitAndCall(b,"FEEDBACK_2_SITESAFETY GlobalExtensionProxy.isTiInstalled()="+GlobalExtensionProxy.isTiInstalled(),function(){tbc_log("feedback 2 sitesafety, params="+a.params);feedback2SiteSafety(a.params)})});tbb_addRequestHandler(TB_ACTIONS.SET_TEMP_IMAGE_SAFE_SEARCH,function(a,c,d){WaitAndCall(b,"SET_TEMP_IMAGE_SAFE_SEARCH GlobalExtensionProxy.isTiInstalled()="+GlobalExtensionProxy.isTiInstalled(),function(){setTempImageSafeSearchStatus()})});tbb_addRequestHandler(TB_ACTIONS.SEND_PS_USAGE_INFO,
function(a,c,d){WaitAndCall(b,"SEND_PS_USAGE_INFO GlobalExtensionProxy.isTiInstalled()="+GlobalExtensionProxy.isTiInstalled(),function(){tbc_log("SEND_PS_USAGE_INFO, SourceType="+a.SourceType);getPluginTB().SendPSUsageInfoData(a.SourceType)})});tbb_addRequestHandler(TB_ACTIONS.SEND_MAIL_2_TMPLUGIN_TOOLBAR,function(a,c,d){WaitAndCall(b,"FeedbackSnsUnsafeURL GlobalExtensionProxy.isTiInstalled()="+GlobalExtensionProxy.isTiInstalled(),function(){tbc_log("SEND_MAIL_2_TMPLUGIN_TOOLBAR, params="+a.params);
var b=JSON.parse(a);sendMail2TmpluginToolbar(b.params)})})})();GlobalExtensionProxy.connect(CallbackFunction,function(b,a){b||(chrome.browserAction.setPopup({popup:TB_PATHS.HTML_POPUP_STORE_ONLY}),chrome.browserAction.setIcon({path:TB_PATHS.IMAGE_PATH+TB_PATHS.IMAGE_LOGO}));b&&IsProductVersion_9_OrLater(a.ProductVersion)&&WaitAndCall(CONST_WAIT_BACKGROUND_TIME_OUT,"tmb_EnableCheckSSLCert GlobalExtensionProxy.isTiInstalled()="+GlobalExtensionProxy.isTiInstalled(),function(){(tmb_EnableCheckSSLCert(Settings)||
Settings.debug)&&chrome.webRequest.onBeforeRequest.addListener(function(a){tmb_EnableCheckSSLCert(Settings)&&getPluginTB().CheckSSLCertificate(a.tabId,a.url)},{urls:["https://*/*"],types:["main_frame"]},["blocking"])});Infos.ProductName=a.ProductName;Infos.ProductVersion=a.ProductVersion;Infos.ProductName_Ti=a.ProductName_Ti;getPluginTB().GetSetting();getPluginTB().GetLearnMoreURL();getPluginTB().GetSerialNumber()})}window.addEventListener("load",initPlugin,!1);
