(function(){var c=function(){};c.prototype.logHeaderSendData="[MFacebook Scan -> send data]";c.prototype.logHeaderHandleResponseData="[MFacebook Scan -> handle response data]";c.prototype.getSendData=function(e){var a={type:"GET",data:null,dataType:"html",url:MFacebookScanResultsTemplate[M_getScanResultIndexByID(e)].URL};(new SendDataLogger(this.logHeaderSendData+" : "+e,a)).getLog();return a};c.prototype.handleResponse=function(e,a){(new ResponseHandlerLogger(this.logHeaderHandleResponseData+", ID : "+
e,a)).getLog();var b=this.getScanResultSampleByID(e),d=TMExt_$(a),c={};c.FixRelatedData={URL:d.find('form[method="post"]').attr("action"),form:{fb_dtsg:d.find('input[name="fb_dtsg"]').attr("value"),charset_test:d.find('input[name="charset_test"]').attr("value"),fixList:[]}};try{switch(String(e)){case "20":this.generateResources_20(a,c);break;case "22":case "23":case "83":this.generateResources_23(a,c);break;case "24":this.generateResources_24(a,c);break;case "31":case "35":this.generateResources_31(a,
c);break;case "33":case "34":this.generateResources_33(a,c);break;case "81":this.generateResources_81(a,c)}this.copySettingResources(b,c);this.copySettingResources(MFacebookScanResultsTemplate[M_getScanResultIndexByID(e)],c);return b}catch(f){return PSDebug.error(f),null}};c.prototype.getAllvalidID=function(){for(var e=[],a=0;a<MFacebookScanResultsTemplate.length;a++)e.push(MFacebookScanResultsTemplate[a].ID);return e};c.prototype.isValidID=function(e){for(var a=this.getAllvalidID(),b=0;b<a.length;b++)if(e==
a[b])return!0;return!1};c.prototype.getScanResultSampleByID=function(e){for(var a=0;a<MFacebookScanResultsTemplate.length;a++)if(MFacebookScanResultsTemplate[a].ID==e)return PUtil.cloneObj(MFacebookScanResultsTemplate[a])};c.prototype.copySettingResources=function(e,a){for(var b in a)e[b]=a[b]};c.prototype.generateResources_20=function(e,a){var b=TMExt_$(e);a.Title=b.find("#root >div >div:eq(0)").text();a.Desc=b.find("#root >div >div:eq(1)").text();a.Desc||(a.Desc=a.Title);b=b.find('label[data-sigil~="touchable"]');
a.PossibleValue={};a.possibleFixValue=[];for(var d=0;d<b.length;d++)a.PossibleValue[d]=b.eq(d).find('span[data-sigil="label"]').text(),a.possibleFixValue.push(d),a.FixRelatedData.form.fixList.push(b.eq(d).find('input[type="radio"]').attr("value")),b.eq(d).find('input[name="privacyx"]').attr("checked")&&(a.Current=d)};c.prototype.generateResources_23=function(e,a){var b=TMExt_$(e),d=b.find("#root >div >div:eq(0)").text(),c=b.find("#root >div >div:eq(1)").text(),f=b.find("#root >div >div:eq(2)").text();
d?(a.Title=d,a.Desc=c):(a.Title=c,a.Desc=f);a.Desc||(a.Desc=a.Title);b=b.find('label[data-sigil~="touchable"]');a.PossibleValue={};a.possibleFixValue=[];for(d=0;d<b.length;d++)a.PossibleValue[d]=b.eq(d).find('span[data-sigil="label"]').text(),a.possibleFixValue.push(d),a.FixRelatedData.form.fixList.push(b.eq(d).find('input[type="radio"]').attr("value")),b.eq(d).find('input[name="privacyX"]').attr("checked")&&(a.Current=d)};c.prototype.generateResources_24=function(e,a){var b=TMExt_$(e);a.Title=b.find("#root >div >div:eq(0)").text();
a.Desc=b.find("#root >div >div:eq(1)").text();a.PossibleValue={0:null,1:null};a.Current=b.find('input[name="enable"]').attr("checked")?1:0;a.possibleFixValue=[0,1];a.FixRelatedData.form.fixList=[0,1]};c.prototype.generateResources_31=function(e,a){var b=TMExt_$(e),d=b.find("section._55ws p");a.Desc="";for(var c=0;c<d.length;c++){var f=TMExt_$(d[c]).text();f&&(a.Title?a.Desc+=f+" ":a.Title=f)}a.Desc||(a.Desc=a.Title);a.PossibleValue={0:b.find('span[class="_55mr"]').text(),1:b.find('span[class="_55ms"]').text()};
a.Current=b.find('input[name="enable"]').attr("checked")?0:1;a.possibleFixValue=[0,1];a.FixRelatedData.form.fixList=[1,0]};c.prototype.generateResources_33=function(c,a){var b=TMExt_$(c);a.Title=b.find("#root >div >div:eq(0)").text();a.Desc=a.Title;a.Desc||(a.Desc=a.Title);b=b.find('label[data-sigil~="touchable"]');a.PossibleValue={};a.possibleFixValue=[];for(var d=0;d<b.length;d++)a.PossibleValue[d]=b.eq(d).find('span[data-sigil="label"]').text(),a.possibleFixValue.push(d),a.FixRelatedData.form.fixList.push(b.eq(d).find('input[type="radio"]').attr("value")),
b.eq(d).find('input[name="privacyX"]').attr("checked")&&(a.Current=d)};c.prototype.generateResources_35=function(c,a){var b=TMExt_$(c);a.Title=b.find('span[class="_528h mfss _52ja"] >p:eq(0)').text();a.Desc=b.find('span[class="_528h mfss _52ja"] >p:gt(0)').text();a.PossibleValue={0:b.find('span[class="_55mr"]').text(),1:b.find('span[class="_55ms"]').text()};a.Current=b.find('input[name="enable"]').attr("checked")?0:1;a.possibleFixValue=[0,1];a.FixRelatedData.form.fixList=[1,0]};c.prototype.generateResources_81=
function(c,a){var b=TMExt_$(c);a.Title=b.find("#root >div >div:eq(0)").text();a.Desc=b.find("#root >div >div:eq(1)").text();a.Desc||(a.Desc=a.Title);a.PossibleValue={0:null,1:null};0<b.find('input[type="checkbox"][checked]').length?1==b.find('input[type="checkbox"][checked]').length&&"Posts on my timeline"==b.find('input[type="checkbox"][checked]').parent().prev().text()?a.Current=0:a.Current=1:a.Current=0;a.possibleFixValue=[0]};c.prototype.getHTMLContent=function(c){return TMExt_$.parseJSON(c.substring(c.indexOf("{")))};
window.MFacebookScannerHelper=c})();
