(function(){var h=function(){this.responseHeaderScanSingle=MFPScanSingleResponse;this.responseHeaderScan=MFPScanResponse};h.prototype.getAllURLInfo=function(d,e){function b(){if(g==f)return d()}var f=3,g=0;SendWebRequest({type:"GET",data:null,dataType:"html",url:URLList.Privacy},function(c){c=TMExt_$(c);MFacebookScanResultsTemplate[M_getScanResultIndexByID("20")].URL=c.find('div[class="_56be"]:eq(0) a[class="_5b6s"]:eq(0)').attr("href");MFacebookScanResultsTemplate[M_getScanResultIndexByID("22")].URL=
c.find('div[class="_56be"]:eq(2) a[class="_5b6s"]:eq(0)').attr("href");MFacebookScanResultsTemplate[M_getScanResultIndexByID("23")].URL=c.find('div[class="_56be"]:eq(2) a[class="_5b6s"]:eq(1)').attr("href");MFacebookScanResultsTemplate[M_getScanResultIndexByID("24")].URL=c.find('div[class="_56be"]:eq(2) a[class="_5b6s"]:eq(2)').attr("href");g++;b()},e);SendWebRequest({type:"GET",data:null,dataType:"html",url:URLList.TimeLineAndTagging},function(c){c=TMExt_$(c);MFacebookScanResultsTemplate[M_getScanResultIndexByID("31")].URL=
c.find('div[class="_56be"]:eq(0) a[class="_5b6s"]:eq(1)').attr("href");MFacebookScanResultsTemplate[M_getScanResultIndexByID("33")].URL=c.find('div[class="_56be"]:eq(1) a[class="_5b6s"]:eq(0)').attr("href");MFacebookScanResultsTemplate[M_getScanResultIndexByID("34")].URL=c.find('div[class="_56be"]:eq(1) a[class="_5b6s"]:eq(1)').attr("href");MFacebookScanResultsTemplate[M_getScanResultIndexByID("35")].URL=c.find('div[class="_56be"]:eq(2) a[class="_5b6s"]:eq(0)').attr("href");g++;b()},e);SendWebRequest({type:"GET",
data:null,dataType:"html",url:URLList.Apps},function(c){c=TMExt_$(c);MFacebookScanResultsTemplate[M_getScanResultIndexByID("81")].URL=c.find('div[class="_56be"]:eq(2) a[class="_5b6s"]:eq(0)').attr("href");MFacebookScanResultsTemplate[M_getScanResultIndexByID("83")].URL=c.find('div[class="_56be"]:last a[class="_5b6s"]:eq(0)').attr("href");g++;b()},e)};h.prototype.scanSingle=function(d,e){function b(c){c=(new APIResponseHelper(g.responseHeaderScanSingle,ReturnCodeEnum.NETWORK_ERROR.code,ReturnCodeEnum.NETWORK_ERROR.description)).getResponse();
PSDebug.error(c);return e(c)}function f(){if(!c.isValidID(d)){var f=(new APIResponseHelper(g.responseHeaderScanSingle,ReturnCodeEnum.INVALID_ID.code,ReturnCodeEnum.INVALID_ID.description,"wrong ID! : "+d+", availableIDS: "+c.getAllvalidID())).getResponse();PSDebug.error(f);return e(f)}SendWebRequest(c.getSendData(d),function(b){var a=c.handleResponse(d,b);if(!a)return b=(new APIResponseHelper(g.responseHeaderScanSingle,ReturnCodeEnum.WEBRESPONSE_PARSE_ERROR.code,ReturnCodeEnum.WEBRESPONSE_PARSE_ERROR.description,
"Web content parse error! ID: "+d+", webData: "+b)).getResponse(),PSDebug.error(b),e(b);b=(new APIResponseHelper(g.responseHeaderScanSingle,ReturnCodeEnum.OK.code,ReturnCodeEnum.OK.description,{ID:a.ID,Risk:a.Risk,Title:a.Title,Desc:a.Desc,PossibleValue:a.PossibleValue,possibleFixValue:a.possibleFixValue,Current:a.Current,Suggestion:a.Suggestion,Category:a.Category,Website:a.Website})).getResponse();PSDebug.log(b);return e(b)},b)}var g=this,c=new MFacebookScannerHelper;if(MFacebookScanResultsTemplate[M_getScanResultIndexByID(d)].URL)return f();
g.getAllURLInfo(function(){return f()},b)};h.prototype.scan=function(d){function e(a){if(!h){if(a[b.responseHeaderScanSingle].ReturnCode==ReturnCodeEnum.OK.code)switch(a=a[b.responseHeaderScanSingle].Response,parseInt(a.ID)){case 20:case 22:case 23:case 24:f.PrivacySetting.Items.push(a);break;case 31:case 33:case 34:case 35:f.TimeLineAndTagging.Items.push(a);break;case 81:case 83:f.AppsAndWebsites.Items.push(a)}else if(a[b.responseHeaderScanSingle].ReturnCode==ReturnCodeEnum.WEBRESPONSE_PARSE_ERROR.code)k=
!0;else return a=(new APIResponseHelper(b.responseHeaderScan,a[b.responseHeaderScanSingle].ReturnCode,a[b.responseHeaderScanSingle].Description,a[b.responseHeaderScanSingle].Response)).getResponse(),PSDebug.error(a),h=!0,d(a);c++;if(c==g)return a=k?(new APIResponseHelper(b.responseHeaderScan,ReturnCodeEnum.WEBRESPONSE_PARSE_ERROR_COULD_USE_PARTLY.code,ReturnCodeEnum.WEBRESPONSE_PARSE_ERROR_COULD_USE_PARTLY.description,f)).getResponse():(new APIResponseHelper(b.responseHeaderScan,ReturnCodeEnum.OK.code,
ReturnCodeEnum.OK.description,f)).getResponse(),PSDebug.log(a),d(a)}}var b=this,f={PrivacySetting:{ID:2,Items:[]},TimeLineAndTagging:{ID:3,Items:[]},AppsAndWebsites:{ID:8,Items:[]}},g=MFacebookScanResultsTemplate.length,c=0,h=!1,k=!1;b.getAllURLInfo(function(){for(var a=0;a<MFacebookScanResultsTemplate.length;a++)b.scanSingle(MFacebookScanResultsTemplate[a].ID,e)},function(a){a=(new APIResponseHelper(b.responseHeaderScan,ReturnCodeEnum.NETWORK_ERROR.code,ReturnCodeEnum.NETWORK_ERROR.description)).getResponse();
PSDebug.error(a);return d(a)})};h.prototype.Website="MFACEBOOK";window.MFacebookPScanner=h;window.MPSScan={scanSingle:function(d,e){(new h).scanSingle(d,function(b){return e(b.MFPScanSingleResponse.Response)})},scan:function(d){(new h).scan(function(e){return d(e.MFPScanResponse.Response)})}}})();
