(function(){window.substringBetween=function(a,c,e){if(null==e)return null;var f=e.indexOf(a);if(-1==f)return null;c=e.indexOf(c,f+a.length);return-1==c?null:e.substring(f+a.length,c)};window.SettingConstants={is_first_savechange:"IsFirstSaveChanges",is_first_fixtwitter:"IsFirstFixTwitter",is_first_fixlinkedin:"IsFirstFixLinkedIn",is_console_log_enabled:"IsConsoleLogEnabled",is_file_log_enabled:"IsFileLogEnabled"};window.PrivacyScannerGlobalSettings={};var d=function(){var a=function(a){try{console&&
console.log?console.log(a):window.console&&window.console.info&&window.console.info.apply(console,arguments)}catch(c){}},c=function(a,c){var e;try{e=TMExt_$.toJSON(c)}catch(b){e=c}return a+e},e=function(a){!b.checkBrowser.IsIE()&&window.PrivacyScannerGlobalSettings[SettingConstants.is_file_log_enabled]&&(a={type:"write_file_log",dataIn:{data:a}},"undefined"!=typeof PSLocalSendMessage?PSLocalSendMessage(a):"undefined"!=typeof PSContentSendMessage&&PSContentSendMessage(a))};return{log:function(f){var b=
c("[LOG]",f),g=window.PrivacyScannerGlobalSettings[SettingConstants.is_console_log_enabled];if("undefined"==typeof g||g)"undefined"!=typeof console&&"undefined"!=typeof console.debug?console.debug(f):a(b);e(b)},info:function(f){var b=c("[INFO]",f),g=window.PrivacyScannerGlobalSettings[SettingConstants.is_console_log_enabled];if("undefined"==typeof g||g)"undefined"!=typeof console&&"undefined"!=typeof console.info?console.info(f):a(b);e(b)},warn:function(b){var d=c("[WARN]",b),g=window.PrivacyScannerGlobalSettings[SettingConstants.is_console_log_enabled];
if("undefined"==typeof g||g)"undefined"!=typeof console&&"undefined"!=typeof console.warn?console.warn(b):a(d);e(d)},error:function(b){var d=c("[ERROR]",b),g=window.PrivacyScannerGlobalSettings[SettingConstants.is_console_log_enabled];if("undefined"==typeof g||g)"undefined"!=typeof console&&"undefined"!=typeof console.error?console.error(b):a(d);e(d)}}}(),b={cloneObj:function(a){return JSON.parse(JSON.stringify(a))},checkPage:{InDomain:function(a){return-1!=window.location.host.indexOf(a)?!0:!1},
IsFacebook:function(){return b.checkPage.InDomain("facebook.com")},IsTwitter:function(){return b.checkPage.InDomain("twitter.com")},IsGooglePlus:function(){return b.checkPage.InDomain("google.com")},IsLinkedIn:function(){return b.checkPage.InDomain("linkedin.com")}},checkBrowser:{IsSafari:function(){return"undefined"!==typeof safari},IsChrome:function(){return"undefined"===typeof safari&&"undefined"!==typeof chrome},IsFirefox:function(){return-1!==navigator.userAgent.toLowerCase().indexOf("firefox")},
IsIE:function(){var a=!1;try{a="undefined"!=typeof ActiveXObject||"undefined"!=typeof new ActiveXObject("Microsoft.XMLHTTP")}catch(c){}return a},IsIELowerThan_8:function(){if(b.checkBrowser.IsIE())try{if("undefined"!=typeof TMExt_$.browser&&"undefined"!=typeof TMExt_$.browser.version&&8>parseFloat(TMExt_$.browser.version))return!0}catch(a){}return!1},IsIE_8:function(){if(b.checkBrowser.IsIE())try{if("undefined"!=typeof TMExt_$.browser&&"undefined"!=typeof TMExt_$.browser.version&&8==parseInt(TMExt_$.browser.version))return!0}catch(a){}return!1},
IsIELowerThan_9:function(){if(b.checkBrowser.IsIE())try{if("undefined"!=typeof TMExt_$.browser&&"undefined"!=typeof TMExt_$.browser.version&&9>parseFloat(TMExt_$.browser.version))return!0}catch(a){}return!1},IsIE_9:function(){if(b.checkBrowser.IsIE())try{if("undefined"!=typeof TMExt_$.browser&&"undefined"!=typeof TMExt_$.browser.version&&9==parseInt(TMExt_$.browser.version))return!0}catch(a){}return!1}},GetIEObject:function(a){if(!b.checkBrowser.IsIE())return!1;if(a){if(!window.g_oTMIEObject)try{window.g_oTMIEObject=
new ActiveXObject("ProToolbarIMRatingActiveX.ToolbarCB")}catch(c){window.g_oTMIEObject=null}a=window.g_oTMIEObject&&"undefined"!=typeof window.g_oTMIEObject.ToolbarInvoke&&!1!=window.g_oTMIEObject.ToolbarInvoke({test_key:"test_value"})?window.g_oTMIEObject:null}else a="undefined"!=typeof window.external.ToolbarInvoke?window.external:null;return a}},h=function(a,c,b,f){a?(this.header=a,this.Response={},this.Response[a]={},this.Response[a].ReturnCode=c,this.Response[a].Description=b?b:"",this.Response[a].Response=
f?f:""):d.error("header must be non-null:"+a)};h.prototype.setResponseItem=function(a,c){this.Response[this.header][a]=c};h.prototype.getResponse=function(){return this.Response};var k=function(a,c){this.logHeader=a?a:"default logHeader";c?this.params=c:d.error(this.logHeader+": params shouldn't be null")};k.prototype.getLog=function(){d.log(this.logHeader);d.log(this.params)};var l=function(a,c){this.logHeader=a?a:"default logHeader";c?this.data=c:d.error(this.logHeader+": data shouldn't be null")};
l.prototype.getLog=function(){d.log(this.logHeader);d.log(this.data)};window.CookieUtil={get:function(a){a=encodeURIComponent(a)+"=";var c=document.cookie.indexOf(a),b=null;0<=c&&(b=document.cookie.indexOf(";",c),-1==b&&(b=document.cookie.length),b=decodeURIComponent(document.cookie.substring(c+a.length,b)));return b}};window.PUtil=b;window.SendDataLogger=k;window.ResponseHandlerLogger=l;window.ReturnCodeEnum={OK:{code:"0",description:"ok"},UNKNOWN_EXCEPTION:{code:"90000000",description:"unknown exception"},
NETWORK_ERROR:{code:"90000001",description:"network error"},WEBRESPONSE_PARSE_ERROR:{code:"90000002",description:"for scan single, it means parse error. for scan, it means all setting are parsed error."},NOT_LOGGED_IN:{code:"90000003",description:"user didn't logged in"},INVALID_ID:{code:"90000004",description:"invalid ID"},INVALID_FIX_VALUE:{code:"90000005",description:"invalid fix value"},WEBRESPONSE_PARSE_ERROR_COULD_USE_PARTLY:{code:"90000006",description:"web response parse error, not all of the settings could be got. but the result which could be handled will be stored into response"},
PERFORM_CLICK_FAIL:{code:"90000007",description:"perform click fail"}};window.APIResponseHelper=h;window.PSDebug=d})();
