var blockedUrl=function(){var a="",a=(a=getUrlParam("url_session_id"))?SendMailtoPlugToolbar('{"params":{"actionID":20009,"paramsIn":{"url_session_id":"'+a+'"}}}')||getUrlParam("url"):getUrlParam("url");return decodeURIComponent(a)}(),timesCookieName="ShowLearnMoreTimes",STRINGS={address:blockedUrl,lbl_title_bar:GetWCCL10NString("lbl_title_bar").replace("%TiProductName%",decodeURI(getUrlParam("product_name_ti"))),lbl_page_title:GetWCCL10NString("lbl_page_title").replace("%TiProductName%",decodeURI(getUrlParam("product_name_ti"))),
lbl_status:GetWCCL10NString("lbl_status"),lbl_address:GetWCCL10NString("lbl_address"),lbl_desc_part1:GetWCCL10NString("lbl_desc_part1"),lbl_desc_part2:GetWCCL10NString("lbl_desc_part2").replace("%URL%",blockedUrl),lbl_close_window_desc:GetWCCL10NString("lbl_close_window_desc"),lbl_handler_desc:GetWCCL10NString("lbl_handler_desc"),lbl_EPM_handler_desc:GetWCCL10NString("lbl_EPM_handler_desc"),lbl_btn_close_window:GetWCCL10NString("lbl_btn_close_window"),lbl_review:GetWCCL10NString("lbl_review"),lbl_siteowner:GetWCCL10NString("lbl_siteowner"),
txt_email_placeholder:GetWCCL10NString("txt_email_placeholder"),lbl_validate_email:GetWCCL10NString("lbl_validate_email"),txt_description_placeholder:GetWCCL10NString("txt_description_placeholder"),lbl_add_approved_list:GetWCCL10NString("lbl_add_approved_list"),lbl_btn_view_anyway:GetWCCL10NString("lbl_btn_view_anyway"),lbl_promotion_title:GetWCCL10NString("lbl_promotion_title"),lbl_promotion_content:GetWCCL10NString("lbl_promotion_content"),lbl_buy_now:GetWCCL10NString("lbl_buy_now"),lbl_copyright:GetWCCL10NString("lbl_copyright"),
lbl_learn_more_link:GetWCCL10NString("lbl_learn_more_link"),lbl_learn_more_desc:GetWCCL10NString("lbl_learn_more_desc"),link_learn_more:GetWCCL10NString("link_learn_more"),link_learn_more_attack_all:GetWCCL10NString("link_learn_more_attack_all")},CONFIG={url:blockedUrl,url_continue:blockedUrl,lang:"%TiLang%",param_url:function(){return"URL="+encodeURIComponent(this.url)},param_permanent:"Permanent=1",getGAOpt:function(){var a=this.url.match(/^(https?:\/\/)(.+)$/),b="/"+a[2];return{account:"%GaAccount%",
clientId:"%GaClientId%",hostname:"%GaFakeHost%",location:(a[1]||"http://")+"%GaFakeHost%"+b,path:b,title:document.title||""}}};(function(a,b,c){-1<c.indexOf("firefox")&&/^tmpx:\/\//.test(window.location.href)&&a.addEventListener("load",function(){var a=b.createElement("SCRIPT");a.src="url_block.js";a.onload=function(){init();post_init()};b.body.onload=null;b.body.parentNode.insertBefore(a,b.body)},!1)})(window,document,navigator.userAgent.toLowerCase());
var wtpScore=parseInt("%WRSScore%"),isShowBuyNowButton="%TiShowBuyNowLink%",isShowBuyNowButton="true"===isShowBuyNowButton;"undefined"===typeof $&&($=function(a){return document.getElementById(a.replace(/#/ig,""))});function getStyle(a,b){var c=$("#"+a);if(c&&c.currentStyle)var d=c.currentStyle[b];else window.getComputedStyle&&(d=document.defaultView.getComputedStyle(c,null).getPropertyValue(b));return d}
function init(){document.getElementsByTagName("body")[0].className=CONFIG.lang;var a=$("#embedded_css");"0px"!=getStyle("lbl_status","padding-left")&&a&&document.getElementsByTagName("head")[0].removeChild(a);window.fillInBlockingContent&&window.fillInBlockingContent();var a=$("#btn_close_window"),b=$("#lbl_status"),c=$("#status_icon");b.className+=" sign_dangerous";c.className+=" sign_dangerous";localizePageContent(STRINGS);a.onmousedown=function(){this.className+=" active"};a.onmouseup=function(){this.className=
this.className.replace(/active/ig,"")};a.onclick=function(){window.close();return!1};$("#btn_try_another").setAttribute("href",blockedUrl);$("#btn_try_another").onclick=takeAction;$("#lbl_handler_desc").onclick=toggleExtraOptions;$("#review").onclick=toggleFeedback;$("#chk_siteowner").onclick=toggleEmail;$("#review").checked=$("#chk_siteowner").checked=$("#add_approved_list").checked=!1;a=$("#txt_email_placeholder");a.onfocus=focusEmailEvent;a.onblur=blurEmailEvent;a.className+=" placeholder";a.value=
a.getAttribute("placeholder");a=$("#txt_description_placeholder");a.onfocus=focusDescEvent;a.onblur=blurDescEvent;a.className+=" placeholder";a.value=a.getAttribute("placeholder");document.onselectstart=function(){return!1}}
function post_init(){if(isShowBuyNowButton){var a=CONFIG.getGAOpt();ga("create",a.account,{name:"trend",storage:"none",cookieDomain:"none",clientId:a.clientId});ga("trend.set","location",a.location);ga("trend.set","hostname",a.hostname);ga("trend.set","page",a.path);ga("trend.send","pageview");var b=!1;$("#lbl_buy_now").onclick=function(){b||(ga("trend.send","event","Trail user","Click buy now"),b=!0)};$("#advertisement").className=$("#advertisement").className.replace(/hidden/ig,"")}showAttackAll()?
($("#lbl_learn_more_desc").className=$("#lbl_learn_more_desc").className.replace(/hidden/ig,""),$("#lbl_learn_more_link").href=STRINGS.link_learn_more_attack_all):$("#lbl_learn_more_link").href=STRINGS.link_learn_more}
function localizePageContent(a){for(var b in a)if("lbl_title_bar"==b)document.title=a.lbl_title_bar;else if("alt_"==b.substr(0,4))insertString(b,a[b],"alt");else if("ttl_"==b.substr(0,4))insertString(b,a[b],"title");else if(b.match(/txt_\w*_placeholder/))insertString(b,a[b],"placeholder");else if("lbl_EPM_handler_desc"==b)insertString(b,a[b].replace(/href=\'\'/ig,"href='%IKBURL%'"));else if("msg_for_submission"==b)break;else insertString(b,a[b])}
function insertString(a,b,c){document.getElementById&&$("#"+a)&&(void 0===c?$("#"+a).innerHTML=b:$("#"+a).setAttribute(c,b))}
function takeAction(){var a=$("#add_approved_list").checked,b=$("#review").checked,c=CONFIG.url_continue,d="",e=document.createElement("a");e.href=c;d=a?'{"params":{"actionID":20008,"paramsIn":{"url":"'+e.href+'","hostname":"'+e.hostname+'","port":'+(e.port||443)+"}}}":'{"params":{"actionID":20007,"paramsIn":{"url":"'+e.href+'","hostname":"'+e.hostname+'","port":'+(e.port||443)+"}}}";SendMailtoPlugToolbar(d);b&&(a=$("#txt_email_placeholder").value.substr(0,63),b=$("#txt_description_placeholder").value.substr(0,
1023),d='{"params":{"actionID":20012,"paramsIn":{"url":"'+e.href+'","email":"'+a+'","desc":"'+b+'"}}}',SendMailtoPlugToolbar(d));setTimeout(function(){document.location=c},2E3);return!1}function toggleExtraOptions(){var a=$("#more_actions"),b=$("#handler");-1<a.className.indexOf("hidden")?(a.className=a.className.replace(/hidden/ig,""),b.className=b.className.replace(/ico_collapse/ig,"ico_expand")):(a.className+=" hidden",b.className=b.className.replace(/ico_expand/ig,"ico_collapse"));return!1}
function toggleFeedback(){var a=$("#feedback");a.className=this.checked?a.className.replace(/hidden/ig,""):a.className+" hidden"}function toggleEmail(){var a=$("#txt_email_placeholder"),b=$("#txt_description_placeholder"),c=$("#lbl_validate_email");this.checked?(a.removeAttribute("disabled"),b.removeAttribute("disabled")):(a.setAttribute("disabled","disabled"),b.setAttribute("disabled","disabled"),c.className+=" hidden")}
function focusEmailEvent(){var a=$("#lbl_validate_email");this.value===this.getAttribute("placeholder")&&(this.value="");this.className=this.className.replace(/placeholder/ig,"");a.className+=" hidden"}function blurEmailEvent(){var a=$("#lbl_validate_email"),b=$("#txt_email_placeholder"),c=b.value,d=b.getAttribute("placeholder");if(c===d||""===c||c!==d&&!validateEmail(c))return b.value=d,b.className+=" placeholder",a.className=a.className.replace(/hidden/ig,""),!1}
function validateEmail(a){return/^([a-zA-Z0-9_\-]+)([a-zA-Z0-9_\.\-]*)@([a-zA-Z0-9_\-]+)\.([a-zA-Z0-9_\.\-]*)([a-zA-Z]{2,})$/.test(a)}function focusDescEvent(){this.value===this.getAttribute("placeholder")&&(this.value="");this.className=this.className.replace(/placeholder/ig,"")}function blurDescEvent(){""===this.value&&(this.value=this.getAttribute("placeholder"),this.className+=" placeholder")}
function setCookie(a,b){var c=new Date;c.setDate(c.getDate()+90);document.cookie=a+"="+escape(b)+";expires="+c.toGMTString()}function getCookie(a){return 0<document.cookie.length&&(c_start=document.cookie.indexOf(a+"="),-1!=c_start)?(c_start=c_start+a.length+1,c_end=document.cookie.indexOf(";",c_start),-1==c_end&&(c_end=document.cookie.length),unescape(document.cookie.substring(c_start,c_end))):""}function showAttackAll(){return parseInt(getUrlParam("show_more"))}init();post_init();
