(function(){window.MAIN_CONSOLE="MAIN_CONSOLE";window.FACEBOOK="FACEBOOK";window.TWITTER="TWITTER";window.GOOGLEPLUS="GOOGLEPLUS";window.LINKEDIN="LINKEDIN";window.INTERNET_EXPLORER="INTERNET_EXPLORER";window.CHROME="CHROME";window.FIREFOX="FIREFOX";window.AllSites=[FACEBOOK,TWITTER,GOOGLEPLUS,LINKEDIN];window.AllBrowsers=[INTERNET_EXPLORER,CHROME,FIREFOX];window.AllSiteAndBrowser=function(){var d=[];TMExt_$.each(AllSites,function(b,e){d.push(e)});TMExt_$.each(AllBrowsers,function(b,e){d.push(e)});
return d}();window.LocalUtil={ParamFromURL:{getParam:function(d){var b=document.location.search;if("string"==typeof b&&0<b.length)for(var b=b.substring(1),b=b.split("&"),e=0;e<b.length;e++){var f=b[e].split("=");if(f[0]==d)return f[1]}return null},GetTabList:function(){var d={ITIS:{BROWSER_TOOLBAR:{DESCRIPTION:"Scan Facebook/Twitter/LinkedIn, focus on Facebook",PATTERN:{FACEBOOK:"1110",TWITTER:"0110",GOOGLEPLUS:"0010",LINKEDIN:"0110",INTERNET_EXPLORER:"0000",FIREFOX:"0000",CHROME:"0000"}},SNS_FACEBOOK:{DESCRIPTION:"Scan Facebook, focus on Facebook",
PATTERN:{FACEBOOK:"1110",TWITTER:"0010",GOOGLEPLUS:"0010",LINKEDIN:"0010",INTERNET_EXPLORER:"0000",FIREFOX:"0000",CHROME:"0000"},FROM:FACEBOOK,PSUsageInfo:FACEBOOK},SNS_TWITTER:{DESCRIPTION:"Scan Twitter, focus on Twitter",PATTERN:{FACEBOOK:"0010",TWITTER:"1110",GOOGLEPLUS:"0010",LINKEDIN:"0010",INTERNET_EXPLORER:"0000",FIREFOX:"0000",CHROME:"0000"},FROM:TWITTER,PSUsageInfo:TWITTER},SNS_GOOGLEPLUS:{DESCRIPTION:"Scan GooglePlus, focus on GooglePlus",PATTERN:{FACEBOOK:"0010",TWITTER:"0010",GOOGLEPLUS:"1110",
LINKEDIN:"0010",INTERNET_EXPLORER:"0000",FIREFOX:"0000",CHROME:"0000"},FROM:GOOGLEPLUS,PSUsageInfo:GOOGLEPLUS},SNS_LINKEDIN:{DESCRIPTION:"Scan LinkedIn, focus on LinkedIn",PATTERN:{FACEBOOK:"0010",TWITTER:"0010",GOOGLEPLUS:"0010",LINKEDIN:"1110",INTERNET_EXPLORER:"0000",FIREFOX:"0000",CHROME:"0000"},FROM:LINKEDIN,PSUsageInfo:LINKEDIN}},STORE:{BROWSER_TOOLBAR:{DESCRIPTION:"Scan GooglePlus, focus on GooglePlus, Facebook/Twitter/LinkedIn show BuyNow",PATTERN:{FACEBOOK:"0011",TWITTER:"0011",GOOGLEPLUS:"1110",
LINKEDIN:"0011",INTERNET_EXPLORER:"0000",FIREFOX:"0000",CHROME:"0000"}},SNS_GOOGLEPLUS:{DESCRIPTION:"Scan GooglePlus, focus on GooglePlus, Facebook/Twitter show BuyNow",PATTERN:{FACEBOOK:"0011",TWITTER:"0011",GOOGLEPLUS:"1110",LINKEDIN:"0011",INTERNET_EXPLORER:"0000",FIREFOX:"0000",CHROME:"0000"},FROM:GOOGLEPLUS,PSUsageInfo:GOOGLEPLUS}},TI6:{BROWSER_TOOLBAR:{DESCRIPTION:"Scan Facebook/Google+, focus on Facebook",PATTERN:{FACEBOOK:"1110",TWITTER:"0000",GOOGLEPLUS:"0110",LINKEDIN:"0000",INTERNET_EXPLORER:"0000",
FIREFOX:"0000",CHROME:"0000"}},SNS_FACEBOOK:{DESCRIPTION:"Scan Facebook, focus on Facebook",PATTERN:{FACEBOOK:"1110",TWITTER:"0000",GOOGLEPLUS:"0010",LINKEDIN:"0000",INTERNET_EXPLORER:"0000",FIREFOX:"0000",CHROME:"0000"},FROM:FACEBOOK,PSUsageInfo:FACEBOOK},SNS_GOOGLEPLUS:{DESCRIPTION:"Scan GooglePlus, focus on GooglePlus",PATTERN:{FACEBOOK:"0010",TWITTER:"0000",GOOGLEPLUS:"1110",LINKEDIN:"0000",INTERNET_EXPLORER:"0000",FIREFOX:"0000",CHROME:"0000"},FROM:GOOGLEPLUS,PSUsageInfo:GOOGLEPLUS}},TI7:{BROWSER_TOOLBAR:{DESCRIPTION:"Scan Facebook/Twitter, focus on Facebook",
PATTERN:{FACEBOOK:"1110",TWITTER:"0110",GOOGLEPLUS:"0010",LINKEDIN:"0000",INTERNET_EXPLORER:"0000",FIREFOX:"0000",CHROME:"0000"}},SNS_FACEBOOK:{DESCRIPTION:"Scan Facebook, focus on Facebook",PATTERN:{FACEBOOK:"1110",TWITTER:"0010",GOOGLEPLUS:"0010",LINKEDIN:"0000",INTERNET_EXPLORER:"0000",FIREFOX:"0000",CHROME:"0000"},FROM:FACEBOOK,PSUsageInfo:FACEBOOK},SNS_TWITTER:{DESCRIPTION:"Scan Twitter, focus on Twitter",PATTERN:{FACEBOOK:"0010",TWITTER:"1110",GOOGLEPLUS:"0010",LINKEDIN:"0000",INTERNET_EXPLORER:"0000",
FIREFOX:"0000",CHROME:"0000"},FROM:TWITTER,PSUsageInfo:TWITTER},SNS_GOOGLEPLUS:{DESCRIPTION:"Scan GooglePlus, focus on GooglePlus",PATTERN:{FACEBOOK:"0010",TWITTER:"0010",GOOGLEPLUS:"1110",LINKEDIN:"0000",INTERNET_EXPLORER:"0000",FIREFOX:"0000",CHROME:"0000"},FROM:GOOGLEPLUS,PSUsageInfo:GOOGLEPLUS}},TI8:{MAINCONSOLE_SNS:{DESCRIPTION:"Scan Facebook/Twitter/LinkedIn/IE/Firefox/Chrome, focus on Facebook",PATTERN:{FACEBOOK:"1110",TWITTER:"0110",GOOGLEPLUS:"0010",LINKEDIN:"0110",INTERNET_EXPLORER:"0110",
FIREFOX:"0110",CHROME:"0110"},PSUsageInfo:MAIN_CONSOLE},MAINCONSOLE_BROWSER:{DESCRIPTION:"Scan IE/Firefox/Chrome, focus on IE",PATTERN:{FACEBOOK:"0010",TWITTER:"0010",GOOGLEPLUS:"0010",LINKEDIN:"0010",INTERNET_EXPLORER:"1110",FIREFOX:"0110",CHROME:"0110"},PSUsageInfo:MAIN_CONSOLE},BROWSER_TOOLBAR:{DESCRIPTION:"Scan Facebook/Twitter/LinkedIn/IE/Firefox/Chrome, focus on Facebook",PATTERN:{FACEBOOK:"1110",TWITTER:"0110",GOOGLEPLUS:"0010",LINKEDIN:"0110",INTERNET_EXPLORER:"0110",FIREFOX:"0110",CHROME:"0110"}},
SNS_FACEBOOK:{DESCRIPTION:"Scan Facebook/IE/Firefox/Chrome, focus on Facebook",PATTERN:{FACEBOOK:"1110",TWITTER:"0010",GOOGLEPLUS:"0010",LINKEDIN:"0010",INTERNET_EXPLORER:"0110",FIREFOX:"0110",CHROME:"0110"},FROM:FACEBOOK,PSUsageInfo:FACEBOOK},SNS_TWITTER:{DESCRIPTION:"Scan Twitter/IE/Firefox/Chrome, focus on Twitter",PATTERN:{FACEBOOK:"0010",TWITTER:"1110",GOOGLEPLUS:"0010",LINKEDIN:"0010",INTERNET_EXPLORER:"0110",FIREFOX:"0110",CHROME:"0110"},FROM:TWITTER,PSUsageInfo:TWITTER},SNS_GOOGLEPLUS:{DESCRIPTION:"Scan GooglePlus/IE/Firefox/Chrome, focus on GooglePlus",
PATTERN:{FACEBOOK:"0010",TWITTER:"0010",GOOGLEPLUS:"1110",LINKEDIN:"0010",INTERNET_EXPLORER:"0110",FIREFOX:"0110",CHROME:"0110"},FROM:GOOGLEPLUS,PSUsageInfo:GOOGLEPLUS},SNS_LINKEDIN:{DESCRIPTION:"Scan LinkedIn/IE/Firefox/Chrome, focus on LinkedIn",PATTERN:{FACEBOOK:"0010",TWITTER:"0010",GOOGLEPLUS:"0010",LINKEDIN:"1110",INTERNET_EXPLORER:"0110",FIREFOX:"0110",CHROME:"0110"},FROM:LINKEDIN,PSUsageInfo:LINKEDIN}},TI9_OrLater:{MAINCONSOLE_SNS:{DESCRIPTION:"Scan Facebook/Twitter/LinkedIn/IE/Firefox/Chrome, focus on Facebook",
PATTERN:{FACEBOOK:"1110",TWITTER:"0110",GOOGLEPLUS:"0010",LINKEDIN:"0110",INTERNET_EXPLORER:"0110",FIREFOX:"0110",CHROME:"0110"},PSUsageInfo:MAIN_CONSOLE},MAINCONSOLE_BROWSER:{DESCRIPTION:"Scan IE/Firefox/Chrome, focus on IE",PATTERN:{FACEBOOK:"0010",TWITTER:"0010",GOOGLEPLUS:"0010",LINKEDIN:"0010",INTERNET_EXPLORER:"1110",FIREFOX:"0110",CHROME:"0110"},PSUsageInfo:MAIN_CONSOLE},BROWSER_TOOLBAR:{DESCRIPTION:"Scan Facebook/Twitter/LinkedIn/IE/Firefox/Chrome, focus on Facebook",PATTERN:{FACEBOOK:"1110",
TWITTER:"0110",GOOGLEPLUS:"0010",LINKEDIN:"0110",INTERNET_EXPLORER:"0110",FIREFOX:"0110",CHROME:"0110"}},SNS_FACEBOOK:{DESCRIPTION:"Scan Facebook/IE/Firefox/Chrome, focus on Facebook",PATTERN:{FACEBOOK:"1110",TWITTER:"0010",GOOGLEPLUS:"0010",LINKEDIN:"0010",INTERNET_EXPLORER:"0110",FIREFOX:"0110",CHROME:"0110"},FROM:FACEBOOK,PSUsageInfo:FACEBOOK},SNS_TWITTER:{DESCRIPTION:"Scan Twitter/IE/Firefox/Chrome, focus on Twitter",PATTERN:{FACEBOOK:"0010",TWITTER:"1110",GOOGLEPLUS:"0010",LINKEDIN:"0010",INTERNET_EXPLORER:"0110",
FIREFOX:"0110",CHROME:"0110"},FROM:TWITTER,PSUsageInfo:TWITTER},SNS_GOOGLEPLUS:{DESCRIPTION:"Scan GooglePlus/IE/Firefox/Chrome, focus on GooglePlus",PATTERN:{FACEBOOK:"0010",TWITTER:"0010",GOOGLEPLUS:"1110",LINKEDIN:"0010",INTERNET_EXPLORER:"0110",FIREFOX:"0110",CHROME:"0110"},FROM:GOOGLEPLUS,PSUsageInfo:GOOGLEPLUS},SNS_LINKEDIN:{DESCRIPTION:"Scan LinkedIn/IE/Firefox/Chrome, focus on LinkedIn",PATTERN:{FACEBOOK:"0010",TWITTER:"0010",GOOGLEPLUS:"0010",LINKEDIN:"1110",INTERNET_EXPLORER:"0110",FIREFOX:"0110",
CHROME:"0110"},FROM:LINKEDIN,PSUsageInfo:LINKEDIN}}},b=LocalUtil.ParamFromURL.getParam("from").split(","),e=b[0],b=b[1];return d[e]?d[e][b]:d.TI9_OrLater[b]},BrowserID:function(){return LocalUtil.ParamFromURL.getParam("browser_id")},BrowserVersion:function(){return LocalUtil.ParamFromURL.getParam("browser_version")},Locale:function(){return LocalUtil.ParamFromURL.getParam("locale")},Status:function(){return LocalUtil.ParamFromURL.getParam("status")},Restart_Browser:function(){return LocalUtil.ParamFromURL.getParam(URL_PARAM_RESTART_BROWSER)}}};
window.OptionSetting=function(){var d=function(){return{is_Focus:function(a){return parseInt(a,2)&8},is_Scan:function(a){return parseInt(a,2)&4},is_Show:function(a){return parseInt(a,2)&2},is_Buy:function(a){return parseInt(a,2)&1}}}(),b=LocalUtil.ParamFromURL.GetTabList(),e=function(a){a={CHROME:0,FIREFOX:1,INTERNET_EXPLORER:2}[a];var c=LocalUtil.ParamFromURL.Status();return c?"1"===c.split("_")[a][1]:!1},f=function(a){for(var c=0,b=AllBrowsers.length;c<b;c++)if(a===AllBrowsers[c])return!0;return!1};
return{getShowSiteOrBrowserList:function(){var a=[],c;for(c in b.PATTERN)!d.is_Show(b.PATTERN[c])||f(c)&&!e(c)||a.push(c);return a},getPromoteSiteOrBrowserList:function(){var a=[],c;for(c in b.PATTERN)d.is_Buy(b.PATTERN[c])&&a.push(c);return a},getScanSiteOrBrowsers:function(){var a=[],c;for(c in b.PATTERN)!d.is_Scan(b.PATTERN[c])||f(c)&&!e(c)||a.push(c);return a},getFocusOn:function(){var a=LocalUtil.ParamFromURL.Restart_Browser();if(a)return a;var a=FACEBOOK,c;for(c in b.PATTERN)d.is_Focus(b.PATTERN[c])&&
(a=c);return a}}}();window.CategoryList="People_can_see_your_personal_info Strangers_can_easily_track_you You_can_be_tagged_without_your_permission People_outside_of_Facebook_can_see_your_info People_can_see_where_you_were People_can_download_your_photos Advertizers_can_learn_more_about_you People_outside_of_Linkedin_can_see_your_info Strangers_could_monitor_your_connection Browser_phishing_protect Application_can_access_your_personal_info".split(" ");window.TIME_INTERVAL_NOT_LOG_IN_CHECK_AGAIN=1E3;
window.TIME_INTERVAL_NOT_LOG_IN_CHECK_AGAIN_IF_NETWORK_ERROR=5E3;window.TIMEOUT_SEND_REQUEST_TO_BACKGROUND=6E4;window.DURATION_TIME_SLIDE_DOWN_SAVECHANGES=200;window.DURATION_TIME_SLIDE_UP_SAVECHANGES=200;window.DURATION_TIME_SLIDE_UP_SETTINGS=500;window.DURATION_TIME_BACK_TO_TOP=800;window.POSITION_WHEN_BACK_TO_TOP_APPEAR=330;window.URL_LIST={FACEBOOK:{URL_SETTING_PAGE:"https://www.facebook.com/settings/?tab=privacy",URL_CHECKLOGIN_PAGE:"https://www.facebook.com/login.php",URL_ACCOUNT_PAGE:"https://www.facebook.com/"},
TWITTER:{URL_SETTING_PAGE:"https://twitter.com/settings/security",URL_CHECKLOGIN_PAGE:"https://twitter.com/settings/account",URL_ACCOUNT_PAGE:"https://twitter.com/"},GOOGLEPLUS:{URL_SETTING_PAGE:"https://plus.google.com/settings?gmbpt=true&fd=1",URL_CHECKLOGIN_PAGE:"https://myaccount.google.com/?pli=1",URL_ACCOUNT_PAGE:"https://accounts.google.com/Logout"},LINKEDIN:{URL_SETTING_PAGE:"https://www.linkedin.com/psettings/privacy",URL_FIX_SETTING_PAGE:{11:"https://www.linkedin.com/psettings/news-mention-broadcast",
12:"https://www.linkedin.com/psettings/data-sharing",13:"https://www.linkedin.com/psettings/enhanced-advertising"},URL_CHECKLOGIN_PAGE:"https://www.linkedin.com/",URL_ACCOUNT_PAGE:"https://www.linkedin.com/uas/login"}};window.IS_SCANING={FACEBOOK:!1,TWITTER:!1,GOOGLEPLUS:!1,LINKEDIN:!1,CHROME:!1,FIREFOX:!1,INTERNET_EXPLORER:!1};window.DCA_CONSTANTS={WEBSITE_OR_BROWSER_ID:{FACEBOOK:0,TWITTER:1,GOOGLEPLUS:2,LINKEDIN:3,CHROME:4,FIREFOX:5,INTERNET_EXPLORER:6,SAFARI:7},SETTING_ID:{SCAN:0,FIX:1},ERROR_ID:{NETWORK_ERROR:0,
TIMEOUT:1,BUSY_FIXING:2,BROWSER_TITANIUM_NOT_EXIST:100,BROWSER_DEFAULT_ERROR:101,BROWSER_IE_VERSION_LOW:102,BROWSER_CHROME_ACCOUNT_LOGGED_IN:103},HELP_ID:{SOMETHING_WRONG:0,KEEP_SEEING_DONT_CLOSE_TAB:1,BPS_SOMETHING_WRONG:2,GOOGLE_ACCOUNT_LOGGED_IN:3},PS_USAGE_WEBSITE_OR_BROWSER_ID:{FACEBOOK:7,TWITTER:9,GOOGLEPLUS:11,LINKEDIN:13,MAIN_CONSOLE:15}};window.BPS_RETURN_CODE={OK:0,IE_VERSION_LOW:3,TITANIUM_NOT_EXIST:301,CHROME_ACCOUNT_LOGGED_IN:200};window.UISettings={privacy_item_content:[{className:"privacy_item_content_setting_Longger_2",
list:[{name:TWITTER,ID:16}]},{className:"privacy_item_content_setting_Longger_1_5",list:[{name:FIREFOX,ID:"ff_do_not_track"}]}]};window.URL_PARAM_RESTART_BROWSER="restart_browser";window.CSS_anotherAccount_image_left=58;window.CSS_anotherAccount_name_gap=5})();
