(function(){window.ConstructFixAllSettingItem=function(a){var c=TMExt_$("<li/>"),d=TMExt_$("<div/>",{"class":"fixAll_item_content_title"}),b=TMExt_$("<div/>",{"class":"fixAll_item_content_title_icon"}),f=TMExt_$("<div/>",{"class":"fixAll_item_content_title_wording",text:a.Title});d.append(f).append(b);var b=TMExt_$("<div/>",{"class":"fixAll_item_content_current"}),f=TMExt_$("<div/>",{"class":"fixAll_item_content_current_icon"}),e=TMExt_$("<div/>",{"class":"fixAll_item_content_current_wording",text:a.PossibleValue[a.Current]});
b.append(f).append(e);var f=TMExt_$("<div/>",{"class":"fixAll_item_content_toIcon"}),e=TMExt_$("<div/>",{"class":"fixAll_item_content_suggestion"}),g=TMExt_$("<div/>",{"class":"fixAll_item_content_suggestion_icon"}),h=TMExt_$("<div/>",{"class":"fixAll_item_content_suggestion_wording",text:a.PossibleValue[a.Suggestion]});e.append(g).append(h);a=TMExt_$("<div/>",{"class":"Setting_display_none",text:TMExt_$.toJSON(a)});d=TMExt_$("<div/>",{"class":"fixAll_item_content_title_ul_li_content"}).append(d).append(b).append(f).append(e).append(a);
c.append(d);return c};window.ConstructEnableToolbar=function(){var a=TMExt_$("<div/>",{"class":"alertInTabContentArea"}),c=TMExt_$("<p/>",{"class":"enable_toolbar_wording",text:GetPSL10NString("ENABLE_TOOLBAR_HINT")}),d=TMExt_$("<a/>",{"class":"get_help_link",target:"_blank",text:GetPSL10NString("GET_MORE_HELP")});d.click(function(){window.open(GetPSL10NString("ENABLE_TOOLBAR_LINK"))});c.append(d);a.append(c);return a};window.ConstructAlertMessageOverContent_loading=function(a){a=TMExt_$("<div/>",
{"class":"alertOverTabContentArea"});var c=TMExt_$("<div/>",{"class":"alertOverTabContentArea_wrapper_loading"});a.append(c);return a};window.ConstructAlertMessageOverContent=function(a){var c=TMExt_$("<div/>",{"class":"alertOverTabContentArea"}),d=TMExt_$("<div/>",{"class":"alertOverTabContentArea_wrapper"}),b=TMExt_$("<div/>",{"class":"alertOverTabContentArea_wrapper_content"});d.append(b);c.append(d);a.closeButton&&(d=TMExt_$("<div/>",{"class":"overlay_container_closeButton"}),d.click(a.closeEvent),
b.append(d));a.head&&(d=TMExt_$("<div/>",{"class":"alertOverTabContentArea_head"}),b.append(d),d.html(a.head));b.append(TMExt_$("<div/>",{"class":"overlay_container_content"}));b.find(".overlay_container_content").html(a.title);b.append(TMExt_$("<div/>",{"class":"overlay_container_content_divider"}));if(a.buttons){var f=TMExt_$("<div/>",{"class":"overlay_container_buttonArea"});b.append(f)}a.buttons&&(1==a.buttons.length?(b=TMExt_$("<button/>",{"class":"btn_silver overlay_container_ok_only",text:a.buttons[0].title}),
b.click(a.buttons[0].callback),f.append(b)):2==a.buttons.length&&(b=TMExt_$("<button/>",{"class":"btn_blue overlay_container_ok",text:a.buttons[0].title}),b.click(a.buttons[0].callback),d=TMExt_$("<button/>",{"class":"btn_silver overlay_container_cancel",text:a.buttons[1].title}),d.click(a.buttons[1].callback),f.append(d).append(b)));if(a.checkBox){var b=TMExt_$("<label/>",{"class":"dont_mention_again_area"}),e=TMExt_$("<input/>",{"class":"dont_mention_again_area_input",type:"checkbox",checked:!1});
e.click(function(){a.checkBox.callback(e.is(":checked"))});b.append(e).append(a.checkBox.title);f.append(b)}return c};window.ConstructAlertMessageFixAll=function(a,c,d,b){var f=TMExt_$("<div/>",{"class":"alertOverTabContentArea"}),e=TMExt_$("<div/>",{"class":"overlay_quickFix_contentWrapper"}),g=TMExt_$("<div/>",{"class":"overlay_quickFix_content"});e.append(g);f.append(e);var e=TMExt_$("<div/>",{"class":"overlay_quickFix_header"}).append(TMExt_$("<div/>",{"class":"overlay_quickFix_content_title",
text:GetPSL10NString("QUICKFIX_TITLE")})).append(TMExt_$("<div/>",{"class":"overlay_quickFix_content_secondTitle",text:GetPSL10NString("QUICKFIX_DESCRIPTION")})),h=TMExt_$("<div/>",{"class":"overlay_quickFix_closeButton"});h.click(c);g.append(h);g.append(e);c=TMExt_$("<div/>",{"class":"overlay_quickFix_content_settingAndChanges"});e=TMExt_$("<div/>",{"class":"overlay_quickFix_content_settingAndChanges_textArea"}).append(TMExt_$("<div/>",{"class":"overlay_quickFix_content_settingAndChanges_shadowline_setting",
text:GetPSL10NString("QUICKFIX_SETTING")})).append(TMExt_$("<div/>",{"class":"overlay_quickFix_content_settingAndChanges_shadowline_current",text:GetPSL10NString("QUICKFIX_CURRENT")})).append(TMExt_$("<div/>",{"class":"overlay_quickFix_content_settingAndChanges_shadowline_changes",text:GetPSL10NString("QUICKFIX_NEW")}));c.append(e);g.append(c);c=TMExt_$("<ul/>",{"class":"overlay_quickFix_content_ul"});g.append(c);a=a.find(".Setting_display_none");for(e=0;e<a.length;e++)h=TMExt_$.parseJSON(a.eq(e).text()),
isSettingRisky(h.Current,h.Risk)&&c.append(ConstructFixAllSettingItem(h));a=TMExt_$("<div/>",{"class":"overlay_quickFix_content_buttonArea"});c=TMExt_$("<button/>",{"class":"btn_silver overlay_quickFix_content_buttonArea_cancel",text:GetPSL10NString("QUICKFIX_FIXALL_CANCEL")});c.click(b);b=TMExt_$("<button/>",{"class":"btn_red overlay_quickFix_content_buttonArea_fixAll",text:GetPSL10NString("QUICKFIX_FIXALL_BUTTON")});b.click(d);a.append(c).append(b);g.append(a);return f}})();
